- recipes-kernel/linux/linux-lmp-dev.bb
- recipes-kernel/linux/linux-lmp_git.bb
- recipes-sota/lmp-device-register/lmp-device-register_git.bb
All LMP sources have been moved to GitHub. This updates our defaults
to use the GitHub repositories for building the LMP.
> Convert to github source defaults

- recipes-bsp/u-boot/u-boot-compulab/enable_support_for_fitimage.patch
- recipes-bsp/u-boot/u-boot-compulab_2017.07.bb
- recipes-bsp/u-boot/u-boot-fslc/0001-mx6cuboxi-enable-FIT.patch
- recipes-bsp/u-boot/u-boot-fslc_%.bbappend
- recipes-bsp/u-boot/u-boot/0001-rpi-prefer-downstream-dtb-files.patch
- recipes-bsp/u-boot/u-boot/0001-rpi-set-CONFIG_SYS_BOOTM_LEN-to-32M.patch
- recipes-bsp/u-boot/u-boot/0001-rpi_defconfig-enable-support-for-FIT.patch
- recipes-bsp/u-boot/u-boot_%.bbappend
Before we officially transition to fitimage for all u-boot compatible targets, enable fitimage support in u-boot for early testing.
> Base support for u-boot fitimage

- recipes-kernel/linux-firmware/linux-firmware_git.bbappend
Latest firmware from upstream doesn't work properly on DB820c, so revert
back to the previous and known working version.
This reverts commit d913576b0c2299065b172e2ea58ab37156e5813a.
> Revert "linux-firmware: drop custom firmware revision for QCA6174"

- conf/distro/lmp.conf
- recipes-samples/images/lmp-image-common.inc
Aktualizr can use the HSM backend (via PKCS#11) for secure SOTA. Enable HSM support and make softhsm part of the base lmp images for testing purposes.
> Enable support for HSM via SoftHSMv2

- recipes-support/libp11/libp11_git.bb
- recipes-support/softhsm/softhsm_git.bb
Changes also proposed to meta-updater, available at https://github.com/advancedtelematic/meta-updater/pull/459.
> Update softhsm and libp11 to latest

- recipes-kernel/bluez-firmware-rpidistro/bluez-firmware-rpidistro_git.bbappend
Latest bluez-firmware release updates BCM4345C0.hcd to
003.001.025.0156.0280, restoring LE scan capability.
Upstream pull-request:
https://github.com/agherzan/meta-raspberrypi/pull/379
> bluez-firmware-rpidistro: update bluez-firmware

- recipes-samples/images/configs/ostree-pending-reboot.service
Aktualizr creates /var/run/aktualizr-session/need_reboot after applying
the update, so change the service file to use the upstream solution
instead.
> ostree-pending-reboot: change to use the upstream aktualizr flag file

- recipes-sota/lmp-device-register/lmp-device-register_git.bb
Bring in changes which allow PKCS#11-based provisioning using an HSM.
Signed-off-by: Marti Bolivar <marti@foundries.io>
> Update to newer version with HSM support

- recipes-sota/lmp-device-register/lmp-device-register_git.bb
Fix for non-HSM initialization.
> lmp-device-register: pull in regression fix

- recipes-devtools/gcc/files/riscv-Use-SYSTEMLIBS_DIR-replacement-instead-of-hardcoding.patch
- recipes-devtools/gcc/gcc-cross_8.3.bbappend
- recipes-devtools/gcc/gcc-runtime_8.3.bbappend
- recipes-devtools/gcc/gcc-source_8.3.bbappend
- recipes-devtools/gcc/gcc_8.3.bbappend
- recipes-devtools/gcc/libgcc-initial_8.3.bbappend
- recipes-devtools/gcc/libgcc_8.3.bbappend
Upstream dropped the riscv linker change with the gcc 8.3 update. Add it
back until the fix lands upstream again.
> gcc-8.3: add patch to change linker to use systemlibs dir on riscv

- classes/lmp-machine-custom.bbclass
- recipes-bsp/u-boot/u-boot-ostree-scr/qemuriscv64/boot.cmd
- recipes-bsp/u-boot/u-boot-ostree-scr/qemuriscv64/uEnv.txt.in
- recipes-devtools/riscv-tools/opensbi_%.bbappend
- recipes-devtools/riscv-tools/riscv-pk.bbappend
- recipes-kernel/linux/linux-lmp_git.bb
- recipes-samples/images/lmp-mini-image.bb
- kernel update to 5.0.6
- boot scripts to support u-boot for qemuriscv64
- remove riscv-pk append (bbl is dead)
- opensbi build fix
- lmp-mini-image add more room for OTA update
- lmp-machine move qemuriscv64 target to opensbi/u-boot support (with fitImage for Linux)
> meta-lmp: updates for kernel 5.0 and RISC-V

- recipes-core/initrdscripts/initramfs-framework/run-tmpfs.patch
Or else it leads to a patching QA warning as follows:
| Applying patch run-tmpfs.patch
| patching file finish
| patching file init
| Hunk #1 succeeded at 78 with fuzz 2 (offset 1 line).
> initramfs-framework: adjust patch to get rid of fuzz

- classes/lmp-machine-custom.bbclass
Due to commit bb370a5a ("opensbi: Fix the u-boot dependency") in
meta-riscv, we now need to use u-boot.bin as the OpenSBI payload or
the dependency won't trigger the u-boot build.
> lmp-machine-custom: qemuriscv64: fix OpenSBI u-boot dependency

- recipes-extended/procps/procps/sysctl.conf
- recipes-extended/procps/procps_%.bbappend
OE has a very outdated sysctl.conf file in the procps package:
https://git.openembedded.org/openembedded-core/commit/?id=8a9b9a323f4363e27138077e3e3dce8139a36708
(circa 2014)
The origins of this file is quite unknown and it's causing a routing
issue when both wifi and ethernet are enabled due to the following:
- upstream change in NetworkManager during 1.16 cycle removes the
dynamic rp_filter setting change when more than one interface
is enabled.
- legacy setting in sysctl.conf sets rp_filter to 1 which blocks
packets with different inbound and outbound addresses.
Documentation of rp_filter setting from kernel.org:
rp_filter - INTEGER
0 - No source validation.
1 - Strict mode as defined in RFC3704 Strict Reverse Path
Each incoming packet is tested against the FIB and if the interface
is …
> procps: add updated sysctl.conf to fix rp_filter issue

- recipes-bsp/u-boot/u-boot-lmp-common.inc
- recipes-bsp/u-boot/u-boot-tools_%.bbappend
- recipes-bsp/u-boot/u-boot_%.bbappend
To make sure our mkimage patches stay in sync with the u-boot patches
we need to apply them to both u-boot and u-boot-tools packages.
This way other layers can expect certain changes to be in place.
> recipes-bsp: u-boot: include same patches for u-boot-tools

- classes/lmp-machine-custom.bbclass
- recipes-bsp/u-boot/u-boot-ostree-scr/raspberrypi-cm3/uEnv.txt.in
Let's add missing Raspberry Pi 3 Compute Module support via the
raspberrypi-cm3 machine.
It is currently a copy of the raspberrypi3* settings (minus a few
overlays).
> lmp: add support for raspberrypi-cm3 machine

- classes/lmp-machine-custom.bbclass
Fixes warning in dmesg:
WARNING: Your 'console=ttyO0' has been replaced by 'ttyS0'
> lmp-machine-custom: beaglebone-yocto: use ttyS0 for console

- recipes-containers/docker-compose/python3-docker-compose/0001-support-requests-up-to-2.22.x-version.patch
- recipes-containers/docker-compose/python3-docker-compose_1.24.0.bb
The patch support-requests-up-to-2.21.0.patch is a pending pull request
but never merged, replace it with the merged one.
The original patch breaks the build with the latest meta-oe, in which
requests has been upgraded to 2.22.0.
> python3-docker-compose: replace a pending patch with the merged one

- recipes-support/lmp-auto-hostname/lmp-auto-hostname/lmp-auto-hostname.service.in
- recipes-support/lmp-auto-hostname/lmp-auto-hostname/lmp-update-hostname.sh
- recipes-support/lmp-auto-hostname/lmp-auto-hostname_0.1.bb
Recipe used to automatically update the target hostname based on device
specific configuration such as mac address and serial number.
Can be customized by the user via the following variables:
LMP_HOSTNAME_MACHINE -> fixed or empty for dt device model
LMP_HOSTNAME_MODE -> mac or serial
LMP_HOSTNAME_NETDEVICE -> interface used by mac mode
> lmp-auto-hostname: add recipe for automatic hostname configuration

- recipes-support/docker-auto-prune/docker-auto-prune/docker-auto-prune.service
- recipes-support/docker-auto-prune/docker-auto-prune/docker-auto-prune.timer.in
- recipes-support/docker-auto-prune/docker-auto-prune_0.1.bb
Systemd service and timer for automatically calling docker prune.
DOCKER_PRUNE_ONCALENDAR can be set as described at https://www.freedesktop.org/software/systemd/man/systemd.timer.html, default is daily. 
> docker-auto-prune: add recipe for auto docker prune timer

- recipes-samples/images/lmp-image-common.inc
- recipes-sota/aktualizr/aktualizr/0001-FIO-toup-aktualizr-lite-Mock-OstreeManager-getCurren.patch
- recipes-sota/aktualizr/aktualizr/0002-FIO-toup-aktualizr-lite-Save-installed-version-targe.patch
- recipes-sota/aktualizr/aktualizr/0003-FIO-toup-aktualizr-lite-Use-current-target-for-statu.patch
- recipes-sota/aktualizr/aktualizr/0004-FIO-toup-docker-apps-Add-support-for-getCurrent.patch
- recipes-sota/aktualizr/aktualizr/0005-FIO-toup-aktualizr-lite-Rename-version-to-helpers.patch
- recipes-sota/aktualizr/aktualizr/0006-config-Add-notion-of-tags-to-package-manager.patch
- recipes-sota/aktualizr/aktualizr/0007-aktualizr-lite-Include-ostree-hash-in-request-header.patch
- recipes-sota/aktualizr/aktualizr/0008-aktualizr-lite-Add-targets-equal-helper.patch
- recipes-sota/aktualizr/aktualizr/0009-aktualizr-lite-Add-a-daemon-mode.patch
- recipes-sota/aktualizr/aktualizr/0010-aktualizr-lite-Add-ability-to-reboot-after-an-update.patch
- recipes-sota/aktualizr/aktualizr/0011-aktualizr-lite-Add-lockfile-for-daemon-mode-updates.patch
- recipes-sota/aktualizr/aktualizr/0012-Create-new-aktualizr-get-command.patch
- recipes-sota/aktualizr/aktualizr/aktualizr-lite.service
- recipes-sota/aktualizr/aktualizr_%.bbappend
- recipes-sota/lmp-device-register/lmp-device-register_git.bb
- recipes-support/curl/curl_%.bbappend
Include the wip patches required for supporting aktualizr-lite and aktualizr-get.
Aktualizr-lite can be used by default by simply setting SOTA_CLIENT = "aktualizr-lite" in conf/local.conf.
> Support for aktualizr-lite/get

- recipes-sota/aktualizr/aktualizr/0013-aktualizr-lite-Fix-incorrect-storing-of-ecu-hwid.patch
- recipes-sota/aktualizr/aktualizr_%.bbappend
Upstream PR: https://github.com/advancedtelematic/aktualizr/pull/1298
> aktualizr: lite: fix incorrect storing of ecu hwid

- recipes-kernel/jool/jool_git.bb
- fixes for upcoming 5.3 kernel
> jool: update to v4.0.4 release

- classes/lmp-machine-custom.bbclass
- Don't set unknown SoCs OSTREE kernel args by default
- Add i.MX7ULP OSTREE kernel arg defaults
> lmp-machine-custom changes for i.MX7ULP

- classes/uboot-fitimage.bbclass
- recipes-bsp/u-boot/u-boot-ostree-scr-fit.bb
- recipes-bsp/u-boot/u-boot-ostree-scr-fit/boot.cmd
- recipes-bsp/u-boot/u-boot-ostree-scr-fit/boot.its.in
- recipes-bsp/u-boot/u-boot-ostree-scr-fit/cubox-i/boot.cmd
- recipes-kernel/linux/linux-lmp_git.bb
- recipes-samples/images/lmp-image-common.inc
- recipes-security/optee/optee-examples_git.bb
- recipes-security/optee/optee-os_git.bb
- recipes-security/optee/optee-sks_git.bb
- recipes-security/optee/optee-test_git.bb
- recipes-support/crucible/crucible/set-default-fusemaps-dir.patch
- recipes-support/crucible/crucible_git.bb
- wic/sdimage-imx6dq-spl-fit-sota.wks
* New WKS file compatible with SPL FIT (larger SPL)
* Ostree boot script in FIT format (in order to avoid u-boot legacy image support)
* New recipe: crucible (iMX fuse programming)
> Initial work for Apalis (imx6dq) secure boot

- recipes-sota/config/aktualizr-lite-public-stream.bb
- recipes-sota/config/files/10-lite-public-stream.toml.in
OTA_LITE_TAG is currently used by the CI promotion logic, so instead of
reusing that variable let's create one specific to the aktualizr-lite
client to avoid issues.
> aktualizr-lite-public-stream: rename tag variable to AKLITE_TAG

- recipes-bsp/u-boot/u-boot-ostree-scr/qemuriscv64/boot.cmd
- recipes-bsp/u-boot/u-boot-ostree-scr/qemuriscv64/uEnv.txt.in
Recent kernel commit in 5.3 changed page table setup which now
crushes the QEMU loaded DTB:
https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/arch/riscv/kernel?h=v5.3&id=671f9a3e2e24cdeb2d2856abee7422f093e23e29
Let's copy the DTB to the established load addr (fdt_addr_r) instead
where it's safe.
> u-boot: qemuriscv64: copy QEMU loaded DTB to safe area (fdt_addr_r)

- recipes-sota/aktualizr/aktualizr/aktualizr-lite.service
Not required anymore as it is now able to reuse the reboot_command
defined by aktualizr (which defaults to /sbin/reboot).
> aktualizr-lite: drop reboot-command from service file

- recipes-samples/images/lmp-feature-jobserv.inc
- recipes-samples/images/lmp-gateway-image.bb
- create lmp-feature-jobserv.inc which contains the jobserv dependencies
- add lmp-feature-jobserv.inc to lmp-gateway-image
> lmp-gateway-image: add jobserv python3 dependencies

- conf/distro/lmp-base.conf
The LmP base distro should be used when no ostree/aktualizr functionality
is needed by an image build.
Example of this would be for manufacturing tools, etc.
> conf/distro: introduce lmp-base distro configuration

- recipes-sota/lmp-device-register/lmp-device-register_git.bb
Also enable the new GIT_COMMIT and HARDWARE_ID build flags.
> lmp-device-register: bump rev to c8d9af9

- recipes-devtools/mcumgr/mcumgr_git.bb
Management library for 32-bit MCUs.
> mcumgr: add recipe

- recipes-samples/images/lmp-feature-debug.inc
To help with HW bringup and debugging let's add the following
tools to the debug feature:
- screen
- tmux
- minicom
- devmem2
> images/feature-debug: add more debug tools

- recipes-support/docker-credential-helper-fio/files/docker-credential-fio-helper
The credential helper can do more than just authenticate. It can
also do things like "store" credentials. This fixes our helper so
that its only run for "get" calls.
> docker-credential-helper: Only run for "get" calls

- recipes-sota/lmp-device-register/lmp-device-register_git.bb
This pulls in the change that always enables the docker-app pakage
manager
> lmp-device-register: Bump to latest version

- recipes-samples/images/lmp-feature-factory.inc
hub.foundries.io docker cli configuration is required for factory users.
> lmp-feature-factory: add docker-cli-config

- recipes-sota/aktualizr/aktualizr_%.bbappend
lshw is used by both aktualizr and aktualizr-lite.
> aktualizr: also add lshw as rdepends of aklite

- recipes-sota/aktualizr/aktualizr_%.bbappend
- eb5e8b5b [fio extras] Use uptane.polling_sec for interval configuration
> aktualizr: bump for uptane.polling_sec support

- recipes-sota/aktualizr/aktualizr_%.bbappend
Pull in fix where we were accidentally trying to report network
information when no TLS server was configured:
https://github.com/foundriesio/aktualizr/commit/5a985d3723531aeae2929a486254052359c808c9
> recipes-sota: Bump version of aktualizr

- recipes-devtools/python/python3-docker/0001-config-Include-usr-lib-docker-in-search-path.patch
- recipes-devtools/python/python3-docker_3.7.3.bb
Our credential helper configuration for the LMP is stored under
/usr/lib/docker/config.json. This adds the path to the docker API
so that docker-compose can use this helper.
> python3-docker: Add support for our credential helper

- recipes-bsp/u-boot/u-boot-fio_git.bb
e47d650 [FIO extras] mx7ulpea-ucom-mfgtool_defconfig: add ext4load support
b89ecaa [FIO extras] imx7ulpea: dts: enable DM QSPI flash
88abee6 [FIO extras] sf: Add Macronix MX25U3235F SPI flash
> u-boot-fio: bump srcrev for udpates to mx7ulpea-ucom

- recipes-devtools/mcumgr/mcumgr_git.bb
- 62a8136 Update to latest newt/newtmgr deps
NOTE: Hand compile testing shows this new version fixes a
crash while updating the firmware on nRF52840-DK from a host
i.MX 7ULP device.
> mcumgr: bump rev for latest newt/newtmgr deps

- recipes-devtools/mcumgr/mcumgr_git.bb
The default do_compile() for OE is creating an oddly broken mcumgr
binary.  When attempting to upload a new firmware image, mcumgr will
reach 12.9% and then hang for a few seconds before crashing.
First attempts to fix this issue did not work when setting the
following to avoid stripping the end binary:
INHIBIT_PACKAGE_STRIP = "0"
My manual build step looks something like this:
GOOS=linux GOARM=7 GOARCH=arm go build mcumgr.go
Adjusting the mcumgr recipe to mimic my local build steps fixes the
issue.
NOTE: The resulting binary is quite large (~15mb) compared to the
default build which is 1/2 the size.
> recipes-devtools: mcumgr: fix binary build

- recipes-sota/aktualizr/aktualizr_%.bbappend
aktualizr should RDEPENDS on docker-app if 'dockerapp' packageconfig is
enabled, and 'dockerapp' should be a target related config option, make
it behave so.
> aktualizr: RDEPENDS on docker-app

- recipes-connectivity/modemmanager/modemmanager_1.10.8.bb
Use newer ModemManager to address "denied" registration issue fixed in
commit:
https://cgit.freedesktop.org/ModemManager/ModemManager/commit/?h=1.10.8&id=47fd8a1e55cac0b0b45812e1dda826f38c264d1b
NOTE: Will revert when upstream merges 1.10.8.
> modemmanager: Upgrade 1.10.6 -> 1.10.8

- recipes-sota/ostree/ostree/0001-Makefile-declare-ostree_boot_SCRIPTS-and-append-valu.patch
- recipes-sota/ostree/ostree_%.bbappend
> ostree: add patch to fix missing ostree-grub-generator

- recipes-security/optee/optee-os/0001-Minimal-HUK-implementation-without-full-CAAM-driver.patch
If the CAAM job times-out report an error instead of failing silently
> optee-os: imx: report error on timeout

- recipes-bsp/u-boot/u-boot-fio_git.bb
fe1cffb [FIO ext] configs: mx7ulpea-mfgtool-ucom: enable IMX_FPGA
06d3735 [FIO ext] configs: mx7ulpea-ucom: enable IMX_FPGA
3c4d5c7 [FIO toup] fpga: imx_m4: boot M4
a5ff21e [FIO internal] common: foundries.io verified boot utility
3115e18 [FIO toup] drivers: rpmb: use cache aligned buffers on route commands
daf7fa2 [FIO toup] drivers: rpmb: replicate linux mmc configuration
9737e86 [FIO toup] drivers: optee: rpmb: fix returning CID to TEE
bc56664 [FIO toup] mmc: fsl_esdhc_imx: initialize data for imx7ulp
> u-boot-fio: bump srcrev for updates to mx7ulpea-ucom / M4 verified boot

- recipes-kernel/linux/linux-lmp_git.bb
- recipes-security/optee/optee-os/0001-imx-caam-check-if-otpmk-can-be-used-when-producing-h.patch
- recipes-security/optee/optee-os_git.bb
- recipes-sota/aktualizr/aktualizr_%.bbappend
- recipes-support/crucible/crucible_git.bb
* linux-lmp kernel stable update
* crucible minor upstream update
* enable cfg werror on optee-os
* update aktualizr to our latest branch revision
* change optee-os to validate otpmk when generating huk
> Initial meta-lmp updates for 57

- recipes-security/optee/optee-fiovb_git.bb
Add the fiovb host binary to the rootfs. 
This binary interfaces to the fiovb TA to read and write persistent values for RPMB and control the rollback counters.
- Notice that rollback counters MUST be specified in hex 
- Also notice that to use the current fiovb binary you need to use symbolic links named fw_printenv and fw_setenv. 
Perhaps we should change that so the application just checks for "fw_print" and "fw_set" strings when routing so the links could be more specific.
> optee-os: added Foundries.IO Verified Boot recipe

- recipes-security/optee/optee-fiovb_git.bb
Use fiovb_printenv and fiovb_setenv to access the secure functionality (just as fw_printenv and fw_sentenv).
This PR also creates the necessary symlinks during the install phase
requires actualzr update.
> fiovb host

- recipes-security/optee/optee-os/0001-Foundries.IO-Verified-Boot-Trusted-Application.patch
restrict the list of access values to m4hash, bootcount and rollback
> optee-os: ta: foundries io trusted app: remove rollback_counter logic

- meta-lmp-base/recipes-devtools/python/python3-docker_%.bbappend
We need ensure python3-docker directory is in FILESEXTRAPATHS, or else
the LMP patch could not be found in do_fetch.
> python3-docker: fix a fetch issue

- meta-lmp-base/recipes-security/optee/optee-os/0001-config-overlay-reserved-memory-size-addr-cells.patch
- meta-lmp-base/recipes-security/optee/optee-os_git.bb
the reserve-memory node addr/size cell properties is now a
configuration option. This is required when we are generating a new
overlay tree instead of appending to one.
> meta-lmp-base: optee: config options for overlay generation

- meta-lmp-base/recipes-security/optee/optee-os/0001-imx7ulp-drivers-watchdog-fix-timing-issue.patch
- meta-lmp-base/recipes-security/optee/optee-os_git.bb
Rhe imx7ulp watchdog has very stringent timing requirements for its
reconfiguration (128 bus cycles after unlock).
Do our best to comply with that requirement.
> meta-lmp-base: optee-os: imx7ulp: fix watchdog

- meta-lmp-base/recipes-security/optee/optee-os/0001-imx7ulp-drivers-watchdog-fix-timing-issue.patch
During the previous patch preparation we incorrectly wrote to BIT(6) -
interrupt status flag - instead of BIT(5) (enable support for 32bit
timers)
Upon stress testing this was causing that "sometimes" reset requests
would act inmediately instead of via countdown (perhaps due to a
violation in writing to this register).
This commit fixes the situation generated by our previous commit.
> meta-lmp-base: optee-os: imx7ulp: fix incorrect register setting

- meta-lmp-base/recipes-sota/aktualizr/aktualizr_%.bbappend
Using SOTA_CLIENT_FEATURES to store the fiovb feature now causes an
error due to sanity checks performed by the meta-updater layer.
Let's move the feature addition to SOTA_EXTRA_CLIENT_FEATURES.
> meta-lmp-base: aktualizr: move fiovb var to SOTA_EXTRA_CLIENT_FEATURES

- meta-lmp-base/recipes-bsp/u-boot/u-boot-fio-common.inc
- 4d70ca7f [FIO extras] imx: imx7ulpea-ucom-kit_v2: add sys_reset config
- 7d1d7fbf [FIO extra] imx: mx7ulpea-ucom: system reset function
- ecf74c43 [FIO toup] fpga: imx_m4: handle dual_boot (M4/A7 running)
> meta-lmp-base: u-boot: bump u-boot sha

- meta-lmp-base/recipes-support/mfgtool-files/mfgtool-files/full_image.uuu.in
- Due to artifact renaming the full_tar scripts need the image filename
updated from *.img.gz -> *.wic.gz
> base: recipes-support: mfgtools: udpate *.img.gz to *.wic.gz

- meta-lmp-base/recipes-sota/aktualizr/aktualizr/aktualizr-lite.path
- meta-lmp-base/recipes-sota/aktualizr/aktualizr/aktualizr-lite.service
- meta-lmp-base/recipes-sota/aktualizr/aktualizr_%.bbappend
- add path check to avoid starting aktualizr-lite when mbed-cloud-client is present
- add aktualite-lite.path service to restart aktualizr-lite service once lmp-device-register has run
> add path service to restart aktualizr-lite service

- meta-lmp-base/recipes-sota/aktualizr/aktualizr/aktualizr-lite.path
Systemd is complaining about dependency for target network when
starting monitoring path service for aktualizr-lite.  The reality
is we don't need to have a target for the monitoring service as
the paths it's watching won't be changed until much later in the
boot.  By that time we have the basic network stack available.
Fix by removing: After=network.target
> base: recipes-sota: aktualizr: bugfix path monitoring service

- meta-lmp-base/recipes-bsp/u-boot/libubootenv_%.bbappend
libubootenv-bin is the RPROVIDER of u-boot-fw-utils, so the
${sysconfdir}/fw_env.config should be in that package instead of being
put in libubootenv package as it is right now.
And ${sysconfdir}/fw_env.config is a machine specific file, so if we
want bundle it to libubootenv recipe, then libubootenv itself should be
a machine package rather than a arch package.
> libubootenv: fix some packaging issues

- meta-lmp-base/recipes-kernel/linux/linux-lmp-dev.bb
Not doing so  makes pulling a kernel from a local filesystem (for
private builds) impossible.
> lmp-base: kernel: do not restrict kernel pull to https

- meta-lmp-bsp/recipes-support/mfgtool-files/mfgtool-files_%.bbappend
imx-boot is a generic dependency for mx8-based targets, so change the
extra machine dependencies to be soc-based and not machine, in order to
cover a wider range of targets.
> bsp: mfgtool-files: change extra depends to soc level

- meta-lmp-base/recipes-sota/aktualizr/aktualizr/aktualizr-lite.path
- Don't worry about starting aktualizr-lite based on public sota config.
this config will always be in place for public builds and never be there
for private builds.  No need for a path watcher.
> base: recipes-sota: aktualizr: remove public sota config as a trigger

- meta-lmp-base/recipes-sota/aktualizr/aktualizr/aktualizr-lite.path
- Link the path monitor to the aktualizr-lite service when it's enabled
by checking for the presence of:
/etc/systemd/system/multi-user.target.wants/aktualizr-lite.service
> base: recipes-sota: aklite.path: depend on aklite.service

- meta-lmp-base/recipes-containers/docker/docker-ce/daemon.json
swap from json-file log driver to journald:
- easier to manage consistent log storage settings across the whole
platform
- possible I/O improvements when reading logs
> base: recipes-containers: docker-ce: use journald log driver

- meta-lmp-base/recipes-support/ostree-pending-reboot/ostree-pending-reboot/ostree-pending-reboot.service
A flaw was observed that sometimes the reboot procedure after updating
is very slow with the message showing on console:
```
[  523.527840] systemd-shutdown[1]: Waiting for process: rngd
```
this is caused by "systemctl --force reboot" being used in
ostree-pending-reboot.service, changing to a regular /sbin/reboot would
be much faster.
> ostree: use /usr/sbin/reboot to reboot the system

- meta-lmp-base/recipes-devtools/mcumgr/mcumgr_git.bb
- any new build of mcumgr errors out due to read-only directories
created during the build
- add a manual step to reset these directories to user write so
they can be deleted
> base: mcumgr: fix build dir permissions

- meta-lmp-base/recipes-samples/images/lmp-feature-factory.inc
- meta-lmp-base/recipes-support/fioconfig/fioconfig/fioconfig-extract.service
- meta-lmp-base/recipes-support/fioconfig/fioconfig/fioconfig.service
- meta-lmp-base/recipes-support/fioconfig/fioconfig_git.bb
> Add fioconfig daemon

- meta-lmp-base/recipes-sota/aktualizr/aktualizr_%.bbappend
NOTE: This includes a SHA update of aktualizr
aktualizr-lite related changes:
- 647e2936 aktualizr: Bump version
- 19bf79a9 add gitignore and README
- 5bf612e0 Merge pull request #3 from doanac/unit-test-fixes
- 72091d86 Fix broken integration test
- c8c8755d Fix tests for latest aktualizr
aktualizr related changes:
- 852f43be [fio extras] bootloader: add support to fio verified boot
> base: recipes-sota: aktualizr: move to master branch

- meta-lmp-base/recipes-support/fioconfig/fioconfig/fioconfig.path
- meta-lmp-base/recipes-support/fioconfig/fioconfig/fioconfig.service
- meta-lmp-base/recipes-support/fioconfig/fioconfig_git.bb
ficonfig has been updated to include an aktualizr-toml-update
helper script.  By using fioctl devices config updates command,
we can now easily set the docker-apps and tags settings for
aktualizr-lite.
> base: recipes-support: fioconfig: add toml helper support

- meta-lmp-base/recipes-security/optee/optee-os_git.bb
Relevent commits:
- 300a9d78 [FIO internal] caam: provide alternative HUK via CFG
- 10dfccc6 [FIO internal] caam: imx7ulp: RPMB workaround for closed boards
> base: optee_os: updates for imx7ulp and alt HUK cfg

- meta-lmp-base/recipes-sota/lmp-device-register/lmp-device-register_git.bb
This version includes the ability to set a default tag for the device to
subscribe for updates on.
> lmp-device-register: Pull in latest version

- meta-lmp-base/conf/distro/include/lmp.inc
- meta-lmp-base/conf/distro/lmp-base.conf
- meta-lmp-base/conf/distro/lmp-mfgtool.conf
- meta-lmp-base/conf/distro/lmp.conf
* Remove support for nfs (nfs client, not used/required by us)
* Manually added a default set for distro features based on was already available by OE. This will allow our user to add features that were previously removed via "_remove", such as x11 and wayland.
> Improve default features settings in LMP

- meta-lmp-base/recipes-sota/lmp-device-register/lmp-device-register_git.bb
- 5acb69e Remove dependency on ostree
- 464218b Make the former '-s' option hidden
- 9979b15 Add ability to specify a factory via an env var
- bf32ca1 Replace the 'stream' option with 'factory' one
- 74189cf Fix DEVICE_API default value
> lmp-device-register: bump to the latest git rev

- meta-lmp-base/classes/kernel-lmp-fitimage.bbclass
Generate a default fit configuration even when no dtb is provided by the
kernel/board, as it gets used to verify all the other components (hash
and signature).
> base: kernel-lmp-fitimage: generate config even without dtb

- meta-lmp-bsp/conf/machine/include/lmp-machine-custom.inc
- meta-lmp-bsp/recipes-bsp/u-boot/u-boot-fio/qemuarm/fw_env.config
- meta-lmp-bsp/recipes-bsp/u-boot/u-boot-fio/qemuarm/lmp.cfg
- meta-lmp-bsp/recipes-bsp/u-boot/u-boot-ostree-scr-fit/qemuarm/boot.cmd
- meta-lmp-bsp/recipes-core/base-files/base-files/qemuarm/fstab
- Enable basic build options for qemuarm machine
- U-boot recipe is the standard u-boot-fio
- Kernel recipe is the standard linux-lmp
- Enable support for fitImage with boot.itb script support
> bsp: machine: add support for qemuarm

- meta-lmp-base/recipes-sota/lmp-device-register/lmp-device-register_git.bb
It should go with https://github.com/foundriesio/lmp-device-register/pull/17/files
I'll remove the 'branch' once the lmp-device-register is merged.
> base: lmp-device-register: support compose app

- meta-lmp-base/recipes-core/initrdscripts/initramfs-framework_%.bbappend
It does not need a extra explicit _sota overrides since other files in
SRC_URI are all sota specific any way.
Without this change, the run-tmpfs.patch would always be the last patch
in SRC_URI, which could lead to 'patch fuzz' QA warnings for the meta
layers that relying on it.
Signed-off-by: Ming Liu <ming.liu@toradex.com>
> initramfs-framework: drop a sota overrides

- meta-lmp-base/recipes-support/mfgtool-files/mfgtool-files_0.1.bb
Related changes:
- Drop custom Foundries release in favor of upstream:
https://github.com/NXPmicro/mfgtools
- Drop static Windows binary not supported by upstream
> recipes-support: mfgtool-files: udpate uuu to 1.3.154 release

- meta-lmp-base/recipes-core/images/initramfs-ostree-lmp-image.bb
- meta-lmp-base/recipes-core/initrdscripts/initramfs-framework/rootfs
This is basically 2 minor changes:
* Add e2fsck to the initrd (increases ~0.5mb)
* Run e2fsck before mounting the rootfs
Systemd also provides a job for running fsck on the rootfs, but e2fsck doesn't work correctly on mounted filesystems, which is why it is better and safer to just run at the initrd level instead.
> Add support for running e2fsck at the initrd

- meta-lmp-base/recipes-security/optee/optee-os_git.bb
NXP SE050 HUK / UUID issue
- 02ffafff [FIO toup] libnxpse050: core: huk
> base: optee-os: bump revision to 02ffaff

- meta-lmp-base/recipes-samples/images/lmp-image-common.inc
As a part of the LmP common image changes, we run a resize-helper which
expands the rootfs to fill the available space.  This usually takes care
of needing enough space on the rootfs to download a complete OTA image.
(about double the size at a minimum)
QEMU target images are not expanded past their original size during this
process and so we increased the overhead factor for all targets to 2.3.
This has 2 downsides:
1. Subscribers have a hard time overriding this setting
2. non-QEMU target wic images are needlessly larger than they should be
due to the resize-helper.
By selectively setting an overridable value of 2.3 for QEMU targets,
we solve both of these issues.
> base: lmp-image-common: only increase overhead factor for QEMU targets

- meta-lmp-base/recipes-kernel/linux/linux-lmp_git.bb
- meta-lmp-bsp/conf/machine/include/lmp-machine-custom.inc
- default linux-lmp recipe bump for 5.4 branch
- rpi commit bump for 4.19 branch
- imx8mm commit bump for 5.4 branch
Relevant commits for 4.19 branch:
- 1e97ab77 BSP: Add fragments for qemuarm64
Relevant commits for 5.4 branch:
- c348b707 bsp: imx8mmevk: fix imx8mm thermal driver error in dmesg
> linux: update KERNEL_META_COMMIT for 4.19 and 5.4 branches

- meta-lmp-base/classes/lmp.bbclass
Preload compose app images into the target rootfs (var/lib/docker) if DOCKER_COMPOSE_APP_PRELOAD is set to "1" provided that the images were dumped before during container build for the corresponding Target.
depends on https://github.com/foundriesio/ci-scripts/pull/71
> base: lmp.bbclass: app images preload

- meta-lmp-base/recipes-sota/aktualizr/aktualizr_%.bbappend
! depends on meta-updater 35240e670e811d149d4765e4a6a8fceae7d642df
- switch to 2020.7+fio
- adjust aktualizr-lite to aktualizr 2020.7
- changes in PackageManagerInterface::fetchTarget signature
- added symlink to clang-tidy-wrapper.sh
> Switch aklite to aktualizr 2020.7

- meta-lmp-base/recipes-sota/lmp-device-register/lmp-device-register_git.bb
Use a scoped token for a device registration call
> base: lmp-device-register: bump rev to 633b11b

- meta-lmp-base/classes/kernel-lmp-fitimage.bbclass
Extend this class to handle FIT_LOADABLES as a list of deployed files
to be added to the kernel fitimage.  This allows subscribers to
retreive these files in u-boot where the contents are verified prior
to using.
Example would be to add the following line to machine.conf:
FIT_LOADABLES = "core0_m4_image.bin core1_m4_image.bin"
- A recipe would place those files in ${DEPLOYDIR} in do_deploy
- Then an additional do_compile[depends] is added to the kernel
recipe such as:
do_compile[depends] += "<recipe>:do_deploy"
> base: kernel-lmp-fitimage: add support for FIT_LOADABLES

- meta-lmp-base/recipes-samples/images/lmp-feature-docker.inc
- meta-lmp-base/recipes-support/docker-image-preload/docker-image-preload/docker-image-preload.service
- meta-lmp-base/recipes-support/docker-image-preload/docker-image-preload_0.1.bb
Systemd service that extracts container images from a tarball into /var/lib/docker so they become 'preloaded'
before running dockerd service.
The tarball is generated and injected into a system image/rootfs (WIC) either by lmp or [container build](https://ci.foundries.io/projects/msul-dev01/lmp/builds/306/assemble-system-image/) or by fioctl (TBD).
This should go with https://github.com/foundriesio/ci-scripts/pull/73 and https://git.foundries.io/development/cloudplatforms/infrastructure/repoz/merge_requests/15
> base: docker-ce: Untar images before running docker

- meta-lmp-base/conf/distro/lmp-mfgtool.conf
Use lmp-mfgtool-factory-custom.inc as a way of including factory
customizations to lmp-mfgtool builds.
NOTE: We have a similar file: lmp-factory-custom.inc being used
for lmp builds.
> conf: distro: lmp-mfgtool: allow factory customization

- meta-lmp-base/recipes-kernel/linux/linux-lmp-lts_git.bb
- meta-lmp-base/recipes-kernel/linux/linux-lmp_git.bb
- meta-lmp-base/recipes-kernel/wireguard/wireguard-module_1.0.20200712.bb
- meta-lmp-base/recipes-kernel/wireguard/wireguard-tools_1.0.20200513.bb
Tested 5.8.1 kernel on qemuarm64, intel-corei7-64, beaglebone-yocto, qemuriscv64, freedom-u540, qemuarm and apalis-imx6.
Kernel meta was also updated with the latest config related changes.
> Adding linux-lmp-lts and bumping linux-lmp to 5.8.1

- meta-lmp-base/recipes-bsp/u-boot/u-boot-fio-common.inc
- meta-lmp-base/recipes-bsp/u-boot/u-boot-fio-imx_2020.04.bb
- meta-lmp-base/recipes-bsp/u-boot/u-boot-fio-mfgtool.bb
- meta-lmp-base/recipes-bsp/u-boot/u-boot-fio_2019.10.bb
- meta-lmp-base/recipes-bsp/u-boot/u-boot-fio_2020.04.bb
- meta-lmp-bsp/recipes-bsp/u-boot/u-boot-fio-imx_%.bbappend
Not enabled by default yet, but recipes useful for early development.
> Adding initial u-boot-fio/u-boot-fio-imx recipes based on 2020.04

- meta-lmp-base/recipes-sota/aktualizr/aktualizr_%.bbappend
- switch to 2020.8+fio
- Fix sorting of the "list" subcommand
- compose-apps: Keep trying to update apps
> base: aktualizr-lite: bump to edc0f77

- meta-lmp-bsp/recipes-bsp/u-boot/u-boot-ostree-scr/imx6ullevk/boot.cmd
- meta-lmp-bsp/recipes-bsp/u-boot/u-boot-ostree-scr/imx6ullevk/uEnv.txt.in
imx6ullevk now uses the u-boot-ostree-scr-fit recipe
> bsp: u-boot-ostree-src: remove unused imx6ullevk settings

- meta-lmp-base/recipes-sota/aktualizr/aktualizr_%.bbappend
- docker-apps: Turn off the docker app pack manager
> base: aktualizr-lite: bump to 34f8f70

- meta-lmp-base/classes/kernel-lmp-fitimage.bbclass
When we use variable "i" to count iteratation through DTBS in
fitimage_assemble.  However, during each loop, we also call
fitimage_emit_section_config which also uses a variable "i" to
count loops when processing LOADABLES.  This causes the value
of "i" in the fitimage_assemble loop to seemingly stay the same
or randomly change in odd ways.
Let's fix the fitimage_assemble iteration count by renaming the
variable to "n" which is not used elsewhere.
> base: classes: kernel-fit-image: fix DTB iteration variable

- meta-lmp-base/recipes-sota/aktualizr/aktualizr_%.bbappend
- Install all Target Apps if compose_apps is not specified
> base: aktualizr-lite: bump to 62142af

- meta-lmp-base/recipes-support/mfgtool-files/mfgtool-files/full_image.uuu.in
- meta-lmp-base/recipes-support/mfgtool-files/mfgtool-files_0.1.bb
- meta-lmp-bsp/recipes-support/mfgtool-files/mfgtool-files/apalis-imx6/full_image.uuu.in
- meta-lmp-bsp/recipes-support/mfgtool-files/mfgtool-files/apalis-imx8/full_image.uuu.in
- meta-lmp-bsp/recipes-support/mfgtool-files/mfgtool-files/imx6ullevk/full_image.uuu.in
- meta-lmp-bsp/recipes-support/mfgtool-files/mfgtool-files/imx7ulpea-ucom/full_image.uuu.in
- meta-lmp-bsp/recipes-support/mfgtool-files/mfgtool-files/imx8mmevk/full_image.uuu.in
- meta-lmp-bsp/recipes-support/mfgtool-files/mfgtool-files/imx8mqevk/full_image.uuu.in
Let's add an OE var: MFGTOOL_FLASH_IMAGE to be used by the flash scripts for
building the .wic filename.
Default to: lmp-base-console-image
> recipes-support: mfgtool-files: allow full_image flash filename override

- meta-lmp-base/recipes-support/docker-credential-helper-fio/files/docker-credential-fio-helper
This allows the script to use the configured tls.server to grab
credentials from. This will become important when customers have their
own device gateway urls.
> docker-credential-helper: Support variable server names

- meta-lmp-base/classes/lmp.bbclass
Just a really tiny cleanup.
Corresponding changes to ci-scripts has been made https://github.com/foundriesio/ci-scripts/commit/7b7c8fcfc464acd4485f0da5c4de5101bce7a667
> base: preload: remove useless 'arch' param

- meta-lmp-base/recipes-security/optee/optee-os-fio_3.10.0.bb
896b1208 [FIO toup] conf: plat-imx:Add support for i2c for the imx8mqevk
Signed-off-by: David Griego <david.griego@foundries.io>
> base: optee-os-fio: 3.10: bump to 896b1208

- meta-lmp-bsp/conf/machine/include/lmp-mfgtool-machine-custom.inc
> bsp: lmp-mfgtool-machine-custom: fix UBOOT_SIGN_ENABLE for mx8mq

- meta-lmp-base/classes/uboot-fitimage.bbclass
SPL will then be able to string match properly during
board_fit_config_name_match (CONFIG_SPL_LOAD_FIT)
> u-boot-fitImage: pass the machine name in the SPL fit

- meta-lmp-base/recipes-sota/aktualizr/aktualizr_%.bbappend
- 0526fd5 aktualizr: switch to 2020.10+fio
> base: aktualizr-lite: bump to 0526fd5

- meta-lmp-base/recipes-support/fioconfig/fioconfig/fioconfig.service
fioconfig runs in a default interval of 300 seconds. This change will allow interval modifications by changing the environment file.
> base: fioconfig: Add environment file to configure interval

- meta-lmp-base/recipes-sota/aktualizr/aktualizr_%.bbappend
- 3c2aa5b garage-sign: download from FIO's storage
> base: aktualizr-lite: bump to 3c2aa5b

- meta-lmp-base/recipes-sota/lmp-device-register/lmp-device-register_git.bb
New version allows DEVICE_API to be overridden via an environment
variable.
> lmp-device-register: Bump version

- meta-lmp-bsp/recipes-kernel/linux/linux-lmp-fslc-imx/0001-FIO-fromtree-ath10k-add-QCA9377-sdio-hw_param-item.patch
- meta-lmp-bsp/recipes-kernel/linux/linux-lmp-fslc-imx_git.bb
This patch from mainline adds support for the QCA9377 chip via
ath10k sdio driver.
This chip is present on i.MX8MM EVK.
> bsp: linux-lmp-fslc-imx: patch fix for QCA9377 SDIO hw params

- meta-lmp-base/recipes-bsp/u-boot/u-boot-fio_2020.04.bb
- meta-lmp-base/recipes-security/optee/optee-os-fio_3.6.0.bb
- base: u-boot-fio: 2020.04: bump to f5ef084e7cb
- base: optee-os-fio: 3.6: bump to c67d7defe31
> Bump u-boot 2020.04 and optee-os 3.6 SHAs

- meta-lmp-bsp/recipes-bsp/u-boot/u-boot-fio/imx8mmevk/lmp.cfg
Disable SPL_DM_MMC and SPL_BLK, that fixes SD boot issues.
> bsp: u-boot-fio: imx8mmevk: lmp.cfg: disable SPL_DM_MMC and SPL_BLK

- meta-lmp-base/recipes-security/optee/optee-os-fio_3.12.0.bb
- meta-lmp-bsp/recipes-security/optee/optee-os-fio-mfgtool_3.12.0.bbappend
```
Switch optee-os-fio/optee-client/optee-test to 3.12 version.
```
> optee: switch to 3.12 version

- meta-lmp-base/recipes-bsp/u-boot/u-boot-fio_2020.04.bb
- dbb9acc4eb [FIO internal] ARM: imx8mq: add define for PERSIST_SECONDARY_BOOT bit
> base: u-boot-fio: 2020.04: bump to dbb9acc4eb

- meta-lmp-base/recipes-kernel/wireguard/wireguard-module_%.bbappend
Currently, only linux-lmp and linux-lmp-rt (both 5.10.y atm) opt out of
building the external wireguard module which applies to kernels < 5.6.y.
Let's provide a way for edge case kernels to also opt-out of the module:
KERNEL_BUILTIN_WIREGUARD = "1"
> bsp: recipes-kernel: wireguard: add option to opt-out of ext module

- meta-lmp-base/recipes-kernel/linux/kmeta-linux-lmp-5.4.y.inc
- meta-lmp-bsp/conf/machine/include/lmp-machine-custom.inc
- meta-lmp-bsp/recipes-bsp/u-boot/u-boot-ostree-scr/am64xx-sk/boot.cmd
- meta-lmp-bsp/recipes-bsp/u-boot/u-boot-ostree-scr/am64xx-sk/uEnv.txt.in
- meta-lmp-bsp/recipes-bsp/u-boot/u-boot-ti-staging/am64xx-sk/0001-am64xx-sk-set-bootm-len-to-64.patch
- meta-lmp-bsp/recipes-bsp/u-boot/u-boot-ti-staging_%.bbappend
- meta-lmp-bsp/recipes-kernel/linux/linux-lmp-ti-staging_git.bb
This is the initial port of TI am64xx-sk board with ostree support
TODO: integrate with uboot-fitimage.bbclass
> Ti am64xx sk support

- meta-lmp-base/recipes-sota/aktualizr/aktualizr_%.bbappend
- 9010446 apps: make finding of auth endpoint prefix agnostic
- 24e7e2e aklite: reuse the existing installation finalization
> base: aktualizr-lite: bump to 9010446

- meta-lmp-base/recipes-sota/lmp-device-register/lmp-device-register_git.bb
- bc56368f Add support for production build and env parameter
- Add production option to lmp-device-register packageconfig
Signed-off-by: Volodymyr Khoroz <volodymyr.khoroz@foundries.io>
> base: lmp-device-register: bump to bc56368f

- meta-lmp-base/recipes-sota/aktualizr/aktualizr_%.bbappend
- 699d6af fixup!: add x-ats-target header at http client instantiation
- b17d48d apps: introduce App Engine interface
- a0e804d test: app engine mock and basic app update tests
> base: aktualizr-lite: bump to 699d6af

- meta-lmp-bsp/recipes-support/mfgtool-files/mfgtool-files/imx6ullevk/bootloader.uuu.in
- meta-lmp-bsp/recipes-support/mfgtool-files/mfgtool-files/imx6ullevk/full_image.uuu.in
There is no eMMC device available by default on imx6ullevk, so taking
into account the partition layout and correct offset when erasing the
bootloader area.
> bsp: mfgtool-files: imx6ullevk: fix erase offset

- meta-lmp-base/recipes-sota/aktualizr/aktualizr_%.bbappend
- dcfc946 apps: send app list in a header unconditionally
- 957b30a aktualizr: update 2021.1+fio (fix the error message `import
path`)
> base: aktualizr-lite: bump to dcfc946

- meta-lmp-bsp/dynamic-layers/freescale-layer/recipes-fsl/images/fsl-image-mfgtool-initramfs.bbappend
With fitimage support there is no need to generate packages for
initramfs, which can confuse the package metadata generation for
dependencies such as imx-boot.
> bsp: fsl-image-mfgtool-initramfs: inherit nopackages

- meta-lmp-bsp/dynamic-layers/stm-st-stm32mp/recipes-support/flashlayouts-stm32mp1/flashlayouts-stm32mp1.bb
When the stm32mp was added to lmp the deploy was not correct.
> meta-lmp-bsp: dynamic: flashlayout fix bug in deploy script

- meta-lmp-base/recipes-devtools/go/go-riscv-1.15.inc
These patches seem to be causing a regression when applied for all
arches.  Let's limit them to only riscv64.
> base: go: limit RISC-V cgo/pie support patches to riscv64

- meta-lmp-base/recipes-sota/aktualizr/aktualizr_%.bbappend
- fe447e0 fixup! get currently installed apps correctly
> base: aktualizr-lite: bump to fe447e0

- meta-lmp-base/recipes-security/optee/optee-os-fio_3.10.0.bb
- meta-lmp-base/recipes-security/optee/optee-os-fio_3.12.0.bb
- meta-lmp-bsp/recipes-kernel/linux/linux-lmp-dev-mfgtool.bbappend
- meta-lmp-bsp/recipes-kernel/linux/linux-lmp-dev-mfgtool/apalis-imx6/0001-MLK-16912-PL310-unlock-ways-during-initialization.patch
- meta-lmp-bsp/recipes-kernel/linux/linux-lmp/apalis-imx6/0001-MLK-16912-PL310-unlock-ways-during-initialization.patch
- meta-lmp-bsp/recipes-kernel/linux/linux-lmp_git.bbappend
- Linux patches to fix Linux init of PL310 caches.
- Bump optee-os SHAs to include PL310 tuning changes
These changes fix performance issues for imx6qdl HW when running OP-TEE.
> apalis-imx6 pl310 fix

- meta-lmp-base/recipes-core/initrdscripts/initramfs-framework/run-tmpfs.patch
In run-tmpfs.patch, we had changed /run to be a tmpfs mountpoint, and
/var/lock is a symbolic link to ../run/lock, so we shall move the
'mkdir' after /run created, or else we get a error as follows:
| mkdir: can't create directory '/var/lock': No such file or directory
> initramfs-framework: create /var/lock later

- meta-lmp-base/recipes-support/compose-apps-early-start/compose-apps-early-start.bb
- meta-lmp-base/recipes-support/compose-apps-early-start/compose-apps-early-start/compose-apps-early-start
- meta-lmp-base/recipes-support/compose-apps-early-start/compose-apps-early-start/compose-apps-early-start.service
Its often desirable to start compose-apps (containers) before a device
is registered and aklite is running. This recipe creates a one shot
service that will start apps if aklite is not yet setup.
> Add apps-early-start recipe

- meta-lmp-bsp/conf/machine/uz3eg-iocc.conf
soc-zynqmp.inc uses cortexa72-cortexa53 as default tune for zynqmp
devices, but uz3eg-iocc only has a53 cores, so define the correct tune
at board level.
> bsp: uz3eg-iocc: set default tune to cortexa53

- meta-lmp-base/recipes-core/dropbear/dropbear/dropbear@.service
- meta-lmp-base/recipes-core/dropbear/dropbear/dropbearkey.service
- meta-lmp-base/recipes-core/dropbear/dropbear_%.bbappend
ECDSA is a lot faster to generate during first use, so prefer it instead
of RSA 2048 (default from OE).
> base: dropbear: prefer ecdsa instead of rsa

- meta-lmp-base/recipes-security/optee/optee-os-fio_3.10.0.bb
```
- 12c10709 [FIO fromtree] ldelf: arm64: support R_AARCH64_NONE relocations
- da24e396 [FIO fromtree] ldelf: arm32: support R_ARM_NONE relocations
```
> base: optee-os-fio: 3.10: bump to 12c10709

- meta-lmp-base/recipes-bsp/u-boot/u-boot-fio_2020.04.bb
```
- 89f95b569c [FIO internal] imx8mq: add definition for SRC_SBMR2_SEC_CONFIG
```
> base: u-boot-fio: 2020.04: bump to 89f95b569c

- meta-lmp-base/recipes-sota/fiotools/fiotools_git.bb
- A recipe to build and install fiotools.
It includes fiopush and fiocheck aimed to push an ostree repo to and check if it's synced with OSTreeHub.
> base: fiotools: add a recipe for fiotools

- meta-lmp-base/recipes-sota/aktualizr/aktualizr/aktualizr-lite.service.in
Move default tmpdir used by aktualizr (boost) to /run/aktualizr instead
of /tmp by default, to avoid having systemd cleaning up files that are
important for aktualizr's runtime.
> base: aktualizr-lite: move tmpdir to /run

- meta-lmp-base/recipes-security/optee/optee-os-fio_3.10.0.bb
- 53fad5f6 Add object name to error output
- e5f5fa8b core: imx: build snvs driver for imx8mm
- daaa6cb8 core: imx: add snvs base address for imx8m
- 8d35b6cf imx: pm: add support for reset2 function
- 1cc8748d core: sm: add PSCI 1.1 SYSTEM_RESET2 support
> base: optee-os: Bump to 53fad5f6

- meta-lmp-base/classes/lmp-disable-gplv3.bbclass
Turn LMP_DISABLE_GPLV3 on when this class is used.
This way, we can better control along the meta-layer which package or packagegroup is being installed
> base: class: lmp-disable-gplv3: Enable the LMP_DISABLE_GPLV3

- meta-lmp-base/recipes-sota/aktualizr/aktualizr_%.bbappend
- e7821f4 docker: assume TUF repo server is Hub creds provider
- ac594c1 callback: explicit Target name as callback context
> base: aktualizr-lite: bump to e7821f4

- meta-lmp-base/recipes-support/systemd-journald-config/systemd-journald-config.bb
- meta-lmp-base/recipes-support/systemd-journald-config/systemd-journald-config/forward-console.conf
Add recipe used to provide configuration fragments for systemd journald,
including one config to forward journal to console by default.
This can be useful on systems with getty disabled.
> base: systemd-journald-config: add recipe

- meta-lmp-base/recipes-sota/lmp-device-register/lmp-device-register_git.bb
base: lmp-device-register: bump to bc56368f
- 032d4f6 Add parameter to turn on an ostree proxy usage
> Bump lmp-dev-reg version

- meta-lmp-base/recipes-core/initrdscripts/initramfs-module-install-efi/init-install-efi.sh
Fix compose-apps preloading logic by making sure the older preloaded
content gets removed before copying over the ones available as part of
the EFI installer.
> base: init-install-efi: fix compose-apps preloading

- meta-lmp-base/recipes-support/mfgtool-resize-helper/mfgtool-resize-helper/mfgtool-resize-helper
- meta-lmp-base/recipes-support/mfgtool-resize-helper/mfgtool-resize-helper_0.1.bb
This will allow us to use the mfgtools to resize the filesystem
on the device without leaving GPLv3 code in the production image.
> base: add mfgtool-resize-helper

- meta-lmp-base/conf/distro/include/lmp.inc
- meta-lmp-base/recipes-core/images/initramfs-ostree-lmp-image.bb
- meta-lmp-base/recipes-kernel/linux/kmeta-linux-lmp-5.10.y.inc
- meta-lmp-base/recipes-samples/images/lmp-base-console-image.bb
- meta-lmp-base/recipes-samples/images/lmp-feature-ima.inc
- meta-lmp-base/recipes-samples/images/lmp-gateway-image.bb
- meta-lmp-base/recipes-security/ima_policy_appraise_all/ima-policy-appraise-all_1.0.bbappend
- meta-lmp-base/recipes-security/ima_policy_hashed/ima-policy-hashed_1.0.bbappend
- meta-lmp-base/recipes-security/ima_policy_simple/ima-policy-simple_1.0.bbappend
- meta-lmp-base/recipes-security/ima_policy_tcb/files/ima_policy_tcb
- meta-lmp-base/recipes-security/ima_policy_tcb/ima-policy-tcb_1.0.bb
- meta-lmp-base/recipes-support/ima-inspect/ima-inspect_0.14.bb
Add patches to allow initial support for IMA, when enabled via DISTRO_FEATURES (to be done at factory level).
This will cause the build to include a default IMA policy file that gets loaded by initrd.
Recommend reading both https://wiki.gentoo.org/wiki/Integrity_Measurement_Architecture and https://en.opensuse.org/SDB:Ima_evm for having a better understanding about IMA in general.
> Add initial support for IMA

- meta-lmp-base/recipes-bsp/u-boot/u-boot-ostree-scr-fit/boot-common.cmd.in
```
If we are validating secondary boot path, Linux should force reboot back to
primary path after running reboot cmd (this is needed for boards without
software POR reset support, like Apalis iMX6).
```
> u-boot-ostree-scr-fit: boot-common: force primary path before reset

- meta-lmp-base/recipes-bsp/u-boot/u-boot-ostree-scr-fit/boot-common.cmd.in
```
Provide explicitly bootfirmware_version as the only
variable that should be imported from version.txt.
For env import help:
env import [-d] [-t [-r] | -b | -c] addr [size] [var ...]
...
var... List of the names of the only variables that get
imported from the environment at address 'addr'.
Without arguments, the whole environment gets imported.
```
> u-boot-ostree-scr-fit: boot-common: import only bootfirmware_version

- meta-lmp-base/recipes-bsp/u-boot/u-boot-ostree-scr-fit/boot-common.cmd.in
Initialize bootfirmware_version to the version available at the rootfs
when performing initial boot after a clean flash (no valid
environment).
This helps aktualizr-lite to avoid doing unnecessary boot firmware
updates if nothing really changed from initial flash.
> base: u-boot-ostree-scr-fit: ubootenv: initialize bootfirmware_version

- meta-lmp-base/recipes-bsp/u-boot/u-boot-ostree-scr-fit/boot-common.cmd.in
Save fiovb.is_secondary_boot state for allowing userspace to
easily identify the boot mode via environment.
Only done with ubootenv as we don't have a variable in fiovb for
is_secondary_boot.
> base: u-boot-ostree-scr-fit: save fiovb.is_secondary_boot state

- meta-lmp-base/recipes-bsp/u-boot/u-boot-fio_2020.04.bb
- 66b40b69abe [FIO internal] spl: enable hw_watchdog for non-dm case
- f9ae151ff88 [FIO internal] add mx7 and mx7ulp support
- e1ce3e1e25f [FIO internal] imx: add low level code for secondary boot in 7ulp
- f1c76782b30 [FIO extras] fiovb: return error on init if board not closed
- 8aaa110b909 [FIO internal] imx: drop imx_warm_reset workaround
> base: u-boot-fio: bump to 66b40b69abe

- meta-lmp-base/recipes-samples/images/lmp-image-common.inc
Allow hosts to be managed via nss-altfiles, but keep the original
content in place as it is common for containers to bind/reuse /etc/hosts
directly, which is a problem when that gets provided by nss-altfiles.
> base: lmp: nss-altfiles: keep standard hosts

- meta-lmp-base/recipes-sota/aktualizr/aktualizr/aktualizr-lite.service.in
- meta-lmp-base/recipes-sota/aktualizr/aktualizr_%.bbappend
base: aktualizr-lite: bump to ab345cc
- b94670a aklite: extend installation report with App state
- d85c1ce apps: store and make use of App update state
- 9bc4fc1 app: let dockerd manage App's container life
- 14c21f2 aklite: add a system-wide lock for aklite
- 3ceb809 aklite: remove the download and update locks
> Bump aklite version 3ceb809

- meta-lmp-base/recipes-bsp/u-boot/u-boot-ostree-scr-fit/boot-common.cmd.in
This will set the bootfirmware_version on a closed board if the
variable is not set, to the current version in rootfs.
> base: u-boot common add setting bootfirmware_version

- meta-lmp-base/recipes-sota/aktualizr/aktualizr_%.bbappend
- df0760a bootloader: update fw if bootfirmware_version is not set (#104)
> base: aktualizr-lite: bump to df0760a

- meta-lmp-base/recipes-graphics/wayland/weston-init.bbappend
When building DISTRO=lmp-[x]wayland several files are setup for
the weston-init recipe.  The files themselves are under an
lmp-wayland directory.
However, the bbappend attempts to use them without qualification.
This results in the following messages whenever any DISTRO besides
lmp-[x]wayland builds weston-init (eventually resulting in a build break):
WARNING: build-xxx/conf/../../layers/openembedded-core/meta/recipes-graphics/wayland/weston-init.bb: Unable to get checksum for weston-init SRC_URI entry utilities-terminal.png: file could not be found
WARNING: build-xxx/conf/../../layers/openembedded-core/meta/recipes-graphics/wayland/weston-init.bb: Unable to get checksum for weston-init SRC_URI entry background.jpg: file could not be found
...
ERROR: weston-init-1.0-r0 do_fetch: Fetcher …
> base: wayland: weston-init: require lmp-wayland for files append

- meta-lmp-base/classes/lmp.bbclass
We are changing CI to trigger an "assemble-system-image" run that works
identical to our container builds. This gives us one code path that is
capable of dealing with our advanced tagging scenarios customers are
starting to hit.
> base: Remove prebuilt image logic

- meta-lmp-base/recipes-kernel/wpanusb/wpanusb_git.bb
WARNING: wpanusb-git-r0 do_populate_lic: Could not copy license file /build/layers/poky/meta/files/common-licenses/GPL-2.0 to /build/project/tmp/work/qemuarm64-lmp-linux/wpanusb/git-r0/license-destdir/wpanusb/GPL-2.0: [Errno 2] No such file or directory: '/build/layers/poky/meta/files/common-licenses/GPL-2.0'
ERROR: wpanusb-git-r0 do_populate_lic: QA Issue: wpanusb: LIC_FILES_CHKSUM points to an invalid file: /build/layers/poky/meta/files/common-licenses/GPL-2.0 [license-checksum]
ERROR: wpanusb-git-r0 do_populate_lic: Fatal QA errors found, failing task.
Signed-off-by: Jeremy Puhlman <jpuhlman@mvista.com>
> wpausb: point to correct gpl-2.0 license.

- meta-lmp-base/recipes-tpm/swtpm/swtpm_%.bbappend
When static user IDs are enabled, the build breaks on swtpm recipe:
ERROR: build/conf/../../layers/meta-security/meta-tpm/recipes-tpm/swtpm/swtpm_0.2.0.bb: argument -d/--home-dir: expected one argument
ERROR: build/conf/../../layers/meta-security/meta-tpm/recipes-tpm/swtpm/swtpm_0.2.0.bb: swtpm: Unable to parse arguments for USERADD_PARAM_swtpm '--system -g tss --home-dir      --no-create-home  --shell /bin/false swtpm':
ERROR: Failed to parse recipe: build/conf/../../layers/meta-security/meta-tpm/recipes-tpm/swtpm/swtpm_0.2.0.bb
The --home-dir parameter requires an argument according to the parser.
This fix should be discussed upstream.
Upstream-Status: Pending
> base: recipes-tpm: swtpm: drop home-dir param to fix parse error

- meta-lmp-base/recipes-extended/ostree/ostree/0001-ostree-pull-set-request-timeout.patch
- meta-lmp-base/recipes-extended/ostree/ostree_%.bbappend
Set a timeout for an overall request processing in order to avoid an
ostree pull/fetch API call or CLI command hang.
The timeout value can be specified via an env variable OSTREE_CURL_TIMEOUT,
if not defined, or equal to zero or it cannot be converted to a long type then
the default value is set.
> base: ostree: patch to setup a curl request timeout

- meta-lmp-base/recipes-sota/aktualizr/aktualizr_%.bbappend
- 4999fa0 apps: use DEBUG level msg if no app state file
- 273ee00: fixup! add dummy 'update-lockfile' param for
backward compatibility with older LmP versions
> base: aktualizr-lite: bump to 4999fa0

- meta-lmp-base/recipes-sota/lmp-device-register/lmp-device-register_git.bb
-  94b288c Use a system-wide file lock to check if aklite is running
> lmp-device-register: bump to 94b288c

- meta-lmp-base/recipes-containers/docker/docker-lmp.inc
pigz takes advantage of both multiple CPUs and multiple
CPU cores for higher compression and decompression speed,
and also set at the official packages.
> base: docker: add pigz to rdepends

- meta-lmp-base/recipes-containers/docker/docker-moby.bb
- meta-lmp-base/recipes-containers/docker/docker-moby/0001-registry-increase-TLS-and-connection-timeouts.patch
- increase TLS connection timeout (10s is too low for poor network condition);
- increase ping & host resolution timeout
- increase an overall connection timeout.
> base: docker-moby: patch dockerd to increase timeouts

- meta-lmp-base/recipes-support/mfgtool-resize-helper/mfgtool-resize-helper/mfgtool-resize-helper
The -p option on e2fsck is not enough to make sure the partition is clean for resizing
so change it to a -y so it will fix.
Then resize may still want e2fsck but since we just did it, we can force resize2fs to
do the resize anyway.
> base: recipes-support resize helper needs to be more forceful

- meta-lmp-base/recipes-extended/ostree/ostree/0001-ostree-pull-set-request-timeout.patch
Increase the default curl request timeout up to 13 minutes. We cannot set higher than ~ 15m because of this issue https://github.com/ostreedev/ostree/issues/2383.
It can be critical in the case of big files pulling through the network with limited bandwidth. libostree doesn't do a resumable download of a single file, so if a timeout occurs then the subsequent file download retry starts from the beginning, which might lead to endless retries...
This change slightly improves chances to succeed. In addition to this, I am going to limit the maximum allowed file size in the rootfs that LmP build generates (currently it's set to 4GB).
> base: ostree: increase default curl request timeout

- meta-lmp-bsp/recipes-kernel/linux/linux-lmp-ea-imx_git.bb
- b3dfd5e95c6e Revert "[fio extras] iMX7ULP: PMIC: BD70528 5.4-based changes"
> bsp: linux-lmp-ea-imx: bump to b3dfd5e95c6e

- meta-lmp-base/recipes-sota/lmp-device-register/lmp-device-register_git.bb
Pull in change that allows lmp-device-register to use a configurable
authentication header
> recipes-sota: Bump lmp-device-register version

- meta-lmp-base/recipes-sota/aktualizr/aktualizr_%.bbappend
Pull in change that adds Target's TAG to /var/sota/current-target
> recipes-sota: Bump aklite version

- meta-lmp-base/recipes-sota/ostreeuploader/ostreeuploader_git.bb
- fiopush: limit a repo file size
> base: ostreeuploader: bump to 1b11a24

- meta-lmp-base/recipes-bsp/u-boot/u-boot-tools/0001-tools-image-host-fix-wrong-return-value.patch
- meta-lmp-base/recipes-bsp/u-boot/u-boot-tools_%.bbappend
```
Backport patch from [1], which fixes FIT signing issues. Details:
A following error was observed:
| Can't write signature for 'signature@1' signature node in
| 'conf@imx6ull-colibri-wifi-eval-v3.dtb' conf node: <unknown error>
| uboot-mkimage Can't add hashes to FIT blob: -1
This is caused by a wrong return value being used in uboot source.
The return value '-ENOSPC' of fit_set_timestamp function does not match
the caller fit_image_write_sig's expection which is '-FDT_ERR_NOSPACE'.
Fix it by not calling fit_set_timestamp, but call fdt_setprop instead.
[1] http://git.yoctoproject.org/cgit.cgi/poky/commit/?id=e9fa8f9001471bb240e997cb4537d2f617f22957
```
> base: u-boot-tools: fix a mkimage signature issue

- meta-lmp-base/files/lmp-group-table
- meta-lmp-base/files/lmp-passwd-table
Required and used by the weston and weston-init recipe.
> base: lmp-passwd/group: add weston/wayland user and group

- meta-lmp-base/recipes-samples/images/lmp-feature-wayland.inc
rootfs-postcommands.bbclass changes the	system default target to
graphical.target if IMAGE_FEATURES contains x11-base or weston.
This patch checks for wayland on DISTRO_FEATURE and if finds it adds
weston to IMAGE_FEATURES.
> base: lmp-wayland: triggering system default target

- meta-lmp-base/recipes-graphics/wayland/weston-init.bbappend
- meta-lmp-base/recipes-graphics/wayland/weston-init/lmp-wayland/weston.env
- meta-lmp-base/recipes-graphics/wayland/weston-init/lmp-wayland/weston.service.patch
- Some devices do not launch weston without the input device connected.
Looks like the configuration on weston.ini [core] require-input=bool
is not the same as --continue-without-input.
According to this issue, it will be fixed in the next version:
https://gitlab.freedesktop.org/wayland/weston/-/merge_requests/524
Signed-off-by: Raul Muñoz <raul@foundries.io>
> base: wayland: weston-init: Add $OPTARGS

- meta-lmp-base/recipes-graphics/wayland/weston-init.bbappend
meta-freescale implements a function to uncomment assignments like
This function is just available if meta-freescale is included.
The commit will duplicate the function and add the set
INI_UNCOMMENT_ASSIGNMENTS for x11 wayland distro regardless of
the board.
Tested with and without meta-freescale.
Signed-off-by: Raul Muñoz <raul@foundries.io>
> base: wayland: weston-init: Uncomment Assignments

- meta-lmp-base/conf/distro/include/lmp.inc
- meta-lmp-base/recipes-samples/images/lmp-image-common.inc
Currently a normal user is unable to change the group list for a user
based on normal tooling (e.g. useradd/usermod), as the main group file
is provided by nss-altfiles (ro - /usr/lib/group) and not by /etc/group.
Follow the same solution as done in rpm-ostree and define a list of
groups that should be mirrored from /usr/lib/group to /etc/group when
creating the image. This should be used for groups that are commonly
changed by the user at runtime (e.g. when adding a new user) such as
audio, sudo and video. Build time groups and users can stay at
nss-altfiles (getgrent will do a merge based on what is configured in
nsswitch.conf).
Reference change from rpm-ostree:
https://github.com/coreos/rpm-ostree/commit/9a2007389337c61c152ea6e89575436e4fe5b1c0
Signed-off-by: Ricardo Salveti …
> base: lmp: add support for ETC_GROUP_MEMBERS

- meta-lmp-base/classes/lmp.bbclass
- meta-lmp-base/recipes-core/images/initramfs-ostree-lmp-image.bb
- meta-lmp-base/recipes-core/initrdscripts/initramfs-framework/ostree_factory_reset
- meta-lmp-base/recipes-core/initrdscripts/initramfs-framework_%.bbappend
- meta-lmp-base/recipes-samples/images/lmp-image-common.inc
- meta-lmp-base/recipes-sota/aktualizr/aktualizr/tmpfiles.conf
- meta-lmp-base/recipes-sota/aktualizr/aktualizr_%.bbappend
On ostree-based systems there are basically 2 locations for rw content, /etc and /var.
As the original /etc (when creating the rootfs) is also stored under /usr/etc on the same deployment (and used during the 3-way merge for updating /etc when applying an update), it is easy to handle as we can simply just erase /etc and restore from what is available at /usr/etc.
As the system is able to manage an empty /var (which is the case during first boot) and recreate all the require directories and files (via systemd tmpfiles.d), we don't need to do much here besides just removing it entirely. While /var can be completely removed, we also have use cases for requiring /var/sota to stay (e.g. not wiping the device registration), so we need to allow the user to decide what to wipe.
As a way to …
> Initial implementation for ostree factory reset

- meta-lmp-base/recipes-bsp/u-boot/u-boot-ostree-scr-fit/boot.cmd
- meta-lmp-base/recipes-support/mfgtool-files/mfgtool-files/bootloader.uuu.in
- meta-lmp-base/recipes-support/mfgtool-files/mfgtool-files/full_image.uuu.in
- meta-lmp-bsp/recipes-support/mfgtool-files/mfgtool-files/imx7ulpea-ucom/bootloader.uuu.in
Prefer using the new default fit separator '-' instead of '@', so it is
able to load standard mfgtools fit images.
> bsp: mfgtool-files: update fit separator

- meta-lmp-bsp/recipes-kernel/linux/linux-lmp-ti-staging/am64xx-evm/0001-arm64-dts-ti-k3-am642-sk-Enable-WLAN-connected-to-SD.patch
- meta-lmp-bsp/recipes-kernel/linux/linux-lmp-ti-staging_git.bb
In the 5.10 kernel the WiFi config was not set as it was in the
5.4 kernel. This will add that missing dtb data.
> bsp: Enable WiFi on am64xx-evm SK version

- meta-lmp-base/recipes-sota/aktualizr/aktualizr_%.bbappend
Relevant changes
- a40a69b pull ostree from GCS bucket(s) with fallback to ostreeproxy/DG
- a42d1d6 aklite: add ability to manage non-booted rootfs
- c698af0 apps: check if the state files exist before use
- 0d3bc06 apps: check downloaded App contains a compose file
> base: aktualizr-lite: bump to a40a69b

- meta-lmp-base/recipes-bsp/u-boot/u-boot-fio-common.inc
- meta-lmp-base/recipes-bsp/u-boot/u-boot-lmp-common.inc
- meta-lmp-bsp/dynamic-layers/xilinx/recipes-bsp/u-boot/u-boot-xlnx_2021.07.bb
```
Deploy the u-boot configuration that was used during the build
process as it's done by default now for u-boot-fio,
as it might be useful as reference later.
```
> bsp: u-boot-xlnx: deploy u-boot config used by the build

- meta-lmp-base/recipes-support/mfgtool-files/mfgtool-files_0.1.bb
Update UUU release to 1.4.139, fix incorrect recipe license (based on
UUU upstream) and also install/deploy the mac binary which is now
released by upstream.
New features:
* Add help option -IgSerNum to set windows registry to ignore serial
* Number above too much entry in register when burn many boards.
* Add snap support
* Add 8ulp support
* Deploy mac image
Bug fixes
* Fixed missed last chunk when meet specific android sparse file
* Return out of memory when allocate failure
* -bshow don't show uuu version information and recover cursor ESC
> base: mfgtool-files: update UUU 1.4.43 -> 1.4.139

- meta-lmp-base/recipes-containers/containerd/containerd-opencontainers_git.bb
- meta-lmp-base/recipes-containers/docker/docker-moby.bb
- meta-lmp-base/recipes-containers/runc/files/0001-Makefile-respect-GOBUILDFLAGS-for-runc-and-remove-re.patch
- meta-lmp-base/recipes-containers/runc/runc-opencontainers_git.bb
* containerd updated to 1.5.5
* docker updated to 20.10.8
* runc updated to v1.0.2
> Backport docker/containerd/runc updates from meta-virtualization master

- meta-lmp-base/recipes-sota/aktualizr/aktualizr_%.bbappend
This brings in a new version of aktualizr-lite that can be built as
an api and shared library for custom clients to extend.
Other changes include:
* 68325ced - Fix hwinfo reporting on x86
> recipes-sota: Bump aktualizr-lite

- meta-lmp-base/recipes-sota/aktualizr/aktualizr_%.bbappend
Custom clients built against aktualizr-lite-lib have a couple of runtime
dependencies including libfyaml and lshw. This change ensure the
resulting images will include those dependencies.
> recipes-sota: Set RDEPENDS for aktualizr-lite-lib

- meta-lmp-base/recipes-support/fioconfig/fioconfig_git.bb
Pulls in a single change to support "safe handlers" as the default
option.
> fioconfig: Bump version

- meta-lmp-base/classes/kernel-lmp-fitimage.bbclass
In fitimage_assemble, we use a shell variable "i" to keep track
of the number of DTBs we've added.  This variable is compared
to "dtbcount" in order to see if we're on the first or "default"
dtb.
However, we also use the "i" variable in fitimage_emit_section_config
to keep a running count of loadables so that we can name them
"loadable_${i}" for uniqueness.
This means anytime "FIT_LOADABLES" is set, we are messing with the DTB
counter and it causes more than 1 "default" node to possibly be set.
Fix this by not using the "i" variable in fitimage_emit_section_config.
> base: kernel-lmp-fitimage: fix loadable and dtb counters

- meta-lmp-base/recipes-bsp/u-boot/u-boot-ostree-scr-fit/boot-common.cmd.in
Add support for loading custom firmware in boot-common.cmd.in include.
> bsp: u-boot-ostree-scr-fit: add support for loading custom firmware

- meta-lmp-base/recipes-bsp/u-boot/u-boot-fio-common.inc
- meta-lmp-base/recipes-containers/containerd/containerd-opencontainers_git.bb
- meta-lmp-base/recipes-containers/docker/docker-moby.bb
- meta-lmp-base/recipes-containers/runc/runc-opencontainers_git.bb
- meta-lmp-base/recipes-devtools/mcumgr/mcumgr_git.bb
- meta-lmp-base/recipes-kernel/jool/jool_git.bb
- meta-lmp-base/recipes-kernel/linux/linux-lmp-dev-mfgtool.bb
- meta-lmp-base/recipes-kernel/linux/linux-lmp-dev.bb
- meta-lmp-base/recipes-kernel/wireguard/wireguard-module_1.0.20210606.bb
- meta-lmp-base/recipes-kernel/wpanusb/wpanusb_git.bb
- meta-lmp-base/recipes-security/optee/optee-client.inc
- meta-lmp-base/recipes-security/optee/optee-examples.inc
- meta-lmp-base/recipes-security/optee/optee-fiovb_git.bb
- meta-lmp-base/recipes-security/optee/optee-os-fio.inc
- meta-lmp-base/recipes-security/optee/optee-sks_git.bb
- meta-lmp-base/recipes-security/optee/optee-test.inc
- meta-lmp-base/recipes-security/optee/pkcs11-se050-import_git.bb
- meta-lmp-base/recipes-sota/aktualizr/aktualizr_%.bbappend
- meta-lmp-base/recipes-sota/custom-sota-client/custom-sota-client_git.bb
- meta-lmp-base/recipes-sota/ostreeuploader/ostreeuploader_git.bb
- meta-lmp-base/recipes-support/crucible/crucible_git.bb
- meta-lmp-base/recipes-support/fio-docker-fsck/fio-docker-fsck_git.bb
- meta-lmp-base/recipes-support/fioconfig/fioconfig_git.bb
- meta-lmp-base/recipes-support/ima-inspect/ima-inspect_0.14.bb
- meta-lmp-base/recipes-support/lshw/lshw_git.bb
Tested locally:
- lmp-mfgtool+mfgtool-files, machine=imx6ullevk: **OK**
- lmp-base+lmp-mini-image, machine=imx6ullevk: **OK**
Tested on Factory:
- lmp-mfgtool+mfgtool-files, machine=imx6ullevk: **OK**
- lmp-base+lmp-factory-image, machine=imx6ullevk: **OK**
Due to https://github.blog/2021-09-01-improving-git-protocol-security-github/#no-more-unauthenticated-git
it is required to use https protocol for github repo accessing.
> master: base: use https protocol

- meta-lmp-base/recipes-support/fioconfig/fioconfig_git.bb
Let OE handle the default ldflags used by the build and also allow
shared support as an effort to reduce the binary size.
> base: fioconfig: reuse OE ldflags and enable shared

- meta-lmp-base/files/lmp-group-table
- meta-lmp-base/files/lmp-passwd-table
Required and used by the pulseaudio recipe.
Signed-off-by: Raul Muñoz <raul@foundries.io>
> base: lmp-passwd/group: add pulse user and group

- meta-lmp-base/recipes-bsp/u-boot/u-boot-fio_2020.04.bb
- e7934985ad [FIO extras-squash] imx_env: fix set mfg to run fastboot by default
> base: u-boot-fio: 2020.04: bump to e7934985ad

- meta-lmp-base/recipes-sota/aktualizr/aktualizr_%.bbappend
Adjust the aktualizr and sota-tools build configuration to the changes in the latest aktualizr build system.
1. Make sota-tools dependent on libostree.
2. Include package config metadata (aktualizr.pc) into the installation.
3. Switch to the latest aklite based on the latest aktualizr (uptane/aktualizr).
> Switch to new aktualizr

- meta-lmp-bsp/dynamic-layers/xilinx/recipes-bsp/u-boot/u-boot-xlnx_2021.07.bb
- 05532d557e [FIO toup] zynqmp: add dynamic detection of fit image spi offset
- 775778ae34 [FIO fromlist] xilinx: zynqmp: Config non zero SYS_SPI_U_BOOT_OFFS
> bsp: u-boot-xlnx: 2021.07: bump to 05532d557e

- meta-lmp-base/recipes-sota/lmp-device-register/lmp-device-register_git.bb
- 3fb49bb Ping the registration server prior to registration
- f3bbc70 Obtain an oauth token before HSM init
> lmp-device-register: bump rev to 3fb49bb

- meta-lmp-base/recipes-bsp/plug-and-trust-seteec/plug-and-trust-seteec_3.3.0.bb
The updated release restores the P&T check for the SE applet version to match the one
selected at build time.
> base: plug-and-trust-seteec: bump revision

- meta-lmp-base/recipes-sota/aktualizr/aktualizr_%.bbappend
- d132ef7 apps: tests for the app fetch check
- dd36f2c apps: do App fetching check thoroughly
- 7c4bb06 aklite: invoke the post check callback in any case
- baa56f3 apps: test container recreation parameterization
- dc53ca6 apps: parameterized App recreation before reboot
- a6400aa apps: check expected size of a layer manifest
- a4d55f8 restorable-apps: check App update size if possible
- cb3fd94 restorable-apps: check App metadata size before pull
> base: aktualizr-lite: bump to d132ef7

- meta-lmp-base/recipes-kernel/linux/linux-lmp-dev-mfgtool.bb
- meta-lmp-bsp/recipes-kernel/linux/linux-lmp-fslc-imx_git.bb
The 5.10-2.1.x-imx includes fixes from the mainline linux-stable and atm seems compatible with our patches and configs for lf-5.10.y.
> Use freescale 5.10-2.1.x-imx linux kernel instead of nxp lf-5.10.y

- meta-lmp-base/recipes-kernel/linux/linux-yocto_%.bbappend
This append is copied from meta-virtualization but now it is out of
the path is incomplete and the linux-yocto kernel virtualization are
silently dropped.
Correct the path and get the virtualization working again
Signed-off-by: Jerome Brunet <jbrunet@baylibre.com>
> linux-yocto: fixup virtualization include path

- meta-lmp-base/recipes-sota/lmp-device-register/lmp-device-register_git.bb
Relative changes:
- b54dfa3 Enable Restorable Apps by default
> base: lmp-device-register: bump to b54dfa3

- meta-lmp-bsp/recipes-kernel/linux/linux-lmp-ea-imx_git.bb
- 4026a5c639c Revert "[fio extras] imx7ulp poweroff state"
> bsp: linux-lmp-ea-imx: bump to 4026a5c

- meta-lmp-base/recipes-core/os-release/os-release.bbappend
Copy the os-release data to a CI build artifact/file.
> base: recipes-core: dump os-release to CI artifact

- meta-lmp-base/recipes-bsp/u-boot/u-boot-ostree-scr-fit/boot-common-alternative.cmd.in
Refer to fiovb.bootupgrade_primary_updated instead of bootupgrade_primary_updated
when in the closed platform path.
> base: u-boot-ostree-scr-fit: alternative: add missing fiovb header

- meta-lmp-bsp/recipes-support/mfgtool-files/mfgtool-files/apalis-imx6-sec/readme.md
- meta-lmp-bsp/recipes-support/mfgtool-files/mfgtool-files/apalis-imx8-sec/readme.md
- meta-lmp-bsp/recipes-support/mfgtool-files/mfgtool-files/imx6ullevk-sec/readme.md
- meta-lmp-bsp/recipes-support/mfgtool-files/mfgtool-files/imx8mm-lpddr4-evk-sec/readme.md
Include more information on the SPL signing process and
standardize the readme between the -sec supported machines.
> bsp: support: mfgtool-files: improve readme for -sec machines

- meta-lmp-base/recipes-bsp/u-boot/u-boot-fio_2021.04.bb
- 08349585ff [FIO internal] cmd: fiovb: increase fiovb_name buffer
> base: u-boot-fio: 2021.04: bump to 08349585ff

- meta-lmp-base/conf/distro/lmp-base.conf
modsign is useful on lmp but complicates local kernel module development
with lmp-base, so disable it by default (as we don't expect lmp-base to
follow the same security standards as lmp).
> base: lmp-base: drop modsign from DISTRO_FEATURES_DEFAULT

- meta-lmp-base/recipes-kernel/linux/kmeta-linux-lmp-5.10.y.inc
- 1ebe16a bsp: imx: iot-gate-imx8: remove DPAA options
- e010a48 bsp: imx: apalis-imx8: fix config conflicts
- c869933 bsp: imx: imx8qm-mek: fix config conflicts
- 80f7905 bsp: imx: imx8mmevk: fix config conflicts
- 2985f07 bsp: uz3eg-iocc: enable CONFIG_COMMON_CLK_VC5
> base: kmeta-linux-lmp-5.10.y: bump to 1ebe16a

- meta-lmp-bsp/conf/machine/orange-pi-r1.conf
A simple configuration for Orange Pi R1 that was based off a Orange Pi
Zero template.
Signed-off-by: Eric Bode <eric.bode@foundries.io>
> conf: machine: Adding Orange Pi R1 machine config

- meta-lmp-base/recipes-sota/aktualizr/aktualizr_%.bbappend
- cfa32fc aklite: rollback if Apps creation failer before reboot
- 9ddfb0b aklite: rollback if Apps fail to start on boot
- 373d9ed aklite: fix comparision with `current` while
checking for rollback. (Fix for just App update rollback)
- 8d77725 apps: check both skopeo and docker store before update
(check available storage before update)
- a519a76 ostree: add the configured ostree remote before pull
(switch to aktualizr 2022.1+fio)
> base: aktualizr-lite: bump to cfa32fc

- meta-lmp-bsp/recipes-kernel/linux/linux-lmp-xlnx_git.bb
Also includes latest changes from xlnx_rebase_v5.10_2021.2 tag.
> bsp: linux-lmp-xlnx: update to v5.10.93

- meta-lmp-base/recipes-kernel/linux/kmeta-linux-lmp-5.15.y.inc
- meta-lmp-base/recipes-kernel/linux/linux-lmp-lts_git.bb
- meta-lmp-base/recipes-kernel/linux/linux-lmp-rt_git.bb
- meta-lmp-base/recipes-kernel/linux/linux-lmp_git.bb
- meta-lmp-bsp/recipes-kernel/linux/linux-lmp/qemuarm64/zone_dma_revert.patch
Updating main linux-lmp kernel from 5.14 to 5.15 as 5.15 is the latest LTS.
> Stable kernel updates (linux-lmp family)

- meta-lmp-bsp/recipes-bsp/u-boot/u-boot-fio_%.bbappend
Typo was introduced by commit f83356f0 (bsp: fix single-char variables,
2021-10-21)
Signed-off-by: Andre Detsch <andre.detsch@foundries.io>
> bsp: u-boot-fio: Fix variable name typo in u-boot-fio_%.bbappend

- meta-lmp-base/conf/distro/include/lmp.inc
- meta-lmp-base/recipes-core/systemd/systemd_%.bbappend
To allow the user to enable support for networkd, we can't really use
the _removal syntax because that always gets parsed last, so instead
define a default set of packageconfig entries used and required by the
default LmP configuration via bbappends.
This is heavily based on the oe-core systemd recipe, and will have to be
maintained and updated as the main recipe adds/removes new options.
> base: systemd: define default packageconfig via bbappend

- meta-lmp-base/recipes-samples/images/lmp-image-common.inc
Add mtd-utils package for providing general MTD utilities (e.g. help
manipulating QSPI devices).
Licensed under GPLv2+ and provided by oe-core.
> base: lmp-image-common: add mtd-utils

- meta-lmp-base/recipes-kernel/linux/linux-lmp-dev-mfgtool.bb
Fix the kernel revision used by the recipe to avoid unexpected changes
coming from upstream.
Revision and version aligned with linux-lmp-fslc-imx.
> base: linux-lmp-dev-mfgtool: fix kernel revision used

- meta-lmp-base/recipes-support/fioconfig/fioconfig_git.bb
- 260a72e Merge pull request #21 from doanac/wireguard-race
- dcb758c vpn: Detect when device has failed to register config
- f4baae0 vpn: Fix racey code path in initVpn
- 3edcbc6 Merge pull request #20 from doanac/deps-updates
- fd85a3a go.mod: Bump ethereum dependency for ECIES
- 123ebb1 go.mod: Bump urfave/cli version
> base: fioconfig: bump rev to 260a72e

- meta-lmp-base/files/lmp-group-table
- meta-lmp-base/files/lmp-passwd-table
Both can be required depending on the packageconfig used by the systemd
recipe.
> base: lmp-passwd/group: add systemd journal-gateway and remote user/group

- meta-lmp-base/recipes-devtools/python/python3-docker/0001-config-Include-usr-lib-docker-in-search-path.patch
The proper logic as done by our golang /usr/bin/docker is to load the
system config if present and then *extend* that with any user defined
config files. The docker-py logic did not allow for that.
> docker-py: Fix configuration import logic

- meta-lmp-bsp/dynamic-layers/freescale-layer/recipes-bsp/imx-mkimage/imx-boot_%.bbappend
Fix typo in imx-boot_%.bbappend.
Tested the mfgtool boot.
> Fix imx8mm -sec boot

- meta-lmp-base/recipes-sota/aktualizr/aktualizr_%.bbappend
- 35ebc64 docker: align image URI parsing with OCI dist spec
> base: aktualizr-lite: bump to 35ebc64

- meta-lmp-base/recipes-core/initrdscripts/initramfs-module-install-efi/init-install-efi.sh
Script mode is used to avoid prompting for user intervention, which
breaks the install flow.
> base: initramfs-module-install-efi: call parted with script mode

- meta-lmp-bsp/dynamic-layers/freescale-layer/recipes-bsp/imx-mkimage/imx-boot/0001-iMX8M-change-DDR-DMEM-padding.patch
- meta-lmp-bsp/dynamic-layers/freescale-layer/recipes-bsp/imx-mkimage/imx-boot_%.bbappend
Change padding of DMEM DDR firmware to save space in internal RAM.
DMEM is padded to 16KB but the actual size of this fw is less than
4KB, so padding to 4KB is enough.
imx-mkimage and U-Boot should be aligned in this change.
> bsp: imx-boot: change DDR DMEM firmware padding

- meta-lmp-base/recipes-bsp/u-boot/u-boot-fio_2021.04.bb
- 16568dac1a [FIO fromtree] imx8m: drivers/ddr: Change padding of DDR4 and LPDDR4
> base: u-boot-fio: 2021.04: bump to 16568dac1a

- meta-lmp-base/recipes-bsp/u-boot/u-boot-ostree-scr-fit/boot-common-alternative.cmd.in
- meta-lmp-base/recipes-bsp/u-boot/u-boot-ostree-scr-fit/boot-common.cmd.in
If an image is not found during 'load_image', the board reports:
Unknown command 'FIO: error occured while loading ...'
Fix this by adding the 'echo' command before the string.
> base: u-boot-ostree-scr-fit: add missing 'echo' command

- meta-lmp-base/recipes-core/initrdscripts/initramfs-module-install-efi/init-install-efi.sh
Disks without partition label (e.g. raw disks created via virtualbox
or qemu) will cause parted to abort when printing the disk information
(Error: unrecognised disk label).
> base: init-install-efi: handle disks without partition label

- meta-lmp-base/recipes-kernel/linux/kmeta-linux-lmp-5.10.y.inc
- bc94558a bsp: imx: imx8mm/mp/mq: add back CONFIG_DRM_IMX_SEC_DSIM
- a172480e bsp: imx: enable DesignWare PCI host platform
- 3f98e242 bsp: imx: imx8m: enable PCIEPHY reset control
> base: kmeta-linux-lmp-5.10.y: bump to bc94558a

- meta-lmp-bsp/dynamic-layers/freescale-layer/recipes-bsp/imx-atf/imx-atf/0001-plat-imx8mp-SiP-call-for-secondary-boot.patch
- meta-lmp-bsp/dynamic-layers/freescale-layer/recipes-bsp/imx-atf/imx-atf_%.bbappend
This fixes rollback support in imx8mp-lpddr4-evk.
> bsp: imx-atf: imx8mp: enable sip call for secondary boot

- meta-lmp-bsp/recipes-kernel/linux/linux-lmp-ti-staging_git.bb
Follow changes from meta-ti master/honister and update kernel
to 5.10.65.
> bsp: linux-lmp-ti-staging: update to 5.10.65

- meta-lmp-bsp/recipes-kernel/linux/linux-lmp-rpi_git.bb
Align with the same version used by meta-rpi honister.
> bsp: linux-lmp-rpi: update to 5.10.83

- meta-lmp-bsp/recipes-bsp/opensbi/opensbi_0.9.bbappend
Same issue as happened with riscv_get_extra_oemake_image (can't be set
to "" as that won't match None), so remove riscv_get_extra_oemake_fdt
since we expect the dtb to be provided via u-boot fit.
> bsp: opensbi: drop custom fdt function

- meta-lmp-base/recipes-containers/docker/docker-ce/0001-dynbinary-use-go-cross-compiler.patch
- meta-lmp-base/recipes-containers/docker/docker-ce/0001-libnetwork-use-GO-instead-of-go.patch
Restore patch content from what was already used by docker-moby, which
is required for proper risc-v support.
This is needed as linkshared is not yet supported on this arch.
> base: docker-ce: restore riscv64 support

- meta-lmp-base/conf/distro/include/lmp.inc
Append removed in newer revisions of meta-st-stm32mp (honister).
> base: lmp: drop old meta-st-stm32mp bbmasks

- meta-lmp-base/recipes-security/optee/optee-os-fio_3.15.0.bb
- 9b9bf5daa [FIO toup] drivers: dcp: fix HUK support
> base: optee-os-fio: 3.15: bump to 9b9bf5daa

- meta-lmp-bsp/conf/machine/include/lmp-machine-custom.inc
Avoid tmp overlay with the main machine as that results in build
failures when running with multiple cpu threads (due competing tmp
folder access).
> bsp: lmp-machine-custom: am64xx: set different tmpdir for k3r5

- meta-lmp-base/recipes-kernel/linux/kmeta-linux-lmp-4.19.y.inc
- meta-lmp-base/recipes-kernel/linux/kmeta-linux-lmp-5.10.y.inc
- 33b5ef2b base: kmeta-linux-lmp-4.19.y: bump to a293ed4
- f214ad95 base: kmeta-linux-lmp-5.10.y: bump to da6f413
> main: base: kmeta-linux-lmp: bump 4.19 and 5.10

- meta-lmp-base/recipes-extended/rpcbind/rpcbind_%.bbappend
We use nss altfiles by default in LmP, and without it being enabled
rpcbind is required to be in files (/etc/passwd).
> base: rpcbind: support for nss altfiles

- meta-lmp-base/recipes-bsp/u-boot/u-boot-ostree-scr-fit/boot-common.cmd.in
- meta-lmp-base/recipes-security/optee/optee-os-fio_3.15.0.bb
```
Fix the issue, when rpmb/ubootenv contains obsolete value of
fiovb.is_secondary_boot.
This happens after update is triggered:
1. secondary path is booted, fiovb.is_secondary_boot == 1
2. update procedure is run
3. saveenv && reset
3. primary boot path is booted, fiovb.is_secondary_boot == 0,
however it is not updated in ubootenv/rpmb storage.
5. In Linux fw_printenv/fiovb_printenv shows is_secondary_boot == 1,
regardless the fact, that the primary boot path is booted.
```
> base: u-boot-ostree-scr-fit: save fiovb.is_secondary_boot if changed

- meta-lmp-base/classes/uboot-fitimage.bbclass
> base: uboot-fitimage: Assign UBOOT_SPL_SIGN* a  weak default value

- meta-lmp-bsp/recipes-bsp/u-boot/u-boot-fio-mfgtool_%.bbappend
Due to a recent change in GCC configuration, the size of SPL for mx8mp
is causing an SRAM overrun.
Disable the new setting to reduce the SPL back to an acceptable size.
> bsp: u-boot-fio-mfgtool: mx8mp: fix SPL size overrun

- meta-lmp-base/classes/uboot-fitimage.bbclass
In case the file path is invalid, it is important to alert the user
as when the file is not present it will result in a invalid boot.
> base:uboot-fitimage.bbclass: Test if UBOOT_SPL_SIGN_KEYDIR exists

- meta-lmp-bsp/recipes-support/mfgtool-files/mfgtool-files/apalis-imx6-sec/full_image.uuu.in
- meta-lmp-bsp/recipes-support/mfgtool-files/mfgtool-files/apalis-imx8-sec/full_image.uuu.in
- meta-lmp-bsp/recipes-support/mfgtool-files/mfgtool-files/imx8mm-lpddr4-evk-sec/full_image.uuu.in
- meta-lmp-bsp/recipes-support/mfgtool-files/mfgtool-files_%.bbappend
We need to clear the fiovb variables when re-flashing images for -sec targets
otherwise it will boot with old values, which might not be intetional.
> bsp: mfgtool-files: clear fiovb variables for -sec targets in full_image

- meta-lmp-bsp/recipes-bsp/u-boot/u-boot-fio_%.bbappend
Follow the fix applied in meta-freescale (999f5d25a2) to fix the
conflict issue when there are multiple entries in UBOOT_CONFIG.
> bsp: u-boot-fio: mx8: fix deploy for multiple UBOOT_CONFIG

- meta-lmp-base/files/lmp-group-table
- meta-lmp-base/files/lmp-passwd-table
This is required if you enable coredump in systemd PACKAGECONFIG
variable.
Signed-off-by: Matija Tudan <tudan.matija@gmail.com>
> base: lmp-passwd/group: add systemd-coredump user and group

- meta-lmp-base/recipes-containers/docker-compose/docker-compose-switch_1.0.4.bb
- meta-lmp-base/recipes-containers/docker-compose/docker-compose_2.4.1.bb
- meta-lmp-base/recipes-containers/docker-compose/python3-docker-compose_%.bbappend
V2 has a different set of commands, and it is not 100% compatible with V1, but this PR also includes compose-switch to facilitate testing V2 without changing any clients.
The main difference is that to call docker compose you now need to use `docker compose` instead of `docker-compose`.
The ideal scenario is to change all clients to use V2 by default, without requiring compose-switch to be installed, but we can do that migration later.
> Docker compose v2

- meta-lmp-base/files/lmp-group-table
- meta-lmp-base/files/lmp-passwd-table
Required by the parsec service (from meta-security/meta-parsec).
> base: lmp-passwd/group: add parsec user and group

- meta-lmp-base/classes/lmp.bbclass
New params to specify fiopush/fiocheck to use, by default or if the specified one are not valid/exist then fiopush/fiocheck built by OE are used.
> Add params to define fiopush/check value

- meta-lmp-base/conf/layer.conf
- meta-lmp-base/dynamic-layers/parsec-layer/recipes-parsec/parsec-service/parsec-service/parsec-tmpfiles.conf
- meta-lmp-base/dynamic-layers/parsec-layer/recipes-parsec/parsec-service/parsec-service_%.bbappend
Required for the parsec service to work correctly on lmp.
> Parsec fixes for sota/lmp

- meta-lmp-base/lib/crate.py
Required until the proposed fix is applied upstream and backported to
honister.
This file is basically crate.py from oe-core/honister plus:
```
diff --git a/meta/lib/crate.py b/meta/lib/crate.py
index d10f441875..1571f8372f 100644
--- a/meta/lib/crate.py
+++ b/meta/lib/crate.py
@@ -83,7 +83,7 @@ class Crate(Wget):
ud.parm['downloadfilename'] = "%s-%s.crate" % (name, version)
ud.parm['name'] = name
-        logger.debug(2, "Fetching %s to %s" % (ud.url, ud.parm['downloadfilename']))
+        logger.debug("Fetching %s to %s" % (ud.url, ud.parm['downloadfilename']))
def unpack(self, ud, rootdir, d):
"""
```
Upstream patch: https://lists.openembedded.org/g/openembedded-core/message/164412
> base: lib: temporarily add crate.py for fetch/debug issues

- meta-lmp-bsp/recipes-support/mfgtool-files/mfgtool-files/apalis-imx6-sec/full_image.uuu.in
There is a set of commits that fixes regression issues with flashing and booting an image.
> apalis-imx6-sec: fix flashing and booting

- meta-lmp-bsp/conf/machine/include/lmp-machine-custom.inc
EFI_PROVIDER should only be set by ebbr targets to avoid having fstab
and other related configs to be set even when not really required.
This is only required because meta-ti sets this by default at k3.inc.
> bsp: lmp-machine-custom: am64xx-evm: unset EFI_PROVIDER

- meta-lmp-base/classes/lmp-disable-gplv3.bbclass
- meta-lmp-base/recipes-support/resize-helper/resize-helper/resize-helper
- meta-lmp-base/recipes-support/resize-helper/resize-helper/resize-helper.service
- meta-lmp-base/recipes-support/resize-helper/resize-helper_0.1.bb
Update resize-helper to remove parted and replace with fdisk.
This removes any use of gplv3 content and so it can be included with gplv2 only builds.
> Resize helper

- meta-lmp-bsp/conf/machine/include/lmp-machine-custom.inc
meta-xilinx-core sets a default WKS_FILES (versal-generic.conf) which is
not compatible with sota-based images (ostree).
> bsp: lmp-machine-custom: versal: fix WKS_FILES settings

- meta-lmp-base/recipes-core/systemd/systemd_%.bbappend
We need to keep xz support enabled along with zstd otherwise devices
based on honister won't be able to read logs produced by hardknott (or
older) based images.
> base: systemd: add back xz support

- meta-lmp-base/recipes-samples/images/lmp-feature-wifi.inc
- meta-lmp-bsp/conf/machine/include/lmp-machine-custom.inc
- meta-lmp-bsp/recipes-kernel/linux-firmware/linux-firmware_%.bbappend
- move generic nxp89xx feature
- add files to support 8997 PCIE
- enable nxp89xx on imx8mp-lpddr4-evk
> Imx8mp wifi fix

- meta-lmp-base/recipes-kernel/linux/kmeta-linux-lmp-5.10.y.inc
- c914d691 bsp: imx: imx8mp: enable missing functionality
> base: kmeta-linux-lmp-5.10.y: bump to c914d691

- meta-lmp-base/recipes-containers/docker-compose/docker-compose/cli-config-support-default-system-config.patch
- meta-lmp-base/recipes-containers/docker-compose/docker-compose_2.4.1.bb
I've just created a pull request out of the Andy's commit, which is basically copy-paste of the patch to `docker cli` needed for building of `docker` itself https://github.com/foundriesio/meta-lmp/blob/main/meta-lmp-base/recipes-containers/docker/files/cli-config-support-default-system-config.patch.
> The patch to docker cli package needed to make `docker compose` work

- meta-lmp-bsp/recipes-kernel/linux-firmware/linux-firmware_%.bbappend
I have *not* tested it during boot, but I don't change the hashes, only how they are configured.
I have built it the lmp-base-console-image for:
* beaglebone-yocto
* imx6ullevk-sec
* imx8mm-lpddr4-evk
During the work to convert meta-lmp to kirkstone, a (QA) build error highlighted that some information is not set for those SRC_URI, but I think it would be a good fit for main as well
> bsp: linux-firmware: Include SRCREV for all the sources

- meta-lmp-base/recipes-security/optee/optee-examples-fio.inc
- meta-lmp-base/recipes-security/optee/optee-sks_git.bb
- meta-lmp-base/recipes-security/optee/optee-test-fio.inc
Since [1] python3-pycrypto is removed
[1] http://cgit.openembedded.org/meta-openembedded/commit/meta-python/recipes-devtools/python?id=84769a963974cffc5d877e57a46a289a84bc293d
> base: optee*: python3-pycrypto: Remove obsolete pycrypto module

- meta-lmp-base/recipes-bsp/device-tree/lmp-device-tree.bb
- meta-lmp-base/recipes-bsp/u-boot/u-boot-fio-common.inc
- meta-lmp-base/recipes-core/nss-altfiles/nss-altfiles_git.bb
- meta-lmp-base/recipes-devtools/python/python3-func-timeout_4.3.5.bb
- meta-lmp-base/recipes-kernel/jool/jool_git.bb
- meta-lmp-base/recipes-kernel/wpanusb/wpanusb_git.bb
- meta-lmp-base/recipes-security/optee/optee-fiovb_git.bb
- meta-lmp-base/recipes-security/optee/optee-test-fio.inc
- meta-lmp-base/recipes-support/crucible/crucible_git.bb
- meta-lmp-base/recipes-support/dnsmasq/dnsmasq_2.86.bbappend
- meta-lmp-base/recipes-support/ima-inspect/ima-inspect_0.14.bb
- meta-lmp-base/recipes-support/lshw/lshw_git.bb
- meta-lmp-base/recipes-support/mfgtool-files/mfgtool-files_0.1.bb
- meta-lmp-bsp/dynamic-layers/xilinx-tools/recipes-bsp/bitstream/bitstream-signed.bb
- meta-lmp-bsp/dynamic-layers/xilinx/recipes-bsp/u-boot/u-boot-xlnx_2022.01.bb
- meta-lmp-bsp/recipes-kernel/kernel-modules/kernel-module-nxp89xx_git.bb
Converts the LICENSE to use SPDX tags instead.
The script used to convert: https://git.openembedded.org/openembedded-core/tree/scripts/contrib/convert-spdx-licenses.py
> Spdx convert

- meta-lmp-base/recipes-samples/images/lmp-feature-optee.inc
They are not strictly required, so remove in order to make them optional
based on the user needs.
> base: lmp-feature-optee: drop sks, examples and pkcs11test

- meta-lmp-base/conf/distro/lmp-mfgtool.conf
- meta-lmp-base/conf/distro/lmp.conf
- meta-lmp-base/conf/layer.conf
- meta-lmp-bsp/conf/layer.conf
This is the initial patchset to start the work to convert meta-lmp to kirkstone.
It is not complete yet, by provides a good base to start working on BSP integration.
> Initial patchset to include kirkstone support

- meta-lmp-base/recipes-kernel/linux/kmeta-linux-lmp-5.10.y.inc
- abe5439: versal: preempt: preempt_none
> base: kmeta-linux-lmp-5.10.y: bump to abe5439

- meta-lmp-base/recipes-kernel/linux/kmeta-linux-lmp-5.10.y.inc
```
- 423dc80 bsp: imx8qm-mek: add CONFIG_AT803X_PHY=y
- abe5439 versal: preempt: preempt_none
- 38a542b versal: cpufreq: enforce the performance governor
- f4e09fd (tag: mp-86-linux-v5.10.y) bsp: imx8qm-mek: add CONFIG_GPIO_MAX732X=y
- c914d69 bsp: imx: imx8mp: enable missing functionality
```
> linux: kmeta-linux-lmp: 5.10: bump to 423dc80

- meta-lmp-bsp/recipes-bsp/u-boot/u-boot-ostree-scr-fit/apalis-imx8/boot.cmd
- meta-lmp-bsp/recipes-bsp/u-boot/u-boot-ostree-scr-fit/imx8qm-mek/boot.cmd
Drop "update_image_boot1" env variable, as it's not used anymore.
Write to boot1 is done by "backup_boot0" instead.
> bsp: u-boot-ostree-scr-fit: imx8qm: drop update_image_boot1

- meta-lmp-bsp/dynamic-layers/xilinx/recipes-bsp/u-boot/u-boot-xlnx_2022.01.bb
- 34fda873c0d Revert "[FIO toup] usb: dwc3: zynqmp: fix reset usb ULPI phy"
- ec9702752dd Merge tag 'xlnx_rebase_v2022.01_2022.1' into xilinx-v2022.01-rebase
- c50d6c48f4e misc: usb5744: usb2244: Setup gpio reset lines as output
- 529e1f44259 arm64: zynqmp: Add dmas, gpu, rtc, watchdogs and opp nodes for SOM
- 4517d7caead arm64: zynqmp: Add power domain description for PL
- 56d126b3081 dt-bindings: xilinx: Add missing ids for PD
- 670aa32d57f Revert "arm64: zynqmp: Add zynqmp firmware specific DT nodes"
- 3afae727f4d Revert "arm64: xilinx: Set CONFIG_ZYNQMP_FIRMWARE config for mini emmc"
- d605ed7c871 mmc: zynq_sdhci: Add weak function prototype
> bsp: u-boot-xlnx: 2022.01: bump to 34fda873c0d

- meta-lmp-base/recipes-sota/aktualizr/aktualizr_%.bbappend
- 5b0a792 apps: prune stopped containers after successful update
- 09070c8 aklite: httpclient: follow redirects
- 8680360 apps: make a storage high watermark configurable
- e507c3f apps: Use `docker compose` by default
- 5b922e2 apps: Inform a caller if no space while fetching
- a499ebd ostree: Detect and return no space error if pull fails
- 2db28ef aklite: Skip update download if failed before
- 96640d2 apps: Fallback to python's compose if no docker's
> base: recipe-sota: aktualizr-lite: bump to 96640d2

- meta-lmp-base/recipes-security/optee/optee-test_3.17.0.bb
Got dropped when updating from optee-test 3.15 to 3.17, but it is still
required due OpenSSL 3.0.
> base: optee-test: 3.17: add back -Wno-error=deprecated-declarations

- meta-lmp-base/recipes-bsp/u-boot/u-boot-fio_2022.04.bb
FIO-specific recipe based on the upstream u-boot 2022.04 release.
> base: u-boot-fio: add recipe for 2022.04

- meta-lmp-base/conf/distro/include/lmp.inc
Base version not available anymore, so add BBMASK in order to remove a
parsing warning until this is fixed at the meta-virtualization layer.
> base: lmp: add meta-virt xilinx xen_4.14 to BBMASK

- meta-lmp-bsp/recipes-support/mfgtool-files/mfgtool-files/apalis-imx6-sec/full_image.uuu.in
- meta-lmp-bsp/recipes-support/mfgtool-files/mfgtool-files/apalis-imx8-sec/full_image.uuu.in
- meta-lmp-bsp/recipes-support/mfgtool-files/mfgtool-files/imx8mm-lpddr4-evk-sec/full_image.uuu.in
- meta-lmp-bsp/recipes-support/mfgtool-files/mfgtool-files/imx8mp-lpddr4-evk-sec/full_image.uuu.in
is_secondary_boot is another variable that gets used by the common boot
logic, so make sure it is also initialized with a valid (zero) value.
> bsp: mfgtool-files: sec: zero is_secondary_boot during full_image

- meta-lmp-base/recipes-extended/ostree/ostree/0001-Allow-updating-files-in-the-boot-directory.patch
- meta-lmp-base/recipes-extended/ostree/ostree/0002-u-boot-add-bootdir-to-the-generated-uEnv.txt.patch
- meta-lmp-base/recipes-extended/ostree/ostree_%.bbappend
Patches to support copying (or hardlinking on single partition
systems) all files from the deployment's /usr/lib/ostree-boot
directory to the relevant /boot/ostree/$os-$bootcsum/ directory.
This feature can be enabled by 'touch .ostree-bootcsumdir-source'
in /usr/lib/ostree-boot.
Changes originally taken from https://github.com/OverC/meta-overc, but
updated to be aligned with the current ostree revision used by lmp.
> base: ostree: add patches to support ostree-boot files

- meta-lmp-base/classes/kernel-lmp-fitimage.bbclass
- meta-lmp-base/recipes-core/images/initramfs-ostree-lmp-recovery.bb
- meta-lmp-base/recipes-core/initrdscripts/initramfs-framework/ostree_recovery
- meta-lmp-base/recipes-core/initrdscripts/initramfs-framework_%.bbappend
- meta-lmp-base/recipes-extended/ostree/ostree/0001-Allow-updating-files-in-the-boot-directory.patch
- meta-lmp-base/recipes-extended/ostree/ostree/0002-u-boot-add-bootdir-to-the-generated-uEnv.txt.patch
- meta-lmp-base/recipes-extended/ostree/ostree/update-default-grub-cfg-header.patch
- meta-lmp-base/recipes-samples/images/lmp-image-common.inc
- meta-lmp-base/recipes-sota/ostree-kernel-initramfs/ostree-kernel-initramfs_%.bbappend
- meta-lmp-bsp/recipes-bsp/u-boot/u-boot-fio/qemuarm64/lmp.cfg
- meta-lmp-bsp/recipes-bsp/u-boot/u-boot-ostree-scr-fit/qemuarm64/boot.cmd
Patch-set to add an initial support for a generic recovery image in LmP.
The idea is to offer a way for the user to build a custom initrd (separated fit when fitImage is used) that can behave as recovery (for restoring the system, performing firmware updates, etc).
Not enabled by default but the user can add by simply defining INITRAMFS_RECOVERY_IMAGE with the recovery intramfs image (e.g. initramfs-ostree-lmp-recovery).
Can be easily tested with qemuarm64-secureboot, by booting the target, running `fw_setenv recovery 1` and rebooting it again. There is currently no automatic way to identify when to set recovery as this can be specific to the hardware, and we can't necessarily use bootcount as this will stress the storage device (as a write will happen on every boot, even when there is no …
> Initial support for a generic recovery image

- meta-lmp-base/classes/lmp.bbclass
- meta-lmp-base/conf/distro/lmp.conf
- meta-lmp-base/recipes-sota/ostree-kernel-initramfs/ostree-kernel-initramfs_%.bbappend
Make the trigger to enable ostree deploy copying content from
/usr/lib/ostree-boot a generic configuration, as then the user can
enable in a more generic fashion.
> Add generic config option for ostree-bootcsumdir-source

- meta-lmp-base/recipes-security/optee/optee-os-fio_3.17.0.bb
- 9fed2c40b [FIO toup] core: imx: enable IMX_SNVS on MX8MP
- 1e96d41d4 [FIO fromtree] drivers: imx_snvs: fix the is_otpmk_valid() logic
- 86eb07ac5 [FIO fromtree] drivers: imx_snvs: fix SNVS register read operation
- de8e54538 [FIO fromtree] drivers: imx_snvs: use snvs_is_device_closed() for RPMB key status
- d8f2772c3 [FIO fromtree] drivers: caam: set OTP as master key
- 5bb285a0a [FIO fromtree] plat: imx: enable SNVS driver by default
- 3699e1418 [FIO fromtree] drivers: imx_snvs: fix SNVS_SSM_MODE_SECURE value
- 363119a90 [FIO fromtree] drivers: imx_snvs: fix SNVS security configuration values
- 02d51963e [FIO fromtree] drivers: imx_snvs: add master key selection
- e2d58048e [FIO fromtree] core: imx8m: add SNVS_SIZE value
- 11716cd17 [FIO fromtree] plat: imx7: add …
> base: optee-os-fio: 3.17: bump to 9fed2c40b

- meta-lmp-bsp/recipes-kernel/linux/linux-lmp-xlnx_git.bb
Includes latest from the 2022.1 Xilinx BSP release.
> bsp: linux-lmp-xlnx: update to v5.15.36

- meta-lmp-base/classes/archiver.bbclass
Add temporarily the archiver.bbclass from git rev cb8647c089
When [1] is merged upstream we can revert this.
[1] https://lists.openembedded.org/g/openembedded-core/message/166784
```
4edc18f8 base: archiver: avoid race conditions when using multiconfig and sharing the same TMPDIR
a8ff21f4 base: add archiver.bbclass from yocto-4.0.1
```
> archiver: avoid race conditions when using multiconfig and sharing the same TMPDIR

- meta-lmp-base/recipes-bsp/gnu-efi/gnu-efi_3.0.14.bbappend
The 3.0.14 release already includes support for riscv64.
Upstream patch:
https://lists.openembedded.org/g/openembedded-core/message/166809
> base: gnu-efi: enable for riscv64

- meta-lmp-base/classes/kernel-lmp-efi.bbclass
- meta-lmp-base/classes/lmp.bbclass
- meta-lmp-base/recipes-core/systemd/systemd-boot_%.bbappend
- meta-lmp-bsp/conf/machine/include/lmp-machine-custom.inc
Add logic to sign both systemd-boot and kernel, for adding initial support for UEFI secure boot.
This is not yet using the unified EFI format, which will implemented later.
> Support for UEFI Secure Boot

- meta-lmp-base/recipes-samples/images/lmp-feature-optee.inc
Currently the lmp-feature-optee includes optee-fiovb but that should
only be enabled if there is an RPMB available (i.e. secured).
> recipes-samples: lmp-feature-optee fiovb is set with separate feature

- meta-lmp-base/recipes-samples/images/lmp-feature-optee.inc
- meta-lmp-base/recipes-security/optee/optee-os-tadevkit_3.17.0.bb
Fix compatibility issues when setting:
PREFERRED_PROVIDER_virtual/optee-os ?= "optee-os"
> base: security: optee: allow upstream optee-os as preferred provider

- meta-lmp-base/recipes-containers/docker-compose/docker-compose_2.6.0.bb
What's changed in 2.6.0:
* fix TestLocalComposeUp which fail locally and bump compose-go to 1.2.7
* attach only to services declared by project applying profiles
* Add ddev's e2e test
* Fix local run of make e2e-compose-standalone
* fix: prevent flickering prompt when pulling same image from N services
* add tags property to build section
* update golang version to 1.18
* bump compose-go to 1.2.6
* add e2e tests to verify env variables priority
* Import dotenv file to os environment
What's changed in 2.5.1:
* Fix relative paths on envfile label
* down: Reject all arguments
* Clarify what default work dir is when multiple compose files
* compose down exit=0 if nothing to remove
* cp command: copy to all containers of a service as default behaviour
* Fix extra space printed with …
> base: docker-compose: update to 2.6.0

- meta-lmp-base/files/lmp-group-table
- meta-lmp-base/files/lmp-passwd-table
> base: lmp-passwd/group: add ntp user and group

- meta-lmp-bsp/recipes-kernel/kernel-modules/kernel-module-nxp89xx_git.bb
This fixes the mlan/moal driver loading and wifi support on imx8mm-lpddr4-evk.
> bsp: kernel: modules: nxp89xx: skip debug split

- meta-lmp-base/recipes-core/systemd/systemd_%.bbappend
Systemd cannot build with gnu-efi support when support for efi is not
enabled, so make it depend on it.
> base: systemd: only enable gnu-efi when efi is available

- meta-lmp-base/recipes-bsp/plug-and-trust-seteec/plug-and-trust-seteec_3.3.0.bb
- meta-lmp-base/recipes-devtools/python/python3-plug-and-trust-ssscli_3.3.0.bb
Missing plug-and-trust-seteec bump after https://github.com/foundriesio/plug-and-trust-seteec/pull/2 is merged.
> Fix se05x support

- meta-lmp-bsp/conf/machine/include/lmp-machine-custom.inc
The wic image depends on do_deploy from efitools that provides the LockDown.efi
```
| DEBUG: Executing shell function do_image_wic
| INFO: Creating image(s)...
|
| ERROR: _exec_cmd: install -m 0644 -D /srv/oe/build/deploy/images/intel-corei7-64/LockDown.efi /srv/oe/build/tmp-lmp/work/intel_corei7_64-lmp-linux/lmp-factory-image/1.0-r0/tmp-wic/hdd/boot/LockDown.efi returned '1' instead of 0
| output: install: cannot stat '/srv/oe/build/deploy/images/intel-corei7-64/LockDown.efi': No such file or directory
|
| WARNING: exit code 1 from a shell command.
| INFO: recipe lmp-factory-image-1.0-r0: task do_image_wic: Failed
| ERROR: Task (/srv/oe/build/conf/../../layers/meta-subscriber-overrides/recipes-samples/images/lmp-factory-image.bb:do_image_wic) failed with exit code '1'
```
Signed-off-by: …
> bsp: lmp-machine-custom: intel: add efitools to WKS_FILE_DEPENDS 

- meta-lmp-base/recipes-kernel/linux/kmeta-linux-lmp-5.10.y.inc
- cf3fa2a bsp: ti: Add standard for am62xx-evm
> base: kmeta-linux-lmp-5.10.y: bump to cf3fa2a

- meta-lmp-base/recipes-sota/aktualizr/aktualizr_%.bbappend
- meta-lmp-base/recipes-support/compose-apps-early-start/compose-apps-early-start.bb
- meta-lmp-base/recipes-support/compose-apps-early-start/compose-apps-early-start/compose-apps-early-start
- meta-lmp-base/recipes-support/compose-apps-early-start/compose-apps-early-start/compose-apps-early-start-recovery
- meta-lmp-base/recipes-support/compose-apps-early-start/compose-apps-early-start/compose-apps-register-images.service
Add early App startup for preloaded *Restorable* Apps.
1. One-shot systemd service aimed to populate the dockerd repository with Registry referencies of the preloaded Apps' images. It makes `dockerd` avoid making any call to Registries during Apps startup.
2. Adjust existing one-shot systemd service that does Apps early start in such a way that it can start both type of Apps, *restorable* and *compose*.
> Early startup for oe builtin preloaded apps

- meta-lmp-base/recipes-security/optee/optee-os-fio_3.17.0.bb
- b2b258efe [FIO fromtree] drivers: imx: dcp: disable the use of UNIQUE KEY after HUK generation
- dca14164c [FIO fromtree] drivers: imx: dcp: clear OTP_KEY bit for unique key selection
- 4100c4aba [FIO fromtree] drivers: imx: dcp: workaround DCP errata 051292
- 987e21245 Revert "[FIO toup] drivers: dcp: fix HUK support"
- b943189fa [FIO toup] imx_ocotp: correct ocotp fuse address computation
> base: optee-os-fio: 3.17: bump to b2b258efe

- meta-lmp-base/recipes-sota/lmp-device-register/lmp-device-register_git.bb
- 959126a main: use engines from openssl 3 by default
> base: lmp-device-register: bump to 959126a

- meta-lmp-base/recipes-sota/aktualizr/aktualizr_%.bbappend
Due switch to OpenSSL 3 (>= kirkstone), the pkcs11 engine path needs
to be changed to follow the correct version id.
Upstream meta-updater PR:
https://github.com/uptane/meta-updater/pull/43
> base: aktualizr: use updated pkcs11 engines path for openssl 3

- meta-lmp-bsp/dynamic-layers/xilinx/recipes-bsp/u-boot/u-boot-xlnx_2022.01.bb
- 071696ff7ce fpga: zynqmp: support loading encrypted bitfiles
- dcf2c6b6d2b fpga: zynqmp: support loading authenticated images
- 67301a8f09a fpga: zynqmp: add bitstream compatible checking
- 8a592b8252c fpga: zynqmp: optimize zynqmppl_load() code
- d6465d67c10 fpga: xilinx: pass compatible flags to load() callback
- 387fe4404a7 spl: fit: pass real compatible flags to fpga_load()
- d08510a0f89 fpga: pass compatible flags to fpga_load()
- 162ed3404dd fpga: xilinx: pass compatible flags to xilinx_load()
- 50c9fee97ba fpga: add fpga_compatible2flag
- c8dce324a45 fpga: zynqmp: add str2flags call
- 8f3db2c3f48 fpga: xilinx: add bitstream flags to driver desc
- 4d1a011034f fpga: xilinx: add missed identifier names
- 715b08d3703 Revert "[FIO toup] cmd: fpga: Separating the …
> bsp: u-boot-xlnx: 2022.01: bump to 071696ff7ce

- meta-lmp-base/recipes-sota/aktualizr/aktualizr_%.bbappend
- 632b6c1 aklite-apps: Set deps on `c++17` explicitly
- fafa4d1 Use clang by default in dev and test env
> base: recipe-sota: aktualizr-lite: bump to 632b6c1

- meta-lmp-bsp/dynamic-layers/xilinx/recipes-bsp/u-boot/u-boot-xlnx_2022.01.bb
- b175231f4b1 fpga: zynqmp: fix handling legacy image
> bsp: u-boot-xlnx: 2022.01: bump to b175231f4b1

- meta-lmp-base/recipes-samples/images/lmp-feature-docker.inc
Fix the following When running do_rootfs task twice: bitbake lmp-factory-image -c do_rootfs
| ERROR: lmp-factory-image-1.0-r0 do_rootfs: lmp-factory-image: usermod command did not succeed.
| ERROR: lmp-factory-image-1.0-r0 do_rootfs: ExecutionError('/build/tmp-lmp/work/intel_corei7_64-lmp-linux/lmp-factory-image/1.0-r0/temp/run.set_user_group.249799', 1, None, None)
| ERROR: Logfile of failure stored in: /build/tmp-lmp/work/intel_corei7_64-lmp-linux/lmp-factory-image/1.0-r0/temp/log.do_rootfs.249799
| ERROR: Task (/build/conf/../../layers/meta-subscriber-overrides/recipes-samples/images/lmp-factory-image.bb:do_rootfs) failed with exit code '1'
Analyzing the log gives:
| NOTE: lmp-factory-image: Performing usermod with [-R /build/tmp-lmp/work/intel_corei7_64-lmp-linux/lmp-factory-image/1.0- …
> base: lmp-feature-docker: create docker group before adding users to them

- meta-lmp-base/recipes-kernel/wireguard/wireguard-tools_%.bbappend
SPDX data requires all runtime dependencies to be updated in order to
reflect the correct json files, and as it is depending on a kernel
module recipe (wireguard-module), we need to force nostamp for
create_runtime_spdx otherwise it will be ignored due sstate cache
filtering (siggen).
This can be reverted once the correct fix lands upstream.
For more information:
https://www.yoctoproject.org/irc/%23yocto.2022-07-06.log.html#t2022-07-06T20:25:15
> base: wireguard-tools: add nostamp for create_runtime_spdx

- meta-lmp-base/conf/distro/include/lmp.inc
We use signed kernel modules by default, so enable openssl support in
kmod in order for it to be able to provide details about the signature
at runtime.
> base: lmp: kmod: add openssl to PACKAGECONFIG

- meta-lmp-base/conf/distro/include/lmp.inc
- meta-lmp-bsp/recipes-kernel/kernel-modules/kernel-module-nxp89xx_git.bb
This is to fix the module not signed issue we noticed on imx8mm evk (wifi module is external).
This was caused by a race condition during the rm_work step, which erased the sysroot for make-mod-scripts, causing sign-file to error out due missing openssl library.
> Fixes for the external kernel modules signing issue

- meta-lmp-base/recipes-containers/docker/python3-docker-vxcan_1.0.2.bb
- 54e218b fix application routing for '/NetworkDriver.EndpointOperInfo'
> base: python3-docker-vxcan: bump to 54e218b

- meta-lmp-bsp/dynamic-layers/freescale-layer/recipes-graphics/imx-gpu-g2d/imx-gpu-g2d_%.bbappend
It appears that there is no longer any files being installed
in the /opt directory.
This reverts commit 444e446e607ba4fae211c5b5512916654f079734.
> Revert "bsp: imx-gpu-g2d: install samples at datadir instead of opt"

- meta-lmp-base/recipes-bsp/u-boot/u-boot-ostree-scr-fit/boot-common-alternative.cmd.in
- meta-lmp-base/recipes-bsp/u-boot/u-boot-ostree-scr-fit/boot-common.cmd.in
Use rootpart env variable instead of hardcoded partition id in the
script for obtaining bootfirmware_version.
> u-boot-ostree-scr-fit: specify root partition id for obtaining version

- meta-lmp-base/recipes-core/initrdscripts/initramfs-framework/run-tmpfs.patch
Refresh patch based on latest oe-core master/kirkstone.
> base: initramfs-framework: refresh run-tmpfs.patch

- meta-lmp-bsp/conf/machine/include/lmp-machine-custom.inc
boot.itb is only available on sota builds.
> bsp: lmp-machine-custom: stm32mp15-disco: add boot.itb only with sota

- meta-lmp-base/conf/distro/include/lmp.inc
Changes from meta-st-stm32mp for busybox and libdrm are not needed.
Libdrm also contaminates other targets, and can be reverted once
https://github.com/STMicroelectronics/meta-st-stm32mp/pull/37 gets
acceted upstream.
> base: lmp: add BBMASK for meta-st-stm32mp kirkstone

- meta-lmp-base/conf/distro/lmp-wayland.conf
- meta-lmp-base/conf/distro/lmp-xwayland.conf
Have both opengl and vulkan enabled by default on wayland/xwayland
builds.
> base: wayland/xwayland: add vulkan to DISTRO_FEATURES

- meta-lmp-bsp/recipes-kernel/linux-firmware/linux-firmware_%.bbappend
Latest firmware with latest kernel won't work with the default settings,
but it is fully functional after switching to EXT_LPO_ISCLOCK (using the
external LPO as clock - 32kHz).
> bsp: linux-firmware: stm32: fix brcmfmac43430-sdio.txt

- meta-lmp-base/recipes-samples/images/lmp-image-common.inc
Install i2c-tools package by default for all images, as this likely to
be used on all platforms when debugging/testing SE05X security chips.
> base: images: install i2c-tools package

- meta-lmp-base/recipes-support/resize-helper/resize-helper/resize-helper
on gpt partitions there is a tag that is removed when fdisk
removes the partition.
Therefore of there is a PART_ENTRY_NAME use sgdisk to put it
back after partition has been updated.
> recipe-support: resize-helper needs to preserve PART_ENTRY_NAME

- meta-lmp-base/recipes-support/resize-helper/resize-helper/resize-helper
> base: resize-helper fix error exit when no PART_ENTRY_NAME exists

- meta-lmp-base/recipes-sota/aktualizr/aktualizr_%.bbappend
- Add `aklite-offline` command to the aktualizr-lite package if `aklite-offline` feature is enabled/added to the package config.
- Bump aklite version that supports an offline update.
> base: recipes-sota: Add aklite offline update cmd

- meta-lmp-base/recipes-support/lmp-el2go-auto-register/lmp-el2go-auto-register.bb
- meta-lmp-base/recipes-support/lmp-el2go-auto-register/lmp-el2go-auto-register/lmp-el2go-auto-register
- meta-lmp-base/recipes-support/lmp-el2go-auto-register/lmp-el2go-auto-register/lmp-el2go-auto-register.service
This recipe requires a factory with Edgelock2GO enabled and
meta-subscriber-overrides additions for default.env and root.crt
> Add new recipe to for Edgelock2GO auto registration

- meta-lmp-base/classes/lmp.bbclass
- meta-lmp-base/recipes-sota/aktualizr/aktualizr_%.bbappend
Fetch and store root metadata on an ostree-based rootfs during bitbaking.
> base: lmp: provision TUF root metadata

- meta-lmp-base/recipes-kernel/linux/linux-lmp.inc
- meta-lmp-bsp/dynamic-layers/freescale-layer/recipes-kernel/kernel-modules/kernel-module-nxp89xx_git.bbappend
- Revert "base: linux-lmp: skip debug split with modsign"
- bsp: kernel: modules: nxp89xx: inherit the kernel-modsign
> drop the use of INHIBIT_PACKAGE_DEBUG_SPLIT for kernel modsign

- meta-lmp-base/classes/create-spdx.bbclass
- base: add create-spdx.bbclass from yocto-4.0.2
```
Add temporarily the create-spdx.bbclass from git rev a4bfb5ce
When [1] is merged upstream we can revert this.
[1] https://lists.openembedded.org/g/openembedded-core/message/168773
```
- create-spdx: ignore packing control files from ipk and deb
```
Otherwise spdx can have references for data that is not packed
in the package delivered because this contol data is temporarly
and only exist while the package is been write.
During do_package_write_ipk task in do_package_ipk the control
files is cleaned up at the end. This can create a race condiction
when the do_create_spdx task runs the add_package_files function
and these files is been deleted at same time in the
task …
```
>  create-spdx: avoid race conditions caused when ipk packages is written

- meta-lmp-base/recipes-kernel/wireguard/wireguard-tools_%.bbappend
This reverts commit eb6758553b97559b0c156d5db9d63bc6b4507465.
Correct fix now available in kirkstone oe-core
(7549429fc93218dee33b216010b2c36a9f814091).
> Revert "base: wireguard-tools: add nostamp for create_runtime_spdx"

- meta-lmp-base/conf/distro/include/lmp.inc
- meta-lmp-base/recipes-core/initrdscripts/initramfs-framework/rootfs
- meta-lmp-base/recipes-core/systemd/systemd_%.bbappend
- meta-lmp-base/recipes-security/optee/optee-client-fio.inc
- meta-lmp-base/recipes-security/optee/optee-client/ckteec.module
- meta-lmp-base/recipes-support/resize-helper/resize-helper/resize-helper
Separating the most common and non breaking changes from https://github.com/foundriesio/meta-lmp/pull/732 in order to facilitate the review and landing.
> Non breaking changes for cryptsetup

- meta-lmp-bsp/recipes-support/mfgtool-files/mfgtool-files/apalis-imx6-sec/full_image.uuu.in
- meta-lmp-bsp/recipes-support/mfgtool-files/mfgtool-files/apalis-imx8-sec/full_image.uuu.in
- meta-lmp-bsp/recipes-support/mfgtool-files/mfgtool-files/imx8mm-lpddr4-evk-sec/full_image.uuu.in
- meta-lmp-bsp/recipes-support/mfgtool-files/mfgtool-files/imx8mp-lpddr4-evk-sec/full_image.uuu.in
delete_pvalue can fail when there is no previous value for such
variable, stopping the flashing process entirely (e.g. new boards).
Fix by simply returning true without checking the return value for
delete_pvalue.
> bsp: mfgtool-files: imx: improve fiovb delete handling

- meta-lmp-bsp/dynamic-layers/freescale-layer/recipes-kernel/kernel-modules/kernel-module-imx-gpu-viv_6.4.3.p2.4.bbappend
Make sure to explicitly depend on virtual/kernel in order to link the
spdx chain correctly and avoid broken task dependencies.
> bsp: kernel-module-imx-gpu-viv: depend on virtual/kernel

- meta-lmp-base/recipes-security/optee/optee-fio.inc
Since OP-TEE 3.16.0 we can leverage CFLAGS32/64 for setting sysroot
option, reducing the need for a custom option and custom patches.
> base: optee-fio: use CFLAGS{32,64} to pass --sysroot

- meta-lmp-base/dynamic-layers/tpm-layer/recipes-tpm2/tpm2-abrmd/tpm2-abrmd_%.bbappend
- meta-lmp-base/recipes-core/ovmf/ovmf_git.bbappend
- meta-lmp-bsp/conf/machine/include/lmp-machine-custom.inc
Base changes should be sent upstream as well, but need to check when we get a master-next that is functional as the base versions are not the same.
> Fix basic support for intel + TPM2

- meta-lmp-base/dynamic-layers/tpm-layer/recipes-tpm2/tpm2-pkcs11/tpm2-pkcs11/tmpfiles.conf
- meta-lmp-base/dynamic-layers/tpm-layer/recipes-tpm2/tpm2-pkcs11/tpm2-pkcs11_%.bbappend
Upstream uses /etc/tpm2-pkcs11 by default, which is not really ideal (as
the default location for the store sqlite databse), so set to
/var/tpm2_pkcs11 instead, and create the respective tmpfiles logic in
order for the system to create the required dir during boot.
> base: tpm2-pkcs11: set default storedir to /var/tpm2_pkcs11

- meta-lmp-base/recipes-sota/aktualizr/aktualizr_%.bbappend
- 9c2277b aklite: Send Apps status only if changed
- b4c4365 api: Send Apps status at checkin
- dd06811 aklite: Adjust to the latest changes to libaktualizr
- 76d51a9 docker: Switch to clang-* v11
- b08f0a4 aklite: Switch to libaktualizr 2022.7+fio
> base: recipe-sota: aktualizr-lite: bump to 9c2277b

- meta-lmp-base/recipes-support/mfgtool-files/mfgtool-files_0.1.bb
**This PR must be merged before switching any NXP boards to u-boot 2022.* - the older uuu won't work with the new USB uids.**
Update UUU release to 1.4.193, introducing required for new u-boot
versions support of new NXP device PID.
New features:
* Add NXP FB/FBK/SDPV device PID
Bug fixes:
* Fixed 314 Corrupt image with larger transfer sizes at sdp(s)
* Fixed missed true at else branch at built-in fat_write script and nand_burn_loader
* Fixed invalid progress percentage in verbose mode
* Fixed QSPI flashing script
* Fix #297 print error when run quit cmd in shell mode
* Fix #180 support check getval return value
> base: mfgtool-files: update UUU 1.4.139 -> 1.4.193

- meta-lmp-base/recipes-core/systemd/systemd_%.bbappend
Systemd expects to install the systemd-boot files under /usr/lib, so use
nonarch_libdir instead of nonarch_base_libdir in order to be compatible
with builds that are not using usrmerge.
> base: systemd: use nonarch_libdir instead of nonarch_base_libdir

- meta-lmp-bsp/dynamic-layers/xilinx/recipes-bsp/arm-trusted-firmware/arm-trusted-firmware/plat-versal-support-raw-bin.patch
- meta-lmp-bsp/dynamic-layers/xilinx/recipes-bsp/arm-trusted-firmware/arm-trusted-firmware_2022.1.bbappend
Add patch that adds adds support for BL32 TEE-RAW.BIN by
defaulting to built-time addresses when FSBL fails at providing
a valid jump address.
> bsp: arm-trusted-firmware: versal: support raw.bin

- meta-lmp-bsp/conf/machine/kv260.conf
SOM has infineon slb9670 by default.
> bsp: kv260: add tpm2 in MACHINE_FEATURES

- meta-lmp-base/recipes-containers/nerdctl/nerdctl/cli-config-support-default-system-config.patch
- meta-lmp-base/recipes-containers/nerdctl/nerdctl_git.bbappend
base: rc: nerdctl: Patch docker/cli to set a def conf path
- Patch docker/cli module before compiling nerdctl so it uses
docker config file `/usr/lib/docker/config.json` for auth by default.
A use may override it by setting DOCKER_CONFIG to refer to their
config directory.
> Patch docker config for nerdctl

- meta-lmp-base/recipes-support/bluetooth-attach/bluetooth-attach_0.1.bb
The default empty file can easily be overridden for special machines
by adding a .bbappend in the appropriate layer (meta-lmp-bsp or
meta-subscriber).
> base: support: add default btattach.conf to bluetooth-attach service

- meta-lmp-base/recipes-bsp/u-boot/u-boot-fio-common.inc
- meta-lmp-base/recipes-bsp/u-boot/u-boot-fio-mfgtool_imx-2022.04.bb
- meta-lmp-base/recipes-bsp/u-boot/u-boot-fio_imx-2022.04.bb
Prepare recipes for enabling u-boot imx-2022.04 for imx boards.
Reduce the PR to only adding the u-boot imx-2022.04 support without switching boards to use it.
There will be other PRs for switching boards to this u-boot as long as they are ready.
> Add support of u-boot imx 2022.04

- meta-lmp-base/recipes-bsp/u-boot/u-boot-fio_imx-2022.04.bb
Fix the hash of HEAD commit cede8a4f144 ("[FIO internal] ARM: mach-imx: spl: add support of imx8mn_evk in spl_mmc_get_uboot_raw_sector()").
Fixes: a02692f3 ("base: u-boot-fio: add recipe for imx-2022.04")
> base: u-boot-fio: imx-2022.04: fix commit hash

- meta-lmp-base/recipes-bsp/u-boot/u-boot-fio_imx-2022.04.bb
Add DEFAULT_PREFERENCE = -1, so recipe is not built by default.
> base: u-boot: u-boot-fio_imx-2022.04 decrease preference

- meta-lmp-base/conf/distro/include/lmp.inc
We use signed kernel modules by default, so enable openssl support in
kmod-native to facilitate debugging with devshell
> base: lmp: kmod-native: add openssl to PACKAGECONFIG

- meta-lmp-base/recipes-bsp/plug-and-trust-seteec/plug-and-trust-seteec_3.3.0.bb
- meta-lmp-base/recipes-support/lmp-el2go-auto-register/lmp-el2go-auto-register/lmp-el2go-auto-register
Fix libckteec.so.0 library name and update plug-and-trust-seteec to reduce the need for a custom config (in order to get it to work without major changes with openssl 3).
> Fix plug-and-trust-seteec and el2go-auto-register

- meta-lmp-base/recipes-bsp/lmp-boot-firmware/lmp-boot-firmware.bb
> base: lmp-boot-firmware: abort when LMP_BOOT_FIRMWARE_FILES not found

- meta-lmp-base/recipes-containers/nerdctl/nerdctl/0001-extend-ps-output.patch
- meta-lmp-base/recipes-containers/nerdctl/nerdctl_git.bbappend
- meta-lmp-base/recipes-sota/aktualizr/aktualizr_%.bbappend
- Patch `nerdctl` to extend `ps` output with more details about container state.
- Add PACKAGECONFIG to turn ON/OFF `nerdctl` in aklite.
- Bump `aklite` version that supports `nerdctl`.
> Enable nerdctl in LmP and aklite

- meta-lmp-base/recipes-devtools/python/python3-plug-and-trust-ssscli_3.3.0.bb
- 6c67941 cli: drop external dependency for func_timeout
Also drop rdepends on func_timeout as it is not required anymore.
> base: python3-plug-and-trust-ssscli: bump to 6c67941

- meta-lmp-bsp/recipes-kernel/linux/linux-lmp-ti-staging/am62xx-evm/tiL5.10-P-1-1-arm64-dts-ti-k3-am625-sk-fix-wlan_en.patch
- meta-lmp-bsp/recipes-kernel/linux/linux-lmp-ti-staging_git.bb
> [fromup] recipes-kernel: correct wifi startup on am62xx

- meta-lmp-base/conf/distro/include/non-clangable.inc
- base: lmp: non-clangable: add trusted-firmware-a used in am6xxx
- base: lmp: non-clangable: add tf-a-fio used in stm32mp1
> non clangable: add new bsp packages

- meta-lmp-base/recipes-security/optee/optee-os-fio_3.18.0.bb
- 6467bb295 [FIO toup] versal: authenc: fix PLM DMA timeout
> base: optee-os-fio: 3.18: bump to 6467bb295

- meta-lmp-base/recipes-extended/ostree/ostree_%.bbappend
fixup for https://github.com/foundriesio/meta-lmp/commit/0abb08c83aee7027711f538e29a5ff16dc334304 `pn-PACKAGE` override is usufull in global variables not in local
> base: ostree: fix the clang override

- meta-lmp-base/recipes-sota/aktualizr/aktualizr_%.bbappend
- 2c9db75 reportqueue: Catch exceptions while loading events from DB
- b847a9f aklite-offline: Add param to tune a docker client
- 4ab5400 rootfstreemanager: make sure to call updateNotify and installNotify
> base: recipe-sota: aktualizr-lite: bump to 4ab5400

- meta-lmp-base/recipes-connectivity/openssh/openssh_%.bbappend
- meta-lmp-bsp/recipes-connectivity/openssh/openssh_%.bbappend
Since kernel 5.6 reading /dev/random does not block anymore, and CRNG
(initialized by the kernel during boot) is considered to be good enough
for userspace, so no need for having rng-tools seeding entropy.
This is not done with a remove override as we still want to allow BSP
layers (or via meta-lmp-bsp) to be able to add rng-tools when needed
(e.g. kernel older than 5.6, as done with tegra and apalis-imx8).
> base/bsp: openssh: drop rng-tools from default PACKAGECONFIG

- meta-lmp-base/conf/distro/include/lmp.inc
Bbappend disables support for GCC plugins for stm32mpcommon, which is
not really needed.
> base: lmp: bbmask meta-st-stm32mp make-mod-scripts bbappend

- meta-lmp-base/recipes-connectivity/openssh/openssh/sshd_check_keys
- meta-lmp-base/recipes-connectivity/openssh/openssh_%.bbappend
Change default script from oe-core to only generate ECDSA and ED25519 keys by default, which are both a lot faster to generate and to use.
> openssh: do not generate rsa keys by default 

- meta-lmp-base/recipes-security/optee/optee-os-fio_3.18.0.bb
- 939fb9c74 [FIO toup] crypto: versal: fix memory access after free
> base: optee-os-fio: 3.18: bump to 939fb9c74

- meta-lmp-base/conf/distro/include/lmp.inc
base: lmp: build with clang toolchain by default
For recipes that doesn't build we can go back to gcc toolchain
with TOOLCHAIN:pn-recipes = "gcc" in main local.conf or
TOOLCHAIN = "gcc" on himself in a bbappend
Depends on https://github.com/foundriesio/meta-lmp/pull/705
> build with clang toolchain by default

- meta-lmp-base/conf/distro/include/non-clangable.inc
> base: lmp: non-clangable: add optee-os-fio-mfgtool

- meta-lmp-base/conf/distro/include/non-clangable.inc
Build is not reproducible, causing the binary hash to change at every clean build (and causing unexpected boot firmware updates).
> base: lmp: non-clangable: add imx-atf

- meta-lmp-base/files/lmp-group-table
Required by the cups recipe.
| ERROR: Nothing PROVIDES 'cups' (but layers/meta-openembedded/meta-oe/recipes-support/freerdp/freerdp_2.8.0.bb DEPENDS on or otherwise requires it) | cups was skipped: cups - cups: system groupname lpadmin does not have a static ID defined. Add lpadmin to one of these files: layers/meta-lmp/meta-lmp-base/files/lmp-group-table
> base: lmp-passwd/group: add lpadmin group

- meta-lmp-base/recipes-bsp/lmp-boot-firmware/lmp-boot-firmware.bb
When the bootfirmware_version is not fixed by PV, the length of bootfirmware_version depends on the number of files passed in LMP_BOOT_FIRMWARE_FILES
Having a variable length is no problem for u-boot env. With backend such as fiovb it is a problem because the storage size of the variable is fixed - 128b in the current boot-common.cmd.in.
Make a single md5sum out of the current bootfirmware_version content so keeps on changing if any of the files in LMP_BOOT_FIRMWARE_FILES changes and length does not exceed 128b.
> lmp-boot-firmware: limit bootfirmware_version length

- meta-lmp-base/recipes-core/images/initramfs-ostree-lmp-recovery/image_download.sh
Add missing "lmp" to URL in image_download.sh
> base: initramfs-ostree-lmp-recovery: Fix image_download.sh URL

- meta-lmp-bsp/conf/machine/include/lmp-machine-custom.inc
This fixes the error:
ERROR: Required build target 'lmp-factory-image' has no buildable providers.
Missing or unbuildable dependency chain was: ['lmp-factory-image', 'packagegroup-base-extended', 'bluetooth-attach-conf']
> bsp: imx8mn-ddr4-evk: fix bluetooth-attach package name

- meta-lmp-base/conf/distro/include/lmp.inc
- base: lmp: adds lmp mirrors to PREMIRRORS
As we have the PREMIRRORS assigned with ??= the Yocto mirrors takes precedence so ours is disabled, change that and adds our mirrors.
- base: lmp: keep lmp PREMIRRORS in sync with MIRRORS
> Use the lmp mirrors in PREMIRRORS and keep it in sync with MIRRORS

- meta-lmp-bsp/recipes-security/optee/optee-os-fio-bsp.inc
Enable CFG_WITH_NSEC_I2CS=y, so OP-TEE can use non-secure i2c buses.
> base: optee-os-fio: enable support for non-secure i2c buses

- meta-lmp-base/recipes-bsp/u-boot/u-boot-fio_imx-2022.04.bb
- 727d16723a6 [FIO toimx] usb: imx: mx6: fix building ehci-mx6 driver
- 113d21b4408 [FIO toup] mmc: spl: select SPL_BLK for SPL_DM_MMC
- e03d63fe4cb [FIO toup] spl: crypto: fix including object files of SHA* in SPL
- ab9772994bf [FIO squash] image-sig: fix disabling SHA1 with FIT_SIGNATURE_STRICT
- 22478f6591a [FIO toup] imx: mx6: spl: reduce BSS size
- 6f174fd7e5f [FIO toup] ARM: mach-imx: imx8ulp: Fix SPL_CRYPTO name
- f025258336c [FIO toup] usb: dwc3: Fix renaming SPL_USB_HOST_SUPPORT to SPL_USB_HOST
- ef3ed1ae6fd [FIO fromtree] net: nfs: Fix CVE-2022-30767 (old CVE-2019-14196)
- 099bb6d19c8 [FIO fromtree] zlib: Port fix for CVE-2018-25032 to U-Boot
- a4430a0515a [FIO fromtree] fs/squashfs: Use kcalloc when relevant
- f33505d8d43 [FIO fromtree] net: Check for the …
> base: u-boot-fio: imx-2022.04: bump to 727d16723a6

- meta-lmp-base/recipes-security/optee/files/se050_applet_version.patch
- meta-lmp-base/recipes-security/optee/optee-os-fio_3.18.0.bb
- bc34b5d9b [FIO fromlist] crypto: se050: updates to the crypto object deletion interface
- ca186acc5 [FIO fromtree] core: mmu: Fix wrong input argument of tee_mm_init()
- 87b59f2e1 [FIO fromtree] plat-stm32mp1: conf: fix tzdram default size when w/o rsv-shm
- d676cf4ca [FIO fromtree] drivers: imx-i2c: add support for imx8mn
- 3ca5eebd1 [FIO squash] arm: boot: fix adding new sub-nodes
- 143053347 [FIO internal] dts: stm32mp1: add i2c5 alias
- 67ddb833b [FIO internal] dts: stm32mp1: provide config properties for i2c5
- 2b03050a8 [FIO toup] stm32mp1: add support for i2c5 bus
- ec6d52e16 [FIO toup] plat-imx: fix subnodes for imx6ull
> base: optee-os-fio: 3.18: bump to bc34b5d9b

- meta-lmp-base/recipes-core/os-release/os-release.bbappend
We can't easily "abuse" IMAGE for knowing the image used when building LmP, so change IMAGE_ID to track LMP_FACTORY_IMAGE instead, which is configured in ci-scripts to the image that is built by the factory ci.
> base: os-release: use LMP_FACTORY_IMAGE for factory-based image

- meta-lmp-base/recipes-support/htpdate/htpdate/default.conf
- meta-lmp-base/recipes-support/htpdate/htpdate_1.3.6.bb
Taking latest from meta-oe/master (due required changes), enable support for systemd and also provide a default config.
Systemd support should be sent upstream as well, will do that after finalizing this pr.
> Add support for htpdate

- meta-lmp-base/classes/lmp-staging.bbclass
This is a work around to not compile rust and clang at same time as it is very huge tasks.
It uses the bitbake lockfiles to run the refered tasks one at a time. The bitbake UI can be misleading since it will inform you that the tasks are working at the same time, which is not true because only one is working and all the others are blocked.
I have a pending bitbake patch to improve this situation.
> lmp-staging: serialize do_compile of heavy tasks

- meta-lmp-base/recipes-security/optee/optee-os-fio-se05x.inc
Add the OEFID and disable RSA (unsupported by hardware)
> optee-os-fio-se05x: support SE050E

- meta-lmp-base/recipes-sota/aktualizr/aktualizr-pkcs11-label.bb
- meta-lmp-base/recipes-sota/aktualizr/aktualizr-pkcs11-label/pkcs11-label.toml
- meta-lmp-base/recipes-sota/aktualizr/aktualizr_%.bbappend
This patch will ensure backward compatibility for aktualizr deployments working with HSM modules. Currently aktualizr uses 1st available initialized token. With changes coming aktualizr will use the token with proper label.
Signed-off-by: Milosz Wasilewski <milosz.wasilewski@foundries.io>
> aktualizr: add default pkcs11 label to aktualizr config

- meta-lmp-base/recipes-core/ovmf/ovmf/0001-MdeModulePkg-NvmExpressDxe-fix-check-for-Cap.Css.patch
- meta-lmp-base/recipes-core/ovmf/ovmf/0002-MdeModulePkg-NvmExpressPei-fix-check-for-NVM-command.patch
- meta-lmp-base/recipes-core/ovmf/ovmf_git.bbappend
Backport patches already applied in main and latest edk2 stable in order to fix NVME usage with recent QEMU versions, as described at https://github.com/tianocore/edk2/pull/2637.
> base: ovmf: backport patches to fix nvm support with qemu

- meta-lmp-base/conf/distro/include/non-clangable.inc
- meta-lmp-bsp/conf/machine/include/lmp-machine-custom.inc
- meta-lmp-bsp/dynamic-layers/tegra/recipes-security/optee/optee-os_3.16.0-l4t-r35.1.0.bbappend
- meta-lmp-bsp/dynamic-layers/tegra/recipes-security/optee/optee-test_3.16.0-l4t-r35.1.0.bbappend
This also allows us to be compatible with latest meta-tegra changes.
> nvidia: enable optee-os from source (instead of pre-built)

- meta-lmp-base/recipes-core/ovmf/ovmf/0001-MdeModulePkg-NvmExpressDxe-fix-check-for-Cap.Css.patch
- meta-lmp-base/recipes-core/ovmf/ovmf/0002-MdeModulePkg-NvmExpressPei-fix-check-for-NVM-command.patch
Correct the patches with the expected line endings, otherwise bitbake fails to apply the changes.
Converted incorrectly when exporting the patches at the previous commit.
> base: ovmf: fix patches line endings

- meta-lmp-base/recipes-sota/aktualizr/aktualizr_%.bbappend
- e5bbb3a offline: Support update on dockerless systems
- 95f08e1 aktualizr: require pkcs11 token label
- 4679a05 appengine: Move pruning to an engine client impl
- e8b302f bootloader: Search bootloader version file in sysroot
- 13124a0 bootloader: Ignore failure of getting firmware ver
> base: recipes-sota: aktualizr-lite: bump to e5bbb3a

- meta-lmp-base/classes/archiver.bbclass
- meta-lmp-base/classes/lmp-staging.bbclass
This ones can be reverted when [1] is been merged
- base: Add archiver.bbclass git rev 2556d0bd 
- base: archiver.bbclass: avoid using machine variable as it breaks multiconfig
This is a work around not fixed yet
- base: lmp-staging: archiver multiconfig signature workaround
[1] https://lists.openembedded.org/g/openembedded-core/message/171736
> Archiver: multiconfig fixes for shared recipes

- meta-lmp-bsp/conf/machine/include/lmp-machine-custom.inc
- meta-lmp-bsp/recipes-kernel/linux-firmware/linux-firmware_%.bbappend
- meta-lmp-bsp/recipes-kernel/linux/linux-lmp-fslc-imx/imx8mm-lpddr4-evk/0001-FIO-toup-arm64-dts-imx8mm-evk-qca-wifi-enable-suppor.patch
- meta-lmp-bsp/recipes-kernel/linux/linux-lmp-fslc-imx_5.15_git.bb
* Bump linux-firmware imx to be aligned with current BSP release
* Fix kernel entrypoint for mx8mm
* Add bluetooth support for imx8mmevka
* Add qca firmware on imx8mm devices (for evka)
> Additional fixes for the NXP BSP

- meta-lmp-bsp/conf/machine/include/lmp-machine-custom.inc
No need to set preferred version for kernel-module-imx-gpu-viv as the one provided by the BSP is now newer.
> bsp: lmp-machine-custom: imx: drop preferred rev for imx-gpu-viv

- meta-lmp-base/conf/distro/include/lmp.inc
This also adds a dependencie BBLAYERS that rebuild many recipes from scracth when we cange the build dir.
> base: lmp: remove image-buildinfo as we don't use it anymore

- meta-lmp-base/recipes-core/images/core-image-minimal-initramfs.bbappend
- meta-lmp-base/recipes-core/images/initramfs-ostree-lmp-image.bb
- meta-lmp-base/recipes-core/os-release/os-release.bbappend
- base: core-image-minimal-initramfs: inherit nopackages
_This can be proposed upstream_
- base: initramfs-ostree-lmp-image: use a python anonimus to check IMAGE_FSTYPES
- base: core-image-minimal-initramfs: use the sstate for all task
_A better approach can be a new bbclass or inc with the bits used in initramfs_
- base: initramfs-ostree-lmp-image: use the sstate for all task
_A better approach can be a new bbclass or inc with the bits used in initramfs_
- base: lmp: remove image-buildinfo as we don't use it anymore
This PR improves the local build time a lot and building with more cache reduces the time to 25 minutes
`time bitbake lmp-base-console-image`
```
real    23m58.393s
user    0m25.023s
sys     0m17.533s
```
> Setscene fixes

- meta-lmp-base/recipes-core/base-files/base-files_%.bbappend
This is the only place on the layer this is used.
```
grep 'FILESEXTRAPATHS.*lmp' -r
```
> base-files: use FILESEXTRAPATHS without machine overrides

- meta-lmp-base/conf/distro/include/lmp.inc
Enable the archiver for every build to fix the SSTATETASKS chain.
The archiver is always enabled on the CI but locally not and this breaks the sstate-cache reuse.
This also fixes many rm_works issue where one of them is the following:
```
Task cpio:do_rm_work couldn't be used from the cache because:
We need hash a11151ed05614d9577893318e8b401bb5450cbdce002199fd3fc4128f21d273e, closest matching task was 8186adc8138c84e4d21eaeef053db0a0bea1c12e6fea2487d59833559ea76f57
basehash changed from 47a321369469543dff15da565f7460bf32bff0e724f063a39cf4e89745fdda5d to 5406e5d6dfd20699e09815b796e1172f952d695cd7697dcec8ae4059e81551a5
Variable SSTATETASKS value changed:
"do_create_runtime_spdx do_create_spdx [-do_deploy_archives-] do_deploy_source_date_epoch do_package do_package_qa do_package_write_ipk …
```
> Archiver: fix setscene locally 

- meta-lmp-base/conf/layer.conf
The recipe os-release only install a file on target so we cat exclude it from the siggen and avoid rebuild packages that releies on the files they provided by the os-release.
Currently one bigside effects of this issue is rebuilding systemd and consequently everything that depends on that.
A list of recipes that are completely stable and will never change. The ABI for the recipes in the list are presented by output from the tasks run to build the recipe. Use of this variable is one way to remove dependencies from one recipe on another that affect task signatures and thus force rebuilds when the recipe changes.
https://docs.yoctoproject.org/ref-manual/variables.html?highlight=siggen_exclude_safe_recipe_deps#term-SIGGEN_EXCLUDERECIPES_ABISAFE
Signed-off-by: Jose Quaresma …
> base: layer.conf: exclude os-release in the siggen as it is abisafe

- meta-lmp-base/recipes-samples/images/lmp-feature-debug.inc
Install dtc package by default for all images, as this likely to be used on all platforms for exporting device tree during debugging.
> base: images: install dtc package

- meta-lmp-base/recipes-containers/docker/files/daemon.json.in
This shows logging information with the container name as in: Nov 09 17:15:03 intel-corei7-64 shellhttpd-httpd-1[407]: Starting
> base: containers: log container name instead of container id

- meta-lmp-base/recipes-bsp/plug-and-trust-seteec/plug-and-trust-seteec_4.02.00.bb
- meta-lmp-base/recipes-security/optee/optee-os-fio-se05x.inc
There are two different OEFIDs for these HSMs.
They dont support unathenticated sessions so SCP03 must be enabled immediately during boot.
> optee-os-fio-se05x: support SE050F

- meta-lmp-base/classes/lmp-staging.bbclass
The var flag network only support a single argument.
> lmp-staging: fix network var flag usage

- meta-lmp-base/conf/distro/lmp-base.conf
- meta-lmp-base/recipes-samples/images/lmp-base-console-image.bb
The distro lmp-base is used usually for developing and debugging issues. Include a set of debug tools to this distro by default.
> base: lmp-base: include development debug tools

- meta-lmp-base/recipes-samples/images/lmp-feature-debug.inc
- meta-lmp-base/recipes-samples/images/lmp-image-common.inc
Move i2c-tools package to lmp-feature-debug, as it's mainly used for SE05x communication debugging.
> base: images: move i2c-tools to feature-debug

- meta-lmp-base/conf/distro/include/non-clangable.inc
- meta-lmp-base/recipes-devtools/mcumgr/mcumgr_git.bb
- base: mcumgr: bump 5c56bd
```
Changelog:
- chore: upgrade deps
- Merge pull request #26 from AudioStreamingPlatform/master
- Added LICENSE file
```
- base: mcumgr: relay only on go that uses goarch underline
```
grep -rn goarch openembedded-core/meta/classes/go.bbclass
openembedded-core/meta/classes/go.bbclass:1:inherit goarch
```
- base: non-clangable: add mcumgr
```
llvm-strip fails with:
ERROR: mcumgr-v0.0.1+git-r0 do_package: Fatal errors occurred in subprocesses:
Command '['x86_64-lmp-linux-llvm-strip', '--remove-section=.comment', '--remove-section=.note', '/srv/oe/build/tmp-lmp/work/corei7-64-lmp-linux/mcumgr/v0.0.1+git-r0/package/usr/bin/mcumgr']' returned non-zero exit status 1.
Subprocess output:x86_64-lmp-linux-llvm-strip: error: SHT_STRTAB string table section [index 9] is …
```
> mcumgr: fix build with clang and bump

- meta-lmp-base/recipes-bsp/u-boot/u-boot-ostree-scr-fit/boot-common-alternative.cmd.in
Print fiovb.is_secondary_boot when debug prints are enabled.
> base: u-boot-ostree-scr-fit: print fiovb.is_secondary_boot

- meta-lmp-base/recipes-security/optee/fio-se05x-cli_git.bb
Add --list-objects option to deprecate ssscli
> lmp-base: fio-se05x-cli: bump version

- meta-lmp-base/recipes-core/os-release/os-release.bbappend
This is a fixup for 96bc0769 os-release: set PACKAGE_ARCH machine dependent
To set the PACKAGE_ARCH we need to bypass the allarch_package_arch_handler from allarch.bbclass otherwise they will set the PACKAGE_ARCH=all regardless of what is defined elsewhere.
> os-release: bypass the allarch_package_arch_handler

- meta-lmp-base/recipes-support/mfgtool-files/mfgtool-files_0.1.bb
New features:
* Add zstd support
* Add iMX93 support
Bug fixes:
* Fixed random crash when download bz2 from http
* Fix crash when download speed slower than decompress speed and need resize buffer
> base: mfgtool-files: update UUU 1.4.193 -> 1.4.243

- meta-lmp-base/recipes-kernel/linux/kmeta-linux-lmp-5.15.y.inc
- 9ec0e7d2 bsp: stm32: remove features that don't exist on this chip
- e6acc158 bsp: stm32: merge disco and eval fragments
- 928422ae bsp: stm32: remove features that don't exist on this chip
> base: kmeta-linux-lmp-5.15.y: bump to 9ec0e7d2

- meta-lmp-base/recipes-security/optee/optee-os-fio.inc
Publish the final configuration used as part of the recipe build into the LmP deploy folder.
Having the conf.mk file published is quite useful when debugging configuration issues without having to build it locally.
> base: optee-os-fio: deploy build configuration

- meta-lmp-base/recipes-sota/lmp-device-register/lmp-device-register_git.bb
- ccd4499 Print log message of each error
> base: lmp-device-register: bump to ccd4499

- meta-lmp-base/conf/distro/lmp-base.conf
Otherwise is not possible to build lmp-base distro using intel-corei7-64 target machine.
```
ERROR: Nothing PROVIDES '${@'' (but /lmp/build/conf/../../layers/meta-lmp/meta-lmp-base/recipes-samples/images/lmp-base-console-image.bb DEPENDS on or otherwise requires it)
ERROR: Required build target 'lmp-base-console-image' has no buildable providers.
Missing or unbuildable dependency chain was: ['lmp-base-console-image', "${@'"]
```
> base: lmp-base: define INITRD_IMAGE_LIVE

- meta-lmp-base/recipes-samples/images/lmp-feature-se05x.inc
Include fio-se05x-cli as part of lmp-feature-se050x as that is the tool we're now maintaining.
> base: lmp-feature-se05x: include fio-se05x-cli

- meta-lmp-bsp/recipes-support/mfgtool-files/mfgtool-files/imx8qm-mek-sec/full_image.uuu.in
- meta-lmp-bsp/recipes-support/mfgtool-files/mfgtool-files/imx8qm-mek/bootloader.uuu.in
This was after trying and failing on real hardware.
This script successfully installs on a closed board provided that the dtb and u-boot config are correct.
> recipes-support: update full_image for imx8qm-mek-sec

- meta-lmp-bsp/recipes-security/optee/optee-os-fio-bsp.inc
Increase the ammount of heap on the PKCS#11 TA so we dont hit TA out of memory condition when creating keys on the secure element.
> bsp: optee-os-fio: imx8mm-lpddr4-evk with se05x

- meta-lmp-bsp/recipes-support/mfgtool-files/mfgtool-files/imx8qm-mek-sec/close.uuu
- meta-lmp-bsp/recipes-support/mfgtool-files/mfgtool-files/imx8qm-mek-sec/fuse.uuu
These values were taken from apalis-imx8 (toradex) and are not required for NXP-based boards.
> bsp: mfgtool-files: imx8qm-mek-sec: drop custom vendor id

- meta-lmp-bsp/dynamic-layers/freescale-layer/recipes-bsp/imx-sc-firmware/imx-sc-firmware-toradex_1.14.0.bb
Update imx-sc-firmware recipe to version 1.14.0, which corresponds to Linux 5.15.52_2.1.0 NXP BSP release.
> bsp: dynamic-layers: toradex: update imx-sc-firmware

- meta-lmp-base/recipes-bsp/u-boot/u-boot-fio_imx-2022.04.bb
- b4d62dc03a1 [FIO tosquash] imx8qm_mek: fix build issues for CONFIG_MMCROOT
> base: u-boot-fio: imx-2022.04: bump to b4d62dc03a1

- meta-lmp-base/recipes-bsp/u-boot/u-boot-fio_2022.04.bb
- 3b47abb216 [FIO internal] ARM: dts: stm32mp157c-ev1: add optee node
- 2fa8f7459f [FIO internal] ARM: dts: stm32mp157c-dk2: dm-pre-reloc for optee
- 9bb61a8858 [FIO squash] drivers: tee: i2c: fix format arguments size
- 6c259e2e23 [FIO internal] ARM: dts: stm32mp157c-dk2-u-boot: add optee node with rpmb dev
- 4c157f1b94 [FIO internal] fastboot: add oem ucmd for remote u-boot commands
> base: u-boot-fio: 2022.04: bump to 3b47abb216

- meta-lmp-base/recipes-bsp/u-boot/u-boot-fio_imx-2022.04.bb
- 7bd9d0a8fc [FIO tosquash] imx8: adjust address for FIT buffer
> base: u-boot-fio: imx-2022.04: bump to 7bd9d0a8fc

- meta-lmp-base/recipes-kernel/kern-tools/kern-tools-native_git.bbappend
```
This reverts commit 9f0837380755461262efc58cb1c4e14dbd47ae59.
It is already merged on master/kirkstone
```
Merged Upstream:
- master: https://git.yoctoproject.org/poky/commit/?id=4c9b5da26bf56c80f2dfdbcb8b35ee36baa8ad7c
- kirstone: not yet
> Revert "base: kern-tools-native: bump to 6a4752ebb"

- meta-lmp-base/recipes-kernel/linux/kmeta-linux-lmp-5.15.y.inc
This fixes a wired ethernet on imx8mp.
- 1b0ca2f bsp: imx8mp-lpddr4-evk: enable REALTEK_PHY
- 5f314c5 bsp: imx: apalis-imx6 enable DRM and HDMI
> base: kmeta-linux-lmp-5.15.y: bump to 1b0ca2f

- meta-lmp-base/recipes-kernel/jool/jool_git.bb
Upstream project renamed the master branch to main.
> base: jool: update branch name from master to main

- meta-lmp-base/recipes-sota/aktualizr/aktualizr_%.bbappend
- 73a1bb7 ostree: Add a flag to turn ON/OFF update blocking
- 465b473 boot: Block update if boot fw update is in progress
- e83d38a aktualizr: Switch to libaktualizr 2022.11+fio
- b4ac6ef apps: Prune images only if pruning is enabled
- 94d72a4 docker: Do auth according to the spec
> base: recipe-sota: aktualizr-lite: bump to 73a1bb7

- meta-lmp-base/recipes-sota/lmp-device-register/lmp-device-register_git.bb
- 2bb3a61 Extend the check whether a device is registered
> base: lmp-device-register: bump to 2bb3a61

- meta-lmp-base/recipes-security/optee/optee-os-fio_3.18.0.bb
- 06944aba5 [FIO fromlist] crypto: drivers: se050-f: rsa: can fallback to software operations
- b4b1ea1ff [FIO fromlist] crypto: drivers: se050-f: ecc: can fallback to software operations
- 692276b28 [FIO fromlist] crypto: drivers: se050: ecc: fallback to software operations
- ef0248b38 [FIO fromlist] crypto: drivers: se050: rsa: fallback to software operations
- 9bc763021 [FIO fromlist] crypto: drivers: se050-f: rsa: fix support
- 873334ea2 [FIO fromlist] crypto: drivers: se050: adaptor: provide the oefid interface
- 16ab116b7 [FIO fromtree] core: crypto-api: rsa: pass algorithm to implementation
- d729f2aa9 [FIO internal]: se050: scp03: prohibit derived keys without RPMB ready.
> base: optee-os-fio: 3.18: bump to 06944aba5

- meta-lmp-bsp/recipes-support/mfgtool-files/mfgtool-files/apalis-imx8-sec/full_image.uuu.in
This suffers from the same order issue as the MEK. this should be almost the same as the MEK at this point.
> recipes-support: Correct apalis-imx8-sec full_image.uuu script

- meta-lmp-base/recipes-security/optee/optee-os-fio_3.18.0.bb
- 382fb9d84 [FIO fromlist] crypto: se050: fix unused function warning when loglevel < 2
- ad8d5279e [FIO fromlist] crypto: drivers: se050-f: rsa: can fallback to softw-ops
- ebebbf4f2 [FIO fromlist] crypto: drivers: se050: rsa: fallback to softw-ops
- e942dd714 Revert "[FIO fromlist] crypto: drivers: se050: rsa: fallback to software operations"
- 443eb7f85 Revert "[FIO fromlist] crypto: drivers: se050-f: rsa: can fallback to software operations"
> base: optee-os-fio: 3.18: bump to 382fb9d84

- meta-lmp-bsp/dynamic-layers/xilinx/recipes-bsp/u-boot/u-boot-xlnx_2022.01.bb
- 0e833bd2e11 [FIO fromtree] arm64: zynqmp: Print the secure boot status information
- 5dbbcc81134 zynqmp: improve multi_boot cmd
> bsp: u-boot-xlnx: 2022.01: bump to 0e833bd2e11

- meta-lmp-base/recipes-support/fioconfig/fioconfig_git.bb
This bumps fioconfig to pull in support for certificate rotation.
> base: fioconfig: Bump revision for client cert rotation

- meta-lmp-bsp/recipes-kernel/linux/linux-lmp/apalis-imx6/0001-FIO-extra-arch-arm-dts-imx6q-apalis-disable-lcdif-pa.patch
- meta-lmp-bsp/recipes-kernel/linux/linux-lmp_git.bbappend
Add a patch to make HDMI interface work.
Note, this patch disables a lcdif panel. If the panel is connected to a board, it is safe to enable it back - in this case, it won't break other interfaces.
> bsp: linux-lmp: apalis-imx6: fix HDMI interface

- meta-lmp-base/recipes-core/dbus/dbus_%.bbappend
From oe-core master (4df1a16e5c38d0fb724f63d37cc032aa37fa122f), specify runstatedir to use /run directly (instead of the default /var/run), to fix the following runtime warning from systemd:
systemd-tmpfiles[350]: /usr/lib/tmpfiles.d/dbus.conf:13: Line references path below legacy directory /var/run/, updating /var/run/dbus/containers → /run/dbus/containers; please update the tmpfiles.d/ drop-in file accordingly.
> base: dbus: specify runstatedir to use /run

- meta-lmp-base/recipes-support/fioconfig/fioconfig_git.bb
This bumps fioconfig to pull in the changes which
remove the go-ethereum dependency in favor of the foundriesio/go-ecies.
Signed-off-by: Volodymyr Khoroz <volodymyr.khoroz@foundries.io>
> base: fioconfig: Bump revision for foundriesio/go-ecies

- meta-lmp-bsp/dynamic-layers/meta-ti-bsp/recipes-bsp/ti-sci-fw/ti-sci-fw_git.bbappend
- meta-lmp-bsp/dynamic-layers/meta-ti-bsp/recipes-ti/secdev/ti-k3-secdev_git.bb
**This is a temporary workaround to remove the dependencie in
meta-ti-extras until the patch is merged upstream.
https://lists.yoctoproject.org/g/meta-ti/message/15567
https://lists.yoctoproject.org/g/meta-ti/message/15568
https://lists.yoctoproject.org/g/meta-ti/message/15569**
The meta-ti-bsp layer is still broken for K3 HS platforms.
The patch [1] makes the check-layer happy again as it does not
fail any more during bitbake parsing but it will be difficult
for the end user to discover this dependency on meta-ti-extras.
On the other side, meta-ti-extras depends on meta-ti-bsp so
this is a circular dependency.
Currently the layer is broken for am62xx-evm/am64xx-evm machines:
```
ERROR: Nothing PROVIDES 'ti-k3-secdev-native' (but …
```
> Remove meta-ti-extras layer dependencies

- meta-lmp-base/conf/distro/include/lmp.inc
This make possible to build meta-st-stm32mp layer
with oe-core master branch.
https://github.com/STMicroelectronics/meta-st-stm32mp/pull/45
> base: lmp: mask meta-st-stm32mp libdrm_2.4.113.bbappend

- meta-lmp-base/conf/distro/include/non-clangable.inc
Jailhouse includes a kernel module, and the build fails if built with a different toolchain than used by the main kernel recipe.
> base: non-clangable: jailhouse: force gcc

- meta-lmp-bsp/recipes-kernel/linux-firmware/linux-firmware_%.bbappend
- 982bb10 FwImage: update firmware to mxm5x17366.p3
- aeba88d FwImage: update firmware to mxm5x17362
> bsp: linux-firmware: Update imx-firmware to lf-5.15.71-2.2.0

- meta-lmp-bsp/dynamic-layers/meta-ti-bsp/recipes-bsp/u-boot/u-boot-ti-staging_%.bbappend
Also include u-boot-lmp-common.inc in order for the final u-boot config to be deployed as part of the build process (facilitates debugging).
> bsp: u-boot-ti-staging: deploy u-boot config

- meta-lmp-bsp/conf/machine/include/lmp-machine-custom.inc
- meta-lmp-bsp/dynamic-layers/meta-ti-bsp/recipes-bsp/lmp-boot-firmware/lmp-boot-firmware.bbappend
Similar to https://github.com/foundriesio/meta-lmp/pull/1020 but without deploying/installing the MC related files (k3-r5 firmware).
> AM6XXX: publish boot firmware files (no MC)

- meta-lmp-base/recipes-sota/config/files/10-lite-public-stream.toml.in
Not used by anyone anymore since aktualizr-lite-public-stream.bb was removed in 360f02224d.
> base: remove 10-lite-public-stream.toml.in

- meta-lmp-base/recipes-kernel/linux/kmeta-linux-lmp-5.10.y.inc
- 2b0fbe83 bsp: ti-arm64-common: add CONFIG_OF_OVERLAY
> base: kmeta-linux-lmp-5.10.y: bump to 2b0fbe83

- meta-lmp-bsp/recipes-kernel/jailhouse/jailhouse/0001-k3-am625-sk-add-vtm-memory-node.patch
- meta-lmp-bsp/recipes-kernel/jailhouse/jailhouse_git.bbappend
Fixes a runtime exception when the kernel accesses that memory region:
Unhandled data read at 0xb00308(4)
FATAL: unhandled trap (exception class 0x24)
> bsp: jailhouse: k3: add missing vtm memory node

- meta-lmp-bsp/conf/machine/include/lmp-machine-custom.inc
Similar to generic-arm64, but with required configurations and dependencies for building edk2 firmware by default (in order to be used with qemu).
> bsp: lmp-machine-custom: add overrides for qemu-generic-arm64

- meta-lmp-base/classes/lmp-staging.bbclass
- meta-lmp-bsp/conf/machine/include/lmp-machine-custom.inc
- meta-lmp-bsp/conf/multiconfig/lmp-k3r5-gp.conf
- meta-lmp-bsp/conf/multiconfig/lmp-k3r5-sr2-hs-fs.conf
- meta-lmp-bsp/conf/multiconfig/lmp-k3r5-sr2-hs-se.conf
- meta-lmp-bsp/conf/multiconfig/lmp-k3r5.conf
Using the same TMPDIR it is very sensitive and prone to several errors
when used in more complex situations.
This configuration forces that all native packages have to be the same between all
machines and this requirement is very easy to break.
Suppose you use a macinhe override and this requirement is no longer met.
Many of these anomalies can be verified with the use of the rm-work and
create-spdx bitbake classes.
> TI: move to unshared TMPDIR in multiconfig machines

- meta-lmp-base/conf/distro/lmp-base-wayland.conf
- meta-lmp-base/conf/distro/lmp-base-xwayland.conf
Initial sanity check with
```
bitbake -e weston-init | awk '/^# \$SRC_URI \[/,/^SRC_URI/'
```
> Added new base distros with wayland support

- meta-lmp-base/recipes-connectivity/openssh/openssh_%.bbappend
- meta-lmp-bsp/recipes-connectivity/openssh/openssh_%.bbappend
OE-Core 2ed579aa28 removes rng-tools pkg-config and rrecommends logic from the openssh recipe, so drop our local overrides as they are not required anymore.
> base/bsp: openssh: drop rng-tools removal

- meta-lmp-bsp/dynamic-layers/xilinx/recipes-bsp/bootbin/machine-xilinx-versal-optee.inc
OP-TEE is not executed by the PLM but by TF-A instead.
> bsp: bootbin: versal: op-tee loaded by tf-a

- meta-lmp-bsp/dynamic-layers/meta-ti-bsp/recipes-bsp/u-boot/u-boot-ti-staging/am62xx-evm/lmp.cfg
Move the default environment from an emmc offset to the first vfat partition (sdcard) as a way to facilitate the environment management process on clean flash.
> bsp: u-boot-ti-staging: am62xx-evm: use vfat for env

- meta-lmp-base/conf/distro/include/lmp.inc
Attempts to isolate the build system from the host distribution’s C library in order to make re-use of native shared state artifacts across different host distributions practical.
https://docs.yoctoproject.org/ref-manual/classes.html?highlight=uninative#uninative-bbclass
> base: lmp: enable uninative

- meta-lmp-base/recipes-samples/images/lmp-image-common.inc
Adds ~3MB to the image size, but useful for users wanting to set timezone to a valid value other than UTC.
> base: lmp-image-common: install tzdata by default

- meta-lmp-bsp/dynamic-layers/stm-st-stm32mp/recipes-support/stm32-mfgtool-files/stm32-mfgtool-files/provision.sh.in
Changing from STM32CubeProgrammer_CLI version 2.11.0 to version 2.12.0 caused the provision.sh script to not work.
This PR makes it work correctly for these 2 versions of the tools and only those as well as making sure that any command that fails in running this script will not allow the script to continue but exit with an appropriate error.
> Provision robustness

- meta-lmp-base/recipes-support/lmp-auto-hostname/lmp-auto-hostname/lmp-auto-hostname.service.in
- meta-lmp-base/recipes-support/lmp-auto-hostname/lmp-auto-hostname/lmp-update-hostname.sh
- meta-lmp-base/recipes-support/lmp-auto-hostname/lmp-auto-hostname_0.1.bb
3 commits that improves the "lmp-auto-hostname" feature [1]:
1. Support changing the hostname even if "`hostnamectl`" is not available, with a fall-back to "`/usr/bin/hostname`".
2. Avoid to run the script at every boot, to boot faster, because it is not needed.
3. Add an option to fetch the serial number from the secure environment with "`fiovb`", instead of using the CPU serial number.
References:
- [1]      "_Auto Hostname_"
<https://docs.foundries.io/latest/user-guide/lmp-auto-hostname/lmp-auto-hostname.html>
- [2]      "_systemd-hostnamed.service, systemd-hostnamed — Daemon to control system hostname from programs_"
<https://docs.foundries.io/latest/user-guide/lmp-auto-hostname/lmp-auto-hostname.html>
> Improve auto hostname

- meta-lmp-bsp/dynamic-layers/stm-st-stm32mp/recipes-support/stm32-mfgtool-files/stm32-mfgtool-files/provision.sh.in
The "`provision.sh`" script was made more robust by commit a9b949cf7d59 [1] that introduced a "`set -e`" command in the Bash script [2], which:
```
set -e Exit immediately if a pipeline (...), exits with a
non-zero status.
```
The script is more robust in the sense that it will exit immediately in case a subcommand fails. The purpose is to avoid to close an STM32MP15x from which the OTP is not fully burned.
When testing commit a9b949cf7d59 [1] on a closed STM32MP15x device, "`provision.sh`" stopped with an error message:
```
Flashing service completed successfully
+ stm32prog_otp_refresh_values ++ STM32_Programmer_CLI -c port=USB1 -otp displ
+ otp_displ='      -------------------------------------------------------------------
STM32CubeProgrammer v2.12.0 …
```
> provision.sh.in: accept STM32_Programmer -otp displ failure

- meta-lmp-bsp/dynamic-layers/meta-ti-bsp/recipes-graphics/libgles/ti-img-rogue-umlibs_%.bbappend
This reverts commit b2a7a2e3adeefef685bf8b28d8685b6b20bfc76a.
Upstream meta-ti reverted the graphics changes because the master branch is broken as bitbake fails parsing.
Once that meta-ti is exercised ao the autobilder it is a blocker on the yocto project.
> Revert "bsp: ti-img-rogue-umlibs: fix usrmerge"

- meta-lmp-base/recipes-samples/images/lmp-image-common.inc
for some audio apps to work the default user needs to be added to the audio group.
> base: recipes-samples: add fio to audio group

- meta-lmp-bsp/recipes-core/images/initramfs-ostree-lmp-image.bbappend
USB support requires firmware to be available in the initrd.
> bsp: initramfs-ostree-lmp-image: tegra: install tegra-firmware-xusb

- meta-lmp-base/recipes-sota/lmp-device-register/lmp-device-register_git.bb
Move to:
* use new "main" branch
* drop all the ifdef content and use /etc/os-release
> base: lmp-device-register: bump version

- meta-lmp-base/recipes-kernel/linux/kmeta-linux-lmp-6.1.y.inc
- meta-lmp-base/recipes-kernel/linux/linux-lmp-rt_6.1.bb
- meta-lmp-base/recipes-kernel/linux/linux-lmp_6.1.bb
Not yet default as STM32 still requires work.
> base: linux-lmp/-rt: add recipes for kernel 6.1

- meta-lmp-base/conf/distro/include/non-clangable.inc
- meta-lmp-bsp/dynamic-layers/tegra/recipes-kernel/linux/linux-tegra%.bbappend
- meta-lmp-bsp/dynamic-layers/tegra/recipes-kernel/linux/linux-tegra-rt_5.10.bb
- meta-lmp-bsp/dynamic-layers/tegra/recipes-kernel/linux/linux-tegra_%.bbappend
Same as linux-tegra, but with the RT (available in the linux/rt-patches folder) applied, as suggested by meta-tegra.
> Add support for linux-tegra-rt

- meta-lmp-base/recipes-kernel/linux/kmeta-linux-lmp-5.15.y.inc
- meta-lmp-bsp/conf/machine/include/lmp-machine-custom.inc
- meta-lmp-bsp/dynamic-layers/freescale-layer/recipes-bsp/firmware-imx/firmware-imx_8.%.bbappend
- meta-lmp-bsp/recipes-kernel/linux-firmware/linux-firmware_%.bbappend
Have SDMA provided by firmware-imx (latest revision) and add firmwared as it is required for early loading of the firmware when booting the system.
> Aligning SDMA firmware version and load logic with NXP BSP

- meta-lmp-bsp/scripts/lib/wic/plugins/source/bootimg-sota-efi.py
Remove the hardcoded bootable flag on the first partition and instead search for active partitions when defining the bootable one.
This allows the ESP partition to be created as second or third partition (for cases where the boot firmware partition needs to be defined first).
> bsp: bootimg-sota-efi: allow dynamic bootable partition

- meta-lmp-base/recipes-bsp/u-boot/u-boot-ostree-scr-fit/boot-common-alternative.cmd.in
Handle case, when bootupgrade_available is mistakenly set (for example manually using fiovb/ubootenv), and this prevents aklite to start new update procedure.
> base: u-boot-ostree-src-fit: handle bootupgrade_available corner case

- meta-lmp-base/conf/distro/include/lmp.inc
**Archiver**
A fix to don't re-run the rm_work is merged upstream
https://git.yoctoproject.org/poky/commit/?id=6cd9a85d2b9f6272c0b0e9d68c6dbd5e8c0c336b
https://git.yoctoproject.org/poky/commit/?id=0f9773ee717d54ce1ed5001bc5ef4ec470f13476
**Create-spdx**
The create-spdx is been moved to only runs on CI as local builds can run in the majority of time without this
that reduces the build time.
**Buildhistory**
Moves the buildhistory to bitbake conf as this is not a distro
configuration and is more related to a build configuration.
> LmP: move INHERIT out of distro config

- meta-lmp-base/recipes-bsp/u-boot/u-boot-ostree-scr-fit/boot-common-alternative.cmd.in
Sync and align handling of "is_secondary_boot" variable between on boot-common and boot-common-alternative boot scripts.
> base: u-boot-ostree-scr-fit: sync is_secondary_boot handling

- meta-lmp-base/recipes-sota/aktualizr/aktualizr/aktualizr-lite.service.in
Drop condition on public-stream and on mbedCloudClient, as they are not really used / supported anymore.
> base: aktualizr-lite.service: drop old conditions for the service

- meta-lmp-base/classes/kernel-lmp-fitimage.bbclass
- meta-lmp-base/classes/uboot-fitimage.bbclass
- meta-lmp-base/recipes-bsp/u-boot/u-boot-ostree-scr-fit.bb
There are few places we use overweighted comparing. Simplify operations to unify them with the other code.
> base: unify comparing values

- meta-lmp-base/recipes-core/initrdscripts/initramfs-module-install-efi/init-install-efi.sh
- meta-lmp-base/recipes-kernel/linux/kmeta-linux-lmp-6.1.y.inc
- meta-lmp-base/wic/image-efi-installer-grub.wks.in
- meta-lmp-bsp/conf/machine/include/lmp-machine-custom.inc
Needed on arm64 as the current sd-boot version does not support loading initrds via LINUX_INITRD_MEDIA_GUID (only via sd-stub, which requires UKI).
> Add back support for grub-based installers and images (for arm64)

- meta-lmp-base/recipes-connectivity/openssl/openssl/0001-translation-EC-legacy-keys-handle-OSSL_PKEY_PARAM_EC.patch
Update the patch in order to be aligned with what was merged in the end.
> base: openssl: refresh patch to the backported version

- meta-lmp-base/recipes-sota/aktualizr/aktualizr_%.bbappend
- 03d1340 api: Add method to obtain device's UUID
- 2a0ff47 offline-client: Fix app blob download
- c598868 offline: Fix dockerless system support
- cba285f offline: Don't pull images at App start
- 6fef010 custom client: Handle rollback for failed apps
- 5a43c1f offline: Handle a normal rollback correctly
- c4d9cc1 pacman: Do correct install "finalization" if no ostree update
- 361b985 offline: Rollback to unknown if initial Target set fails
- 46bfcf5 offline: Finalize Apps install after rollback
- fd850e1 bootloader: Reject update if bootloader rollback is detected
> base: recipe-sota: aktualizr-lite: bump to a7032fb

- meta-lmp-base/recipes-kernel/linux/kmeta-linux-lmp-5.15.y.inc
- meta-lmp-base/recipes-support/mfgtool-files/mfgtool-files_0.1.bb
- meta-lmp-bsp/dynamic-layers/freescale-layer/recipes-bsp/imx-mkimage/imx-boot/0001-iMX8ULP-add-SPL-only-build.patch
- meta-lmp-bsp/dynamic-layers/freescale-layer/recipes-bsp/imx-mkimage/imx-boot_%.bbappend
- meta-lmp-bsp/dynamic-layers/freescale-layer/recipes-fsl/mcore-demos/imx-m33-demos_2.13.0.bb
- meta-lmp-bsp/recipes-bsp/u-boot/u-boot-fio/imx8ulp-lpddr4-evk/fw_env.config
- meta-lmp-bsp/recipes-core/base-files/base-files/imx8ulp-lpddr4-evk/fstab
Some basic updates that are required for supporting imx8ulp.
The actual kernel/u-boot/machine-custom changes will follow in another pr (once everything required is merged).
> Preparing support for imx8ulp

- meta-lmp-bsp/conf/machine/include/lmp-mfgtool-machine-custom.inc
- meta-lmp-bsp/recipes-bsp/u-boot/u-boot-base-scr/imx93-11x11-lpddr4x-evk/boot.cmd
- meta-lmp-bsp/recipes-bsp/u-boot/u-boot-base-scr/imx93-11x11-lpddr4x-evk/uEnv.txt.in
- meta-lmp-bsp/recipes-core/base-files/base-files/imx93-11x11-lpddr4x-evk/fstab
Cherry picks from https://github.com/foundriesio/meta-lmp/pull/1053 to start landing the initial support for 93.
> Initial changes for imx93 support

- meta-lmp-base/recipes-sota/aktualizr/aktualizr_%.bbappend
- d931a79 bootloader: Allow any version format if no rollback protection
- b3f60e8 bootloader: Handle bootloader update if malformed version
> base: recipe-sota: aktualizr-lite: bump to 2d6fade

- meta-lmp-base/recipes-bsp/u-boot/u-boot-fio_imx-2022.04.bb
This should fix booting imx8m devices.
- 0e0855303e1 ("[FIO squash] imx8m: ddr: fix changing padding")
> base: u-boot-fio: imx-2022.04: bump to 0e0855303e1

- meta-lmp-base/recipes-sota/aktualizr/aktualizr/aktualizr-lite.service.in
This patch will force systemd to reboot the board in case aktualizr-lite fails to start. It prevents going into a state when aktualizr-lite doesn't start after OTA and there is no other service that would force a rollback.
> aktualizr-lite: reboot on failed start

- meta-lmp-base/recipes-containers/docker/files/docker.service
When dockerd fails to start after OTA, systemd will reboot the system to force rollback. This patch allows dockerd 3 attempts before rebooting.
> docker: fix dockerd failed start conditions

- meta-lmp-base/recipes-bsp/u-boot/u-boot-ostree-scr-fit/boot-upgrade-alternative.cmd.in
- meta-lmp-base/recipes-bsp/u-boot/u-boot-ostree-scr-fit/boot-upgrade-regular.cmd.in
Update a value of fiovb.bootfirmware_version during boot firmware upgrade procedure alongside with bootfirmware_version.
> base: u-boot-ostree-scr-fit: update fiovb.bootfirmware_version

- meta-lmp-base/conf/distro/lmp.conf
- meta-lmp-bsp/recipes-bsp/alsa/alsa-state-stm32mp1.bbappend
- meta-lmp-bsp/recipes-bsp/alsa/alsa-state-stm32mp1/system-generator-alsa-states
- fixed alsa-state-stm32mp1 recipe
- fixed all recipes that install fonts as a font cache.
> Install files to /usr/lib instead of /var

- meta-lmp-bsp/recipes-support/mfgtool-files/mfgtool-files/imx93-11x11-lpddr4x-evk/full_image.uuu.in
Prefer uncompressed wic in full_image in order to be aligned with all other NXP boards.
We should switch all at the same time as this also impacts documentation, so aligning imx93 with the rest and transition all later once properly tested.
> bsp: mfgtool-files: imx93-11x11-lpddr4x-evk: flash uncompressed wic

- meta-lmp-base/recipes-core/packagegroups/packagegroup-security-tpm2.bbappend
Remove trousers from tpm2 related packagegroup as it is relevant with tpm 1.2 only, which we don't officially support in LmP.
> base: packagegroup-security-tpm2: remove trousers

- meta-lmp-base/recipes-core/systemd/systemd_%.bbappend
Fix the following tmpfiles /run/lock duplication warning message: systemd-tmpfiles[451]: /usr/lib/tmpfiles.d/legacy.conf:13: Duplicate line for path "/run/lock", ignoring.
This is because /run/lock is currently being provided by legacy.conf and 00-create-volatile.conf (OE specific).
> base: systemd: tmpfiles: fix /run/lock duplication

- meta-lmp-base/recipes-bsp/u-boot/u-boot-fio_2022.04.bb
- 3eb7632 Revert "[FIO internal] fiovb: simplify code"
> base: u-boot-fio: 2022.04: bump to 3eb7632

- meta-lmp-base/classes/lmp.bbclass
- meta-lmp-base/recipes-core/base-files/base-files_%.bbappend
- meta-lmp-base/recipes-core/systemd/systemd_%.bbappend
Var directories, created by base-files, are also used by the rootfs task while performing the image bootstrap process (via packages), so they can't be removed at the base-files package level.
Move the removal logic to lmp.bbclass via ROOTFS_POSTPROCESS_COMMAND task, which is executed only when ota-ext4 is set in IMAGE_FSTYPES (only way to know when an ostree image is to be created), after all required rootfs packages are installed. Only dirs that can't be removed at this stage are /var/lib and /var/cache as they are used to store packaging related metadata.
> base: move var clean up from base-files to lmp.bbclass

- meta-lmp-base/recipes-bsp/u-boot/u-boot-fio_imx-2022.04.bb
- a97c174e fastboot: fsl: imx8qm: extend bootloader2 partition
> base: u-boot-fio: 2022.04: bump to a97c174e

- meta-lmp-base/recipes-kernel/linux/linux-lmp-rt_6.1.bb
Follow linux-lmp and switch to the 6.1 series by default.
> base: linux-lmp-rt: switch to 6.1 as default rt

- meta-lmp-base/conf/distro/include/lmp.inc
This reverts commit 9630be90bb0f0c63a4e268db778adf4100ecb9fb.
The systemd tmpfiles is now porvided in meta-updater nfs-utils append [1]
This is needed to create the required directory structure at runtime for nfsd.
[1] https://github.com/uptane/meta-updater/commit/bfcf400813c4ff6f97ac9fd8bf44f5b8b0eb12c9
> Revert "base: lmp: mask meta-updater nfs-utils append"

- meta-lmp-base/classes/fip-utils.bbclass
- meta-lmp-base/classes/uboot-fitimage.bbclass
Create the /firmware/bootloader node using auto-path, in order to automatically create all nodes required for the node path (useful for cases where /firmware is not defined by the board).
> base: u-boot/fip: fix bootfirmware version without firmware node

- meta-lmp-base/wic/image-efi-installer.wks.in
This avoids a possible UEFI bootloader confusion when searching for the right ESP partition to boot.
This change also won't affect the behavior of the installer since ota-boot is just used as a way to copy the /boot content that is supposed to be installed as part of the final image. The final ESP partition is created manually by the script.
> base: image-efi-installer: use ext4 for ota-boot content

- meta-lmp-bsp/recipes-bsp/u-boot/u-boot-ostree-scr-fit/am62xx-evm/boot.cmd
- meta-lmp-bsp/recipes-bsp/u-boot/u-boot-ostree-scr-fit/am64xx-evm/boot.cmd
Extra "ti_" is already part of the default fdtfile variable in the latest TI BSP (set via "run findfdt").
> bsp: u-boot-ostree-scr-fit: am62/am64: update fit config naming

- meta-lmp-base/recipes-support/libp11/files/0001-from-list-Introduce-generic-keypair-generation-inter.patch
- meta-lmp-base/recipes-support/libp11/files/0002-from-list-Fix-constness-of-key-generation-attributes.patch
- meta-lmp-base/recipes-support/libp11/files/0003-FIO-internal-ec_keygen-changes-required-for-TPM.patch
- meta-lmp-base/recipes-support/libp11/files/0004-from-upstream-slot-fix-token-initialization.patch
- meta-lmp-base/recipes-support/libp11/libp11_0.4.12.bb
Enables libp11 with out-of-tree patches that allows using the API to create EC keys as well as initializing a token in the TPM.
> libp11: fix libp11 to enable lmp-device-register refactor

- meta-lmp-base/classes/fip-utils.bbclass
- meta-lmp-base/classes/lmp-staging.bbclass
- meta-lmp-base/classes/uboot-fitimage.bbclass
- meta-lmp-base/recipes-bsp/lmp-boot-firmware/lmp-boot-firmware.bb
- meta-lmp-base/recipes-bsp/u-boot/u-boot-fio-common.inc
- meta-lmp-base/recipes-sota/ostree-kernel-initramfs/ostree-kernel-initramfs_%.bbappend
- meta-lmp-base/recipes-support/mfgtool-files/mfgtool-files_0.1.bb
- meta-lmp-bsp/dynamic-layers/freescale-layer/recipes-bsp/imx-mkimage/imx-boot_%.bbappend
- meta-lmp-bsp/dynamic-layers/stm-st-stm32mp/recipes-support/flashlayouts-stm32mp1/flashlayouts-stm32mp1.bb
- meta-lmp-bsp/dynamic-layers/stm-st-stm32mp/recipes-support/stm32-mfgtool-files/stm32-mfgtool-files_0.1.bb
- meta-lmp-bsp/dynamic-layers/xilinx/recipes-bsp/u-boot/u-boot-xlnx_2022.01.bb
- meta-lmp-bsp/recipes-kernel/linux/linux-lmp-toradex-imx_git.bb
This handler will generate an ERROR when there are 'do_deploy' dependencies without setting the DEPENDS.
One of the side effect of this issues is SPDX documents not including the correct dependencies.
```
/
| ERROR: lmp-boot-firmware-0-r0 do_install: Task 'do_install' depends on 'virtual/bootloader:do_deploy' but 'virtual/bootloader' is not in DEPENDS
| ERROR: lmp-boot-firmware-0-r0 do_install: Task 'do_install' depends on 'virtual/trusted-firmware-a:do_deploy' but 'virtual/trusted-firmware-a' is not in DEPENDS
\
```
Explicit adds the dependencies of the 'do_deploy' in the task[depends].
With this patch the missed dependencies are now in the SPDX documents of the package as well as in the final SPDX of the combined image.
The following example is for the lmp-base-console-image on …
> Track the missing dependencies on SPDX documents

- meta-lmp-base/recipes-sota/aktualizr/aktualizr_%.bbappend
- bb55a33 Merge pull request #237 from foundriesio/custom-client-target
- 447bbbe readme: Add info on building running the custom client
- 7dbcead custom-client: Add env var to specify config dir
- c528030 makefile: Add the custom client target
- a05f2a1 Merge pull request #236 from foundriesio/fix-events-draining-at-exit
- dbcfa31 liteclient: Drain events before destruction
- 404d643 Merge pull request #235 from foundriesio/kprosise/cleanup-markdown
- c12719d Cleanup documentation in aktualizr-lite
> base: recipe-sota: aktualizr-lite: bump to bb55a33

- meta-lmp-base/classes/lmp-staging.bbclass
We only show mirror in use when the summary is enabled
and because the default value of the function is summary=True
we need to considere and validate when the argument is not provided.
This fix a bug where multiple lines are printed for every sstate_checkhashes call:
```
SState mirrors: file://.* https://storage.googleapis.com/lmp-cache/v90-sstate-cache/PATH
SState mirrors: file://.* https://storage.googleapis.com/lmp-cache/v90-sstate-cache/PATH
SState mirrors: file://.* https://storage.googleapis.com/lmp-cache/v90-sstate-cache/PATH
SState mirrors: file://.* https://storage.googleapis.com/lmp-cache/v90-sstate-cache/PATH
```
> lmp-staging: lmp_sstate_checkhashes: summary needs to be checked

- meta-lmp-bsp/recipes-kernel/linux/linux-lmp-fslc-imx.inc
- meta-lmp-bsp/recipes-kernel/linux/linux-lmp-fslc-imx_6.1.bb
- meta-lmp-bsp/recipes-kernel/linux/linux-lmp-fslc-imx_git.bb
- separate common 
- Add linux-lmp-fslc-imx kernel based on the latest stable 6.1.24
> Add linux-lmp-fslc-imx 6.1 kernel recipe

- meta-lmp-base/recipes-kernel/linux/linux-lmp-dev.bb
Update template variables to use 6.4.0-rc2 by default, as that is the current development release.
> base: linux-lmp-dev: update template to 6.4.0-rc2

- meta-lmp-bsp/recipes-kernel/linux/linux-lmp-fslc-imx_6.1.bb
- meta-lmp-bsp/recipes-kernel/linux/linux-lmp-fslc-imx_git.bb
I accidentally merged the previous PR before testing. This PR fixes the building issue brought in https://github.com/foundriesio/meta-lmp/pull/1097
Include the file with common settings fixes building the system.
Fixes: 8ee14f16 ("bsp: linux-lmp-fscl-imx: separate common settings")
> Emegency fix: bsp: linux-lmp-fslc-imx: include common settings

- meta-lmp-base/classes/lmp.bbclass
There is no reason to support the ostreehub API v1, so let's push a generated ostree repo only to ostreehub v2 API.
> base: lmp: Push only to v2 of ostreehub API

- meta-lmp-base/recipes-sota/ostreeuploader/ostreeuploader_git.bb
- 1d57fed fiopush: Support just `v2` ostreehub API version
- b3732aa fiocheck: Support just `v2` ostreehub API version
> base: recipe-sota: ostreeuploader: bump to b3732aa

- meta-lmp-bsp/dynamic-layers/stm-st-stm32mp/recipes-support/stm32-mfgtool-files/stm32-mfgtool-files/FlashLayout_stm32mp1-usb.tsv.in
- meta-lmp-bsp/dynamic-layers/stm-st-stm32mp/recipes-support/stm32-mfgtool-files/stm32-mfgtool-files_0.1.bb
As explained by Arnout Vandecappelle in a review, the "`--transform`" in:
```
tar -czf ${DEPLOYDIR}/${PN}-${MACHINE}.tar.gz \
--transform "s,^mfgtool-files,mfgtool-files-${MACHINE}," \
-C ${DEPLOYDIR} ${PN}
```
in the "`do_deploy()`" task in "`stm32-mfgtool-files_0.1.bb`" [1] does not work:
```
This transform isn’t doing anything, because the directory is called
"stm32-mfgtool-files", not "mfgtool-files"... Should use "${PN}"
here. I do think the transform is useful.
```
We should use "`${PN}`" instead of "`mfgtool-files`" as source of the name transformation, because the directory name is "`${PN}`", as shown by the first line of "`do_deploy()`" on line 38:
```
install -d ${DEPLOYDIR}/${PN}
```
"`${PN}`" is the recipe name [3], "`stm32-mfgtool-files`" in our case.
This recipe was moved …
> stm32-mfgtool-files: fix tar's "--transform" to rename dir

- meta-lmp-base/recipes-sota/lmp-device-register/lmp-device-register_git.bb
- 0e65a28 Merge pull request #44 from ldts/pacman-fix
- 45b6d27 main: fix missing pacman tags
- 85675c3 auth: Make the oauth api configurable
> base: lmp-device-register: bump to 0e65a28

- meta-lmp-base/recipes-support/docker-cli-config/docker-cli-config/config.json
- meta-lmp-base/recipes-support/docker-cli-config/docker-cli-config/config.json.in
- meta-lmp-base/recipes-support/docker-cli-config/docker-cli-config_0.1.bb
This can be used to point a device at another factory backend instance.
> base: docker-cli-config: Make hub.fio URL configurable

- meta-lmp-base/recipes-bsp/u-boot/u-boot-fio_2022.04.bb
- ea62f691709 [FIO extras] board: rpi: always set fdt_addr if provided by firmware
> base: u-boot-fio: 2022.04: bump to ea62f691709

- meta-lmp-base/conf/distro/include/non-clangable.inc
Fixes undefined references due glibc being built with gcc.
> base: non-clangable: containerd: use libgcc with compiler-rt

- meta-lmp-base/classes/uboot-fitimage.bbclass
egrep is obsolescent. It is now an alias for "grep -E" [1]. Update the command to avoid wrapping and showing warning.
[1]
$ egrep -V
egrep: warning: egrep is obsolescent; using grep -E grep (GNU grep) 3.8
> base: uboot-fitimage: avoid using obsolete egrep

- meta-lmp-base/recipes-support/mfgtool-files/mfgtool-files_0.1.bb
Upstream updated the binaries for the 1.5.21 release by accident (https://github.com/nxp-imx/mfgtools/issues/374), so update to use the new sha and also drop uuu_mac temporarily until it is available by upstream again.
> base: mfgtool-files: refresh release sha256sum

- meta-lmp-base/recipes-sota/custom-sota-client/custom-sota-client_git.bb
The custom-sota-client requires the folder /etc/sota/conf.d/ available. Otherwise, the service will not start. 
Install an empty folder /etc/sota/conf.d/ .
> base: custom-sota-client : Add the missing configuration folder

- meta-lmp-base/recipes-containers/skopeo/skopeo/0001-cmd-copy-max-parallel-pulls-param.patch
- meta-lmp-base/recipes-containers/skopeo/skopeo_git.bbappend
- meta-lmp-base/recipes-sota/aktualizr/aktualizr/aktualizr-lite.service.in
- meta-lmp-base/recipes-sota/aktualizr/aktualizr_%.bbappend
- Patch `skopeo` to expose a new CLI param `--max-parallel-pulls`.
- Add a new env. variable to control the maximum concurrent pulls in `skopeo copy` command.
- Bump the new aklite version that supports the new env. var.
> Skopeo max parallel pulls param

- meta-lmp-base/recipes-bsp/u-boot/u-boot-fio_imx-2022.04.bb
Use a u-boot version based on NXP u-boot branch lf_v2022.04 and tag lf-6.1.1-1.0.0 used in NXP BSP LF6.1.1_1.0.0.
Tested booting lmp-base:
- imx6ullevk: **OK**
- imx8mm-lpddr4-evk: **OK**.
- apalis-imx8: **OK**
Tested by Ricardo:
- imx8ulp
- imx93
> base: u-boot-fio: imx-2022.04: switch to 2022.04+lf-6.1.1-1.0.0-fio

- meta-lmp-bsp/recipes-kernel/linux/linux-lmp-fslc-imx/0003-FIO-toup-gpu-drm-cadence-select-hdmi-helper.patch
- meta-lmp-bsp/recipes-kernel/linux/linux-lmp-fslc-imx/0004-FIO-toup-media-imx8-select-v4l2_-for-mxc-mipi-csi2_y.patch
- meta-lmp-bsp/recipes-kernel/linux/linux-lmp-fslc-imx_6.1.bb
Add more patches to fix issues with building imx8mp and imx8mq:
- select hdmi helper cdns-hdmi-core driver
- select v4l2_* modules for mxc-mipi-csi2_yav driver
> Further patches for kernel 6.1

- meta-lmp-base/conf/layer.conf
This pacth fixes the CI rebuilding of the kernel that is currently triggered by:
```
H_BUILD++ -> os-release -> initramfs -> kernel
```
The os-release is not installed on the initramfs image but because it is a condictional RRECOMMENDS dependencie of the systemd recipe they are used on the signature. The systemd recipe is used on the signature because they provide the udev as systemd-udevd installed on the image.
The os-release dependecie can be checked on the bitbake task-depends.dot file:
```
> bitbake --graphviz [ initramfs-ostree-lmp-image | core-image-minimal-initramfs ] 
> grep os-release task-depends.dot
"systemd.do_package_qa" -> "os-release.do_packagedata" 
"systemd.do_package_write_ipk" -> "os-release.do_packagedata"
```
The steps to reproduce the triggering of the rebuild are …
> base: layer.conf: exclude os-release siggen dependencie on the initramfs

- meta-lmp-base/recipes-bsp/u-boot/u-boot-fio-mfgtool_2021.04.bb
- meta-lmp-base/recipes-bsp/u-boot/u-boot-fio_2021.04.bb
- meta-lmp-base/recipes-bsp/u-boot/u-boot-fio_2021.07.bb
U-boot 2021.04 and 2021.07 are not used in LmP anymore. Remove obsolete recipes.
> base: u-boot: remove unused recipes

- meta-lmp-bsp/recipes-bsp/u-boot/u-boot-fio/stm32mp15-disco/lmp.cfg
- meta-lmp-bsp/recipes-bsp/u-boot/u-boot-fio/stm32mp15-eval-sec/lmp.cfg
- meta-lmp-bsp/recipes-bsp/u-boot/u-boot-fio/stm32mp15-eval/lmp.cfg
- meta-lmp-bsp/recipes-bsp/u-boot/u-boot-ostree-scr-fit/stm32mp15-disco/boot.cmd
- meta-lmp-bsp/recipes-bsp/u-boot/u-boot-ostree-scr-fit/stm32mp15-eval/boot.cmd
The required addr variables are all depending on CONFIG_DISTRO_DEFAULTS, which got disabled as a consequence of the lmp-common work, causing the boot to fail.
Manually define the required addr variables in order for lmp to be fully functional with and without CONFIG_DISTRO_DEFAULTS.
> bsp: u-boot-fio/scr-fit: stm32mp15: define used addr vars

- meta-lmp-base/recipes-support/ntp/ntp/0001-libntp-Do-not-use-PTHREAD_STACK_MIN-on-glibc.patch
- meta-lmp-base/recipes-support/ntp/ntp/0001-sntp-Fix-types-in-check-for-pthread_detach.patch
- meta-lmp-base/recipes-support/ntp/ntp/0001-test-Fix-build-with-new-compiler-defaults-to-fno-com.patch
- meta-lmp-base/recipes-support/ntp/ntp/ntp-4.2.4_p6-nano.patch
- meta-lmp-base/recipes-support/ntp/ntp/ntp.conf
- meta-lmp-base/recipes-support/ntp/ntp/ntpd
- meta-lmp-base/recipes-support/ntp/ntp/ntpd.list
- meta-lmp-base/recipes-support/ntp/ntp/ntpd.service
- meta-lmp-base/recipes-support/ntp/ntp/reproducibility-fixed-path-to-posix-shell.patch
- meta-lmp-base/recipes-support/ntp/ntp/sntp
- meta-lmp-base/recipes-support/ntp/ntp/sntp.service
- meta-lmp-base/recipes-support/ntp/ntp_4.2.8p17.bb
The ntp version available in meta-oe kirkstone has several CVEs and important bugs, but we cannot easily backport in meta-oe since the newer version also brings general improvements (not suitable for LTS).
Since the general improvements done as part of the release 4.2.8p16 are not of a concern for LmP, backport latest version from meta-oe master in order to fix the several CVEs associated with the older revisions.
CVEs fixed:
- CVE-2023-26551
- CVE-2023-26552
- CVE-2023-26553
- CVE-2023-26554
- CVE-2023-26555
> base: import ntp 4.2.8p17 from meta-oe master d2a38a5ec5

- meta-lmp-base/conf/layer.conf
- meta-lmp-base/dynamic-layers/clang-layer/recipes-devtools/clang/files/Add-missing-cstdint.patch
- meta-lmp-base/dynamic-layers/clang-layer/recipes-devtools/clang/llvm-project-source.bbappend
Clang 14.0.3 fails to build with GCC 13.1.x with the error [1]. Apply an upstream fix for this issue.
[1]
| In file included from llvm/lib/Support/Signals.cpp:14: | llvm/include/llvm/Support/Signals.h:119:8: error: variable or field 'CleanupOnSignal' declared void
|   119 |   void CleanupOnSignal(uintptr_t Context);
|       |        ^~~~~~~~~~~~~~~
| llvm/include/llvm/Support/Signals.h:119:24: error: 'uintptr_t' was not declared in this scope
Upstream-Status: Pending [meta-clang]
> base: clang-layer: fix building llvm with GCC13

- meta-lmp-base/recipes-samples/images/lmp-image-common.inc
Commit b49ed7f5c sets IMAGE_ROOTFS_SIZE to 65536, which forces the image size to be basically enough for the rootfs, without a lot of extra space (which is then extended by resize-helper). This might cause issues due lack of disk space depending on the situation, so extend IMAGE_ROOTFS_SIZE to 2.3 on tegra, to make sure by default it has enough for a full rootfs OTA.
> base/bsp: lmp-image-common: tegra: increase IMAGE_OVERHEAD_FACTOR to 2.3

- meta-lmp-base/recipes-core/ncurses/files/0001-tic-hang.patch
- meta-lmp-base/recipes-core/ncurses/files/0002-configure-reproducible.patch
- meta-lmp-base/recipes-core/ncurses/files/0003-gen-pkgconfig.in-Do-not-include-LDFLAGS-in-generated.patch
- meta-lmp-base/recipes-core/ncurses/files/exit_prototype.patch
- meta-lmp-base/recipes-core/ncurses/ncurses_6.4.bb
- meta-lmp-base/recipes-core/ncurses/site_config/headers
Switching to ncurses-6.4 later than 20230408 fixes the mentioned CVE.
The upstream version of this fix is in progress.
> ncurses: fix CVE-2023-29491

- meta-lmp-bsp/recipes-kernel/linux/linux-lmp-fslc-imx_6.1.bb
- ad9ab3b3c553 ("ARM: imx_v7_defconfig: Remove KERNEL_LZO config")
> bsp: linux-lmp-fslc: bump kernel 6.1-1.0.x-imx to ad9ab3b3c553

- meta-lmp-bsp/recipes-kernel/linux/linux-lmp-fslc-imx_6.1.bb
This PR switches all imx machines that use linux-lmp-fslc-imx kernel to 6.1.
This version includes both arm64/arm32 archs.
This PR is splitter to smaller ones:
https://github.com/foundriesio/meta-lmp/pull/1194
https://github.com/foundriesio/meta-lmp/pull/1195
> [all relevant imx] Switch to kernel 6.1

- meta-lmp-base/recipes-sota/aktualizr/aktualizr_%.bbappend
- 50e2db3 restorableapps: Cleanup skopeo's tmp files
- 82a2a25 restorableapps: Try tmp file removal if not enough space
- b771ee0 offline: Use absolute path to source dir
- 7050db9 offline: Don't install or register Apps if already running
- f5a810b and d8a59bb cli: The API-based CLI implementation (update/finalize)
- 5885f8a rootfsmanager: Move the finalization fix to libaktualizr
> base: rs: Bump aklite version to e66327c

- meta-lmp-bsp/dynamic-layers/meta-ti-bsp/recipes-bsp/u-boot/u-boot-ti-staging/k3-accept-filesystem-path-to-the-RoT-key.patch
- meta-lmp-bsp/dynamic-layers/meta-ti-bsp/recipes-bsp/u-boot/u-boot-ti-staging_%.bbappend
Allow u-boot's binman to read the signing keys from anywhere in the filesystem.
i.e: specifying the following config option in uboot:
`CONFIG_SIGN_KEY_PATH="/tmp/`
> k3: u-boot: place root of trust keys outside the source repository

- meta-lmp-base/recipes-support/mfgtool-files/mfgtool-files_0.1.bb
New features:
- Using github working flow action to do release.
- Expand upload command, like uploading the value of a specific variable.
Bug fixes:
- Fix segfault when boot data is zero in SDP.
- Fix issues when m_skip is not zero in fastboot.
- Fix issues when file size isn't divisible by block size in fastboot.
- Fix read uploaded data for FB.
> base: mfgtool-files: update UUU 1.5.21 -> 1.5.109

- meta-lmp-base/recipes-kernel/linux/kmeta-linux-lmp-6.1.y.inc
- 810864f0 bsp: imx: imx8mm-evk: fix ethernet interface
> base: kmeta-linux-lmp-6.1.y: bump to 810864f0

- meta-lmp-base/conf/layer.conf
This patch is a follow-up of 24d1016e, the fsl-image-mfgtool-initramfs is used on the distro lmp-mfgtool and without this patch the initramfs is rebuilded which consequently triggers a kernel rebuild.
> base: layer.conf: exclude os-release siggen dependencie on the mfgtool-initramfs

- meta-lmp-bsp/recipes-bsp/u-boot/u-boot-fio/imx8mp-lpddr4-evk/lmp-ebbr.cfg
Tested OK:
- flash
- boot
- network
- register
Reduce image size to fix flashing error [1].
[1]
3:9      6/ 9 [image too large for partition         ] FB: flash bootloader2 ../u-boot-imx8mp-lpddr4-evk-ebbr.itb
> bsp: u-boot-fio: imx8mp-lpddr4-evk-ebbr: reduce image size

- meta-lmp-base/recipes-kernel/linux/kmeta-linux-lmp-6.1.y.inc
- ktypes: xeno4: fix evl configuration
> base: kmeta-linux-lmp-6.1.y.inc: bump to 3261dba

- meta-lmp-base/recipes-support/fioconfig/fioconfig_git.bb
This commit fixes the `fioconfig` handler allowing to restart of the  SOTA CLIENT service when the Custom SOTA Client is used instead `aktualizr-lite`.
Previously the `fioconfig` handler had a hard-coded `systemctl restart aktualizr-lite` . 
In cases where the Custom SOTA Client is used and the `fioconfig` receives any configuration from `fioctl` , it was impossible to restart the Custom SOTA Client service to apply the new configurations.
- Bump `fioconfig` rev to `c9469923f88cec496a9abce194d698fda0f3573d`.
- The final image still retains the `aktualizr-toml-update` handler filename.
> base: fioconfig: Support SOTA_CLIENT customization on aktualizr-toml-update handler.

- meta-lmp-base/recipes-sota/lmp-device-register/lmp-device-register_git.bb
- 3c871e7 options: validate the UUID input parameter
> base: lmp-device-register: bump to 3c871e7

- meta-lmp-base/recipes-sota/lmp-device-register/lmp-device-register_git.bb
- ced5f1c options: fix regression on UUID validation
> base: lmp-device-register: bump to ced5f1c

- meta-lmp-base/recipes-support/lmp-device-auto-register/lmp-device-auto-register/lmp-device-auto-register
Add support for auto registration with tags. Tags should be defined in the /etc/sota/tags file. This file should contain one line with comma separated list of tags.
> meta-lmp-base: lmp-device-auto-register: add support for tags

- meta-lmp-base/conf/distro/include/lmp.inc
Prefer the recipe provided by LmP, which includes AM62 support.
This is to allow us enabling meta-ti-extras without conflicts.
> base: lmp: meta-ti-extras: mask jailhouse

- meta-lmp-base/recipes-security/optee/fio-se05x-cli_git.bb
- 6fd9c93 getuid: display also in decimal
- 1ecbbba getuid: display the secure element unique identifier
- 0611906 Update README.rst
> lmp-base: fio-se05x-cli: bump to 6fd9c93

- meta-lmp-bsp/recipes-kernel/linux/linux-lmp-ti-staging_git.bb
- 8f7f371be25080 HACK: arm64: dts: ti: k3-am68-sk-base-board: Disable DSI
- 02fc6e18c300af HACK: arm64: dts: ti: k3-j784s4-evm: Disable DSI
- 72ad1c84e47332 HACK: arm64: dts: ti: k3-j721s2-common-proc-board: Disable DSI
- 995670442f4b47 arm64: dts: ti: k3-am69-sk-rpi-hdr-ehrpwm: Set the updated pinmux for gpio0
- 772e8f4ac9d62e arm64: dts: ti: k3-j721e-main: Add dts nodes for EHRPWMs
- 439c0dff56266e arm64: dts: ti: k3-j721s2-main: Add dts nodes for EHRPWMs
- a430178d12c87a arm64: dts: ti: k3-j721e-sk-*: Add DTB overlay to enable EHRPWMs
- 6aad0284013ee2 TEMP: media: img: vxe-vxd: decoder: Disable CMA for capture buffers
- de1228f628054a arm64: dts: ti: k3-j721e-beagleboneai64: Fixup reference to phandles array
- a6741f1de15a35 arm64: dts: ti: k3-j721e-beagleboneai64: …
> bsp: linux-lmp-ti-staging: update to 09.00.00.007

- meta-lmp-base/recipes-sota/lmp-device-register/lmp-device-register_git.bb
-3a99d9b options: debug info: fix source of tag and factory definition
> base: lmp-device-register: bump to 3a99d9b

- meta-lmp-bsp/conf/machine/include/lmp-machine-custom.inc
Add a machine feature "mxm-mwifiex-load" that enables auto-loading NXP wlan driver "moal" on boot. It allows to have wlan interface existing by default.
> bsp: ixm8mn-lpddr4-evk: enable wlan driver on boot

- meta-lmp-base/recipes-samples/images/lmp-image-common.inc
Useful for users consuming the intel image with qemu.
> base: lmp-image-common: intel: also create wic.qcow2

- meta-lmp-bsp/recipes-kernel/linux/linux-lmp-fslc-imx-rt_6.1.bb
Based on 6.1-2.0.x-imx + v6.1.38-rt12-rebase.
> bsp: linux-lmp-fslc-imx-rt: update kernel to the 6.1-2.0.x-imx branch

- meta-lmp-base/recipes-kernel/linux/kmeta-linux-lmp-5.15.y.inc
- 613da241 bsp: rpi3: add missing usb phy and regulator fixed
- aea810f0 bsp: rpi: remove config warnings
> base: kmeta-linux-lmp-5-15.y: bump to 613da241

- meta-lmp-base/recipes-sota/aktualizr/aktualizr_%.bbappend
- 99a91d2: cmake: Add build param to turn ON/OFF aklite-apps
- 0bcd548: apps: Calculate App update size precisely
- 80e3e5d: yaml2json: Throw exception with meaningful message
- 193cdf4: restorableapps: Verify already extracted compose file
- cc741b2: restorableapps: Check and store compose file safely
- f24e129: ostree: Exit fetch retry loop if no space while pulling deltas
- def33c2: Print msg if expected error occurs while importing root meta
- c861cf7: liteclient: Set request headers properly at init time
- af0df67: liteclient: Update ostree hash header
- 3c4b924: liteclient: Update info about current target on successful update
- ce6e38d: liteclient: Refresh the status headers on successful update
> base: rs: aktualizr: bump version to 2575118

- meta-lmp-base/recipes-kernel/jool/jool_git.bb
A new kernel module is part of this release, which requires the usage of an internal KBUILD_EXTRA_SYMBOLS settings, and why it is also removed from the recipe.
Install updated to use modules_install in order to have signed modules as part of the install process.
- 47334c91 Protocolary updates for release 4.1.10
- 469c2c22 Add support for kernel 6.2 and 6.3
- cbaf33dc Clean up skb->tstamp on translation
- 4509b34a Patch the kernel module's JNLAT_PORT parser
- bf4c7e36 Docs: Clarify the source of the NBT's ping
- dad6837d Patch Netlink request error propagation logic
- 490ddb09 Modernize the iptables shared object exports
- d5e64957 Userspace half of #347
- 7831ff3f Protocolary updates for release 4.1.9
- 0b5952e8 F1x #378
- c2962a73 Netlink: Allow some backward …
> base: jool: update to 4.1.10

- meta-lmp-base/conf/distro/include/non-clangable.inc
As set with the generic jailhouse recipe.
> base: non-clangable: jailhouse-imx: force gcc

- meta-lmp-base/conf/distro/include/lmp.inc
Added as a side effect of the oe-core a1119750e commit, and causes unexpected side effects on aktualizr-lite, such as:
aktualizr-lite[993]: libc++abi: terminating with uncaught exception of
type offline::MetaFetcher::NotFoundException: Metadata hasn't been
found; role: root; ve5
Disable while the behavior is properly investigated on a more recent clang release.
> base: lmp: clang: disable -mbranch-protection=standard

- meta-lmp-base/conf/distro/include/lmp.inc
It will be better to dropping this as it build a lot of stuff used only in testing, when we decide to run on the target the unit test produced with ptest we can enable it again.
> base: lmp: remove ptest from distro feauture

- meta-lmp-base/recipes-sota/lmp-device-register/lmp-device-register_git.bb
- f3f6d4b options: fix message regarding default device name
- 9107056 options: prevent registration attempts to "lmp" factory
- e8ef575 options: UUID refactor generation code
- fd586fe options: toggle UUID validation
> base: lmp-device-register: bump to f3f6d4b

- meta-lmp-base/recipes-support/compose-apps-early-start/compose-apps-early-start.bb
Add aktualizr-lite-apps as runtime dependency.
The compose-apps-early-start script relies on aklite-apps.
> base: compose-apps-early-start: Add runtime dependency

- meta-lmp-base/recipes-connectivity/docker-network-ref/docker-network-ref/create-docker-ref-network.sh.in
- meta-lmp-base/recipes-connectivity/docker-network-ref/docker-network-ref/docker-network-ref.service
- meta-lmp-base/recipes-connectivity/docker-network-ref/docker-network-ref_1.0.bb
docker-network-ref brings a reference implementation for a docker bridge network that compose apps can connect to.
This avoids issues found when a network is defined in a compose app, which prevents bringing these apps and network down.
> base: connectivity: introduce docker-network-ref implementation

- meta-lmp-base/recipes-support/compose-apps-early-start/compose-apps-early-start/compose-apps-early-start
The assemble system image to add containers to wic image was updated awhile back to include the docker content.
The early start can take advantage of that and just do a docker compose up similar to the logic for compose-apps.
This updates the early start app to detect and activate the app if it is already loaded into docker.
> meta-lmp: update compose apps early start

- meta-lmp-base/recipes-sota/aktualizr/aktualizr_%.bbappend
- ac91224 liteclient: Enable TLS connections sharing
- 1ce7782 aktualizr: Bump version to 2023.09+fio
- e666637 apps: Assume stateless app is pulled when running it
- 54040f3 rfsmgr: Don't pull ostree if no available storage
- eb3a3ff sysroot: Remove redundant conf param
- a46a634 Apply usage stat to apps
- de69ee4 Use usage stat to control pull attempts
- 03c6b14 Unify and improve free space verification
- f676ad3 Apply the new storage watermark parameter to both the delta and non-delta use-cases
- 6efbe43 Delta stat usage fixes
- 70aa49e Delta stat application: check update size before fetching update data
- e20362d Improvements and cleanup related to the static delta use-case
> base: rs: aktualizr: bump version to e981256

- meta-lmp-base/recipes-sota/lmp-device-register/lmp-device-register_git.bb
This gets lmp-device-register working "out of the box" for MEDs
> base: lmp-device-register: support configurable oauth url

- meta-lmp-bsp/recipes-support/mfgtool-files/mfgtool-files/imx6ulevk/full_image.uuu.in
- meta-lmp-bsp/recipes-support/mfgtool-files/mfgtool-files/imx6ullevk/full_image.uuu.in
- meta-lmp-bsp/recipes-support/mfgtool-files/mfgtool-files/imx8mm-lpddr4-evk-sec/full_image.uuu.in
- meta-lmp-bsp/recipes-support/mfgtool-files/mfgtool-files/imx8mm-lpddr4-evk/full_image.uuu.in
- meta-lmp-bsp/recipes-support/mfgtool-files/mfgtool-files/imx8mn-ddr4-evk-sec/full_image.uuu.in
- meta-lmp-bsp/recipes-support/mfgtool-files/mfgtool-files/imx8mn-ddr4-evk/full_image.uuu.in
- meta-lmp-bsp/recipes-support/mfgtool-files/mfgtool-files/imx8mn-lpddr4-evk-sec/full_image.uuu.in
- meta-lmp-bsp/recipes-support/mfgtool-files/mfgtool-files/imx8mn-lpddr4-evk/full_image.uuu.in
- meta-lmp-bsp/recipes-support/mfgtool-files/mfgtool-files/imx8mp-lpddr4-evk-sec/full_image.uuu.in
- meta-lmp-bsp/recipes-support/mfgtool-files/mfgtool-files/imx8mp-lpddr4-evk/full_image.uuu.in
- meta-lmp-bsp/recipes-support/mfgtool-files/mfgtool-files/imx8mq-evk/full_image.uuu.in
- meta-lmp-bsp/recipes-support/mfgtool-files/mfgtool-files/imx8qm-mek-sec/full_image.uuu.in
- meta-lmp-bsp/recipes-support/mfgtool-files/mfgtool-files/imx8qm-mek/full_image.uuu.in
- meta-lmp-bsp/recipes-support/mfgtool-files/mfgtool-files/imx8ulp-lpddr4-evk/full_image.uuu.in
- meta-lmp-bsp/recipes-support/mfgtool-files/mfgtool-files/imx93-11x11-lpddr4x-evk/full_image.uuu.in
Use the compressed image. It reduces one step for the flashing process and makes the flashing time a little quicker.
> mfgtool-files: Use compressed image for the full_image script

- meta-lmp-base/recipes-support/docker-credential-helper-fio/files/docker-credential-fio-helper
Normally `/var/sota/sota.toml` has had TOML with no indentation. eg: 
```
[section]
key=val
```
There are situations where /var/sota/sota.toml can be indented:
```
[section]
key=val
```
This changes our regular expression to handle either one. Discovered while testing meds.
> base: docker-credential-helper: Handle leading spaces

- meta-lmp-base/recipes-kernel/linux/kmeta-linux-lmp-6.1.y.inc
- meta-lmp-bsp/recipes-kernel/linux/linux-lmp-fslc-imx-rt/0001-FIO-extras-arm64-dts-imx8mm-evk-use-imx8mm-evkb-for-.patch
- meta-lmp-bsp/recipes-kernel/linux/linux-lmp-fslc-imx-rt/0001-FIO-internal-arch-arm64-dts-imx8mp-enable-I2C5-bus.patch
- meta-lmp-bsp/recipes-kernel/linux/linux-lmp-fslc-imx-rt/mx8mn-nxp-bsp/0001-FIO-internal-arm64-dts-imx8mn-evk.dtsi-re-add-blueto.patch
- meta-lmp-bsp/recipes-kernel/linux/linux-lmp-fslc-imx-rt_6.1.bb
- meta-lmp-bsp/recipes-kernel/linux/linux-lmp-fslc-imx_6.1.bb
NXP commits change chunks used in fio patches, so this solution shadows incompatible patches for `linux-lmp-fslc-imx` by updated ones for `linux-lmp-fslc-imx-rt`.
Tested on imx8mm-evkb.
> Update linux-lmp-fslc-imx-rt to nxp real-time-edge version

- meta-lmp-base/recipes-containers/nerdctl/nerdctl_git.bb
- meta-lmp-base/recipes-containers/nerdctl/nerdctl_git.bbappend
This reverts commit dd33a569bd0ab62552f7dcaf2590f6a081f88f92.
> Revert "base: nerdctl: install the binaries in OE standard places"

- meta-lmp-base/recipes-support/lmp-el2go-auto-register/lmp-el2go-auto-register/lmp-el2go-auto-register
On a device running a dockerless LmP with EdgeLock 2GO [1], the "aktualizr-lite" was failing and exiting with an error message:
`aktualizr-lite[991]: boost::filesystem::canonical: No such file or directory [generic:2]: "/usr/bin/docker"`
We could trace the error in "`aktualizr-lite`": it happens only when "`aktualizr-lite`" tried to upgrade the "compose apps" on a dockerless system. But "`aktualizr-lite`" can work: while our device is dockerless, we could register it manually with "`lmp-device-register`" and upgrade the firmware with "`aktualizr-lite`".
The difference between the successfull "`aktualizr-lite`" when manually registering the device and the error mentioned above is the use of EdgeLock 2GO (el2go). The "`lmp-el2go-auto-register`" script [2] starts the EdgeLock 2GO agent and …
> lmp-el2go-auto-register: allow to disable "composeapp"

- meta-lmp-base/recipes-containers/docker/docker-ce_%.bbappend
- meta-lmp-base/recipes-containers/docker/files/0001-tarexport-optimize-image-loading-on-local-host.patch
This patch helps to improve the image loading process that occurs at the App installation step. Specifically, image layers are not copied from the skopeo/OCI store to the docker temporal directory before their extraction to the docker store.
Instead, image layers are read directly from the skopeo store.
Also, this patch fixes a few minor issues the loader/tarexporter implementation.
To leverage the patch [this change to aklite](https://github.com/foundriesio/aktualizr-lite/pull/273. should be utilized.
> base: rc: Patch docker to load image optimally

- meta-lmp-base/classes/uboot-fitimage.bbclass
The SYS_TEXT_BASE is renamed to TEXT_BASE. Improve a grep regex to cover both legacy and new name. This fixes the bug [1] in u-boot.itb that leads to load u-boot over the SPL and causes a crash [2].
[1]
...
Image 0 (uboot)
Description:  U-Boot no-dtb
...
Load Address: 0x00000000
Entry Point:  0x00000000
...
[2]
U-Boot SPL 2023.04+fio+g3ffd209fa1 (Sep 27 2023 - 13:31:56 +0000) ...
"Error" handler, esr 0xbf000002
elr: 00000000007ed498 lr : 00000000007e48b0
x 0: 0000000000000000 x 1: 00000000400ac090
x 2: 00000000000aa360 x 3: 0000000000000008
x 4: 0000000040200000 x 5: 00000000000aa4b4
x 6: 0000000000000002 x 7: 0000000000187a4c
x 8: 00000000400abfc0 x 9: 0000000000000002
x10: 00000000000aa4b8 x11: 0000000000187a6c
x12: 00000000400abfc0 x13: 00000000400abfc0
x14: 000000004e577609 x15: …
> base: uboot-fitimage: fix getting TEST_BASE address

- meta-lmp-base/recipes-sota/lmp-device-register/lmp-device-register_git.bb
Changes:
- 2557b25 main: improve cleanup mechanism
- 24ef2ed main: cleanup created PKCS11 keys on registration errors
- 8b7f3a3 main: add --force option to allow cleanup of previous execution data
- d281ad3 pkcs11: disable get_uuid HSM error messages
- f502b66 options: validate HSM path
> base: lmp-device-register: bump to 2557b25

- meta-lmp-base/recipes-bsp/u-boot/u-boot-fio-mfgtool_imx-2023.04.bb
- meta-lmp-base/recipes-bsp/u-boot/u-boot-fio_imx-2023.04.bb
Introduce FIO-specific recipes based on the NXP u-boot release lf-6.1.22-2.0.0.
> base: u-boot-fio: add recipe for imx-2023.04

- meta-lmp-base/classes/uboot-fitimage.bbclass
Automatically add LMP_BOOT_FIRMWARE_VERSION to SPL DTB, if SPL build is enabled in U-Boot.
> base: uboot-fitimage: add boot firmware version to spl dtb

- meta-lmp-base/recipes-sota/aktualizr/aktualizr/aktualizr-lite.service.in
In order for the `docker compose` commands to be executed correctly from within `aktualizr` the `$HOME` environment variable needs to be present. This can be done in two ways, either we add the HOME environment variable to the already existing `Environment=` settings or we set the `User`. 
All code in golang, so far as I have seemed to determine, uses the `$HOME` to determine the user home directory through methods like `UserHomeDir`. 
There are two other ways to get the data, one is through `os.user.Lookup`/`os.user.LookupId` and the other is `user.Current()`. Meaning we could also patch the `docker compose` code in order to use this particular method rather than setting a hardcoded user.
> fix(aktualizr): Add User to Unit file

- meta-lmp-base/recipes-support/fioconfig/fioconfig_git.bb
Just update the reference for `fioconfig` to make it so that when you remove overrides from `z-50-fioctl.toml` it will relinquish control back to whatever is in `/var/sota/sota.toml`.
@rsalveti can you verify all is in order?
> chore(fioconfig): Revert back when ommitting tag

- meta-lmp-bsp/dynamic-layers/meta-ti-bsp/recipes-support/ti-mfgtool-files/ti-mfgtool-files/flash.sh.in
- Add DFU signatures to binaries before flashing. This addresses this issue:
dfu-util: Invalid DFU suffix signature
dfu-util: A valid DFU suffix will be required in a future dfu-util release!!!
- Add additional return code handling to make script more fault-tolerant.
- Increase sleep after last fastboot continue invocation, so ums cmd has enough time to expose eMMC to host pc.
- Suppress "dfu-util: unable to read DFU status after completion" error, as it doesn't have any negative impact.
> bsp: dynamic-layers: ti-mfgtool-files: improve flash.sh

- meta-lmp-base/recipes-bsp/u-boot/u-boot-fio_imx-2023.04.bb
- c9892f0ea8a [FIO toup] fastboot: fb_fsl: add support for imx8mp and imx8mn
- a36dfbf2250 [FIO internal] common: support bootfirmware info in spl
- 8a9f935ae6c [FIO toup] board: freescale: mx6ul_14x14_evk: make DM-base serial driver work in SPL
- 0f33abed90b [FIO toup] arm: dts: imx6ul-14x14-evk-u-boot: enable uart1 in SPL
- 1c58c47b282 [FIO toup] board: freescale: mx6ullevk: make DM-base serial driver work in SPL
- f8736e83164 [FIO toup] arm: dts: imx6ull-14x14-evk-u-boot: enable uart1 in SPL
- 5534200c799 [FIO toup] board: mx6ullevk: add early UART pinmux initialization
> base: u-boot-fio: imx-2023.04: bump to c9892f0ea8a

- meta-lmp-base/dynamic-layers/tpm-layer/recipes-tpm2/tpm2-tss/tpm2-tss/fixup_hosttools.patch
Quiet a warning in Layer Index update check:
WARNING: Invalid upstream status in /opt/workdir/https___github_com_foundriesio_meta-lmp/meta-lmp-base/dynamic-layers/tpm-layer/recipes-tpm2/tpm2-tss/tpm2-tss/fixup_hosttools.patch: Upstream-Status: OE [inappropriate]
https://docs.yoctoproject.org/contributor-guide/recipe-style-guide.html#patch-upstream-status
> tpm2-tss: fix Upstream-Status of patch

- meta-lmp-base/recipes-bsp/u-boot/u-boot-fio_imx-2022.04.bb
- 605d0aa5c0 [FIO toup] fastboot: fb_fsl: add support for imx8mp and imx8mn
- bb09b00e62 [FIO internal] common: support bootfirmware info in spl
> base: u-boot-fio: imx-2022.04: bump to 605d0aa5c0

- meta-lmp-base/recipes-sota/aktualizr/aktualizr_%.bbappend
- b38db4c offline: Don't allow downgrade by default
- df9aa8f offline: Fix --log-level option
- d1cfcb4 offline: Add sub-command to check update source dir
- 1efffdc offline: Add "current" subcommand
> base: rs: aktualizr: Bump aklite ver to 2afacef

- meta-lmp-bsp/conf/machine/include/lmp-machine-custom.inc
The value defined on meta-ti prevails so we need to change this not only when sota is enabled but always.
This affects mfgtool-am62xx-evm after lmp-signing.bbclass was merged because teh keys defined in TI bsp not found:
```
ERROR: /lmp/build-lmp-mfgtool-am62xx-evm-initrd-rebuild-container/conf/../../layers/meta-lmp/meta-lmp-bsp/recipes-kernel/linux/linux-lmp-fslc-imx-xeno4_git.bb: SIGNING_UBOOT_SIGN_KEY=${TI_SECURE_DEV_PKG}/keys/ubootdev.key is not a file.
ERROR: /lmp/build-lmp-mfgtool-am62xx-evm-initrd-rebuild-container/conf/../../layers/meta-ti/meta-ti-bsp/recipes-kernel/linux/linux-ti-staging-systest_5.10.bb: SIGNING_UBOOT_SIGN_KEY=${TI_SECURE_DEV_PKG}/keys/ubootdev.key is not a file.
ERROR: /lmp/build-lmp-mfgtool-am62xx-evm-initrd-rebuild-container/conf/../../layers/meta-ti/meta-ti-bs …
```
> bsp: lmp-machine-custom: remove sota override from UBOOT_SIGN_KEYDIR in k3

- meta-lmp-base/conf/layer.conf
To avoid rebuilding any package that depends on base-files-issue
when it changes.
> base: layer.conf: add base-files-issue to SIGGEN_EXCLUDERECIPES_ABISAFE

- meta-lmp-bsp/recipes-support/mfgtool-files/mfgtool-files/imx8qm-mek-sec/close.uuu
- meta-lmp-bsp/recipes-support/mfgtool-files/mfgtool-files/imx8qm-mek-sec/fuse.uuu
"reboot" command is not available for apalis-imx8 u-boot,
so replace it with "reset".
> bsp: support: mfgtool-files: imx8qm-mek: replace "reboot" command

- meta-lmp-base/recipes-support/lmp-el2go-auto-register/lmp-el2go-auto-register/lmp-el2go-auto-register
This PR makes various improvements to lmp-el2go-auto-register. The main goal is to make it more useful for a subscriber who wants to use EdgeLock 2GO to manage their own secure objects.
Currently only two secure objects are handled: Foundries and AWS IoT. The mechanism used for AWS IoT can however easily be applied more generically to any keypair and certificate that a subscriber wants to provision through EdgeLock 2GO. 
Subscriber keypairs may use an algorithm other than P-256, so support for that is added as well. However, this part is largely untested - in the end we used P-256 after all, so I didn't get around to test all the others, and our SE050 variant doesn't support P-384 and P-521.
We happen to use OID 0x5010 in our tests, and it turns out that the processing of labels didn't …
> lmp-el2go-auto-register: enable generic usage for subscriber secure objects

- meta-lmp-bsp/recipes-kernel/linux/linux-lmp-fslc-imx/0001-FIO-extras-arm64-dts-imx8mm-evk-use-imx8mm-evkb-for-.patch
Upstream dts changes caused the evkb model to also be included in the evka dts file, causing a bug at userspace when trying to identify if hciattach should be executed or not (as it depends on evkb).
> bsp: linux-lmp-fslc-imx: imx8mm-evk: fix compatible node on evka

- meta-lmp-base/conf/distro/include/lmp.inc
Mask gcc-source_12.3.bbappend instead of gcc-source_12.2 after the latest updates in meta-st-stm32mp layer.
> base: distro: mask gcc-source_12.3

- meta-lmp-base/conf/distro/include/non-clangable.inc
Similar to imx-atf (named differently due SoC differences but same source).
> base: non-clangable: add qoriq-atf

- meta-lmp-bsp/recipes-core/base-files/base-files/am62xx-evm/fstab
- meta-lmp-bsp/recipes-core/base-files/base-files/am64xx-evm/fstab
- meta-lmp-bsp/recipes-core/base-files/base-files/beaglebone-yocto/fstab
- meta-lmp-bsp/recipes-core/base-files/base-files/beagleplay/fstab
- meta-lmp-bsp/recipes-core/base-files/base-files/imx6ulevk/fstab
- meta-lmp-bsp/recipes-core/base-files/base-files/imx6ullevk/fstab
- meta-lmp-bsp/recipes-core/base-files/base-files/imx7ulpea-ucom/fstab
- meta-lmp-bsp/recipes-core/base-files/base-files/imx8mm-lpddr4-evk/fstab
- meta-lmp-bsp/recipes-core/base-files/base-files/imx8mn-ddr4-evk/fstab
- meta-lmp-bsp/recipes-core/base-files/base-files/imx8mn-lpddr4-evk/fstab
- meta-lmp-bsp/recipes-core/base-files/base-files/imx8mp-lpddr4-evk/fstab
- meta-lmp-bsp/recipes-core/base-files/base-files/imx8mq-evk/fstab
- meta-lmp-bsp/recipes-core/base-files/base-files/imx8qm-mek/fstab
- meta-lmp-bsp/recipes-core/base-files/base-files/imx8ulp-lpddr4-evk/fstab
- meta-lmp-bsp/recipes-core/base-files/base-files/imx93-11x11-lpddr4x-evk/fstab
- meta-lmp-bsp/recipes-core/base-files/base-files/k26/fstab
- meta-lmp-bsp/recipes-core/base-files/base-files/qemuarm/fstab
- meta-lmp-bsp/recipes-core/base-files/base-files/qemuarm64/fstab
- meta-lmp-bsp/recipes-core/base-files/base-files/qemuriscv64/fstab
- meta-lmp-bsp/recipes-core/base-files/base-files/rpi/fstab
- meta-lmp-bsp/recipes-core/base-files/base-files/sun8i/fstab
- meta-lmp-bsp/recipes-core/base-files/base-files/uz/fstab
Enable file system check on boot mounts by default to avoid corrupted vfat partitions that can later block the boot process.
> bsp: base-files: fstab: enable file system check on boot

- meta-lmp-bsp/conf/machine/include/lmp-machine-custom.inc
The commit cb51e303 removes the sota override but also inadvertently the weak assinged.
Restore the weak assinged so that is possible to use the '=' to override this defenitions on the factory.
> bsp: lmp-machine-custom: UBOOT_SIGN_KEYDIR for TI k3 should be weak assinged

- meta-lmp-bsp/dynamic-layers/freescale-layer/recipes-bsp/imx-atf/imx-atf/0001-plat-imx8m-obtain-boot-set-from-bootrom-even-log.patch
- meta-lmp-bsp/dynamic-layers/freescale-layer/recipes-bsp/imx-atf/imx-atf_%.bbappend
- meta-lmp-bsp/recipes-bsp/u-boot/u-boot-ostree-scr-fit/imx8mn-ddr4-evk/boot.cmd
- meta-lmp-bsp/recipes-bsp/u-boot/u-boot-ostree-scr-fit/imx8mn-lpddr4-evk/boot.cmd
- meta-lmp-bsp/recipes-bsp/u-boot/u-boot-ostree-scr-fit/imx8mp-lpddr4-evk/boot.cmd
These changes switched to usage of `imx_secondary_boot` U-Boot cmd for detecting primary/secondary boot instead of previous mock solution.
> i.MX8MN/MP secondary boot detection

- meta-lmp-bsp/dynamic-layers/freescale-layer/recipes-bsp/imx-atf/imx-atf/0001-plat-imx8m-obtain-boot-set-from-bootrom-even-log.patch
Fix this build issue on some machines:
| plat/imx/imx8m/gpc_common.c:365:13: error: 'is_secondary_boot' defined but not used [-Werror=unused-function]
> bsp: dynamic-layers: imx-atf: fix build issue

- meta-lmp-base/recipes-support/fioconfig/fioconfig_git.bb
Pulls in fix to allow fioconfig to recover from a corrupted copy of the config file on disk.
> base: fioconfig: Bump version

- meta-lmp-base/recipes-support/lmp-el2go-auto-register/lmp-el2go-auto-register.bb
The files `default.env` and `root.crt` are placeholders to be replaced with the user configurations in downstream layers.
> base: lmp-el2go-auto-register: re-add default.env and root.crt placeholders

- meta-lmp-base/conf/distro/lmp.conf
- meta-lmp-base/recipes-bsp/u-boot/u-boot-ostree-scr-fit.bb
- meta-lmp-base/recipes-bsp/u-boot/u-boot-ostree-scr-fit/boot-header.cmd.in
Add LMP_ROLLBACK_PROTECTION_ENABLE variable for enabling rollback protection during build time.
If it is set U-Boot boot.cmd script will automatically force enable rollback protection during first run.
> base: u-boot-ostree-scr-fit: add var for enabling rb protection

- meta-lmp-base/classes/lmp-staging.bbclass
When we have more than one mirror it will be good to remove extra spaces and tabs.
> base: lmp-staging: lmp_sstate_checkhashes: remove multiple spaces

- meta-lmp-bsp/dynamic-layers/freescale-layer/recipes-bsp/imx-mkimage/imx-boot_%.bbappend
**NOTE, this change is backward compatible so we can apply these changes without bumping meta-freescale.**
The new version of imx-boot uses both signed_hdmi and signed_dp firmware for imx8m. Install them both.
> bsp: imx-boot: install all signed fw

- meta-lmp-base/classes/lmp.bbclass
Without this change lmp-base distro fails to build and other without sota DISTRO_FEATURES will still fail the same way.
> base: lmp: ota-esp is only needed when sota is enabled

- meta-lmp-base/recipes-core/initrdscripts/initramfs-module-install-efi/init-install-efi.sh
- meta-lmp-base/recipes-core/initrdscripts/initramfs-module-install-efi_%.bbappend
Use [1] to test.
I created one commit with the changes of the install script only to make it easier to review what the script was and how it is changed. The goal is to have this squashed before the merge.
Also, I created a new recipe and a new package name to make sure we can switch in the class file, however, there might be other better ways, I thought it is only simpler.
[1] https://docs.foundries.io/latest/reference-manual/linux/linux-wic-installer.html#testing-wic-image-installer-with-qemu-x86
> Lmp disable gplv3 init install efi

- meta-lmp-base/recipes-support/mfgtool-files/mfgtool-files_0.1.bb
New features:
- Add built spinand command support
- parser [-t timeout] for all protocol
Fixes:
- force use old libusb to run at ubuntu 18.04
- Hot Fixed for SPDS crash for some images
> base: mfgtool-files: update UUU 1.5.109 -> 1.5.141

- meta-lmp-bsp/dynamic-layers/freescale-layer/recipes-bsp/imx-atf/imx-atf/0001-Revert-MA-20141-imx8m-enable-alarm-when-shutdown.patch
- meta-lmp-bsp/dynamic-layers/freescale-layer/recipes-bsp/imx-atf/imx-atf_%.bbappend
Current logic in imx-atf configures SNVS_LP Control Register to generate a wakeup alarm after power-down, so poweroff works the same as reboot.
Revert the patch 4fe65a006b2 ("MA-20141 imx8m: enable alarm when shutdown") in imx-atf that introduces this behavior.
> bsp: dynamic-layers: imx-atf: adjust power off logic

- meta-lmp-base/recipes-sota/custom-sota-client/files/systemd.service
In order for the `docker compose` commands to be executed correctly from within the custom sota client the `$HOME` environment variable needs to be present.
This can be done in two ways, either we add the HOME environment variable to the already existing `Environment=` settings or we set the `User`.
> base: rs: custom-sota-client: Add User to Unit file

- meta-lmp-base/classes/fip-utils.bbclass
The default `DEPLOY_DIR_IMAGE` value are `${DEPLOY_DIR}/images/${MACHINE}` so switch to that.
> base: fip-utils: use the DEPLOY_DIR_IMAGE

- meta-lmp-base/conf/distro/include/non-clangable.inc
Add optee-examples to the list of optee related recipes which should all be aligned with gcc.
> base: non-clangable: add optee-examples

- meta-lmp-base/recipes-support/compose-apps-early-start/compose-apps-early-start/compose-apps-early-start.service
The way customers use this feature means that it can be several reboots before the device is registered. The early-start was running on every boot which causes delays in startup. This makes it so it only runs once and on all subsequent reboots dockerd will start the containers.
> recipes-support: make early-start only run to completion once

- meta-lmp-bsp/recipes-bsp/trusted-firmware-a/tf-a-fio-st.inc
```
The ft-a-fio deploy task does optionally sign the tf-a using the
ST STM32MP Signing Tool. However, if it is invoked due to some
other dependent recipe change when the previous signed files already
exist, it reports that the destination file already exists and asks
for confirmation:
Do you want to replace this file: .../tf-a-stm32mp157c-dk2-sdcard_Signed.stm32 ? (y/n)
This keeps to be generated until all memory is exhausted and then it
ends with an error.
Fix the issue by removing the old file in advance before signing, as
signing tool doesn't have a cmdline option to replace the file.
Fixes: https://github.com/igoropaniuk/meta-lmp/commit/11fa2be280fb83933f3d70471aeb8d700ad700c3("bsp: tf-a-fio: add signing support for stm32mp15-disco-sec")
Signed-off-by: Igor Opaniuk …
```
> bsp: tf-a-fio: st: remove old signed binary before signing

- meta-lmp-base/recipes-security/optee/optee-os-fio_3.21.0.bb
- 33d9bf3fc [FIO toup] drivers: se050: disable SM2_* when enabled
> base: optee-os-fio: 3.21: bump to 33d9bf3fc

- meta-lmp-bsp/wic/sdimage-stm32mp157c-dk2-optee.wks.in
It's not possible to specify size prefix for --align option, it's by default in KBytes. Fix this error:
Fix sdimage-stm32mp157c-dk2-optee.wks:20: argument --align: invalid int value: '4096K'
Fixes: 1e1897d0dc("bsp: wic: stm32mp1: wks file improvements")
> bsp: wic: stm32mp15: fix align param

- meta-lmp-base/conf/distro/include/lmp.inc
Don't remove/keep ext4 image in deploy folder, as it might be needed by other scripts responsible for flashing a target.
> base: distro: lmp: keep ext4 image

- meta-lmp-base/conf/distro/include/non-clangable.inc
Kernel module needs to be aligned with the toolchain used by the main kernel, which is gcc.
> base: non-clangable: add nvidia-display-driver

- meta-lmp-base/recipes-sota/aktualizr/aktualizr_%.bbappend
- 838e53c dockerclient: Calculate archive size correctly
- 6fda4d5 dockerclient: Handle tar creation errors
> Fix the aklite image loading issue for v92 (base: rs: Bump aklite with fix for v92 838e53c)

- meta-lmp-base/recipes-support/luks-reencryption/luks-reencryption/luks-reencryption
Assume the first luks device is the rootfs, the one requiring on-line reencryption.
> base: luks-reencryption: stop on first luks match

- meta-lmp-base/recipes-containers/composeapp/composectl_git.bb
- 06800ca statfs: Convert block size to 64 bit explicitly
> Fix composectl for 32 bit machines (base: rc: composectl: Bump version 06800ca)

- meta-lmp-base/recipes-sota/aktualizr/aktualizr_%.bbappend
The new utility is rather like `skopeo` not `aklite-apps` so no need to have the package config for it.
> base: rs: aktualizr: Remove composectl from packageconfig

- meta-lmp-base/recipes-containers/composeapp/composectl_git.bb
- 5419dab check: Use read-only store to copy from local store
> base: rc: composectl: Bump version 5419dab

- meta-lmp-bsp/dynamic-layers/stm-st-stm32mp/recipes-support/stm32-mfgtool-files/stm32-mfgtool-files_0.1.bb
Use ':' separator instead of '/' for sed 's' command, as for example LMP_MFGTOOL_FLASHLAYOUT value itself might also have slashes.
Fixes: 91eb22094("bsp: lmp-mfgtool: provide dynamic configuration for flashlayout class")
> bsp: dynamic-layers: stm32-mfgtool-files: change sed separator

- meta-lmp-base/classes/lmp-signing.bbclass
The task flag vardeps can be empty and in this case it is none.
Consequently this means that we cannot add anything to the task vardeps when it is empty.
We should also match any full string present on vardeps and not sub-strings so varname_hash should be checked on vardeps list and not string.
> base: lmp-signing: fix append when vardeps is none

- meta-lmp-bsp/dynamic-layers/stm-st-stm32mp/recipes-support/stm32-mfgtool-files/stm32-mfgtool-files_0.1.bb
This reverts commit 7600a79bd17504c0544a8bd5152740def380f884.
I have tested this localy and it works without the do_compile[vardeps] and so the do_compile task runs when the LMP_MFGTOOL_FLASHLAYOUT or LMP_FLASHLAYOUT_BOARD_NAME change.
> Revert "bsp: stm32-mfgtool-files: keep track of the variables used"

- meta-lmp-bsp/dynamic-layers/tegra/recipes-containers/libnvidia-container/libnvidia-container_1.10.0.bbappend
Unblock meta-tegra bump and can be reverted when https://github.com/OE4T/meta-tegra/pull/1456 was merged
> base: libnvidia-container: rdepend on tegra-libraries-cuda

- meta-lmp-base/recipes-security/optee/optee-os-fio_3.21.0.bb
- 6120b1aa3 Revert "[FIO toup] drivers: se050: disable SM2_* when enabled"
- 70ef5c34e [FIO fromtree] crypto: se050: ecc: allow software fallback on key allocation requests
- 9e31f457a [FIO fromtree] crypto_api: acipher: ecc key allocation API, pass the key type
> base: optee-os-fio: 3.21: bump to 6120b1aa3bb

- meta-lmp-bsp/dynamic-layers/tegra/recipes-bsp/tegra-binaries/tegra-helper-scripts/initrd-flash.sh
Includes:
- e034e0e2 initrd-flash: set pipefail option
https://github.com/OE4T/meta-tegra/commit/e034e0e271dea2e0f51a55e11fcf881ef0e675e5
https://github.com/OE4T/meta-tegra/pull/1458
- f8cb5c6a initrd-flash.sh: ensure substitution for DTB_FILE
https://github.com/OE4T/meta-tegra/commit/f8cb5c6ad2617755f5cb74f85a1b0b2cd6380f6c
https://github.com/OE4T/meta-tegra/pull/1453
> bsp: tegra-helper-scripts: update initrd-flash.sh fork with lastest changes

- recipes-sota/aktualizr/aktualizr-callback/90-handle-callback.toml
- recipes-sota/aktualizr/aktualizr-callback/callback-handler
- recipes-sota/aktualizr/aktualizr-callback_1.0.bb
Customers are not always ready to tackle a custom SOTA client and only want simple hold off of a step of the updating.
This adds a simple recipe that sets up a callback handler as an option other that using aktualizr-lite CLI or a custom client.
> base: aktualizr-callback: add a callback handler example

- meta-lmp-bsp/dynamic-layers/tegra/recipes-containers/libnvidia-container/libnvidia-container_1.10.0.bbappend
This reverts commit 49c2b20a0e8d37239ee0410d5cbcc39e041e4c77.
Part of meta-tegra kirkstone ece7adfd9527a3edcc26a4855498e54fdee1ec56.
> Revert "bsp: libnvidia-container: rdepend on tegra-libraries-cuda"

- meta-lmp-base/recipes-support/lmp-device-auto-register/lmp-device-auto-register.bb
- meta-lmp-base/recipes-support/lmp-device-auto-register/lmp-device-auto-register/lmp-device-auto-register
- meta-lmp-base/recipes-support/lmp-device-auto-register/lmp-device-auto-register/lmp-device-auto-register.service.in
This patch enables lmp-device-auto-register to use /etc/hostname as FoundriesFactory device registration name. It is done by setting build time variable LMP_AUTO_REGISTER_USE_HOSTNAME. If this variable is empty lmp-device-auto-register will use randomly generated UUID.
> meta-lmp-base: allow lmp-device-auto-register to use hostname

- meta-lmp-base/recipes-sota/aktualizr/aktualizr_%.bbappend
- meta-lmp-base/recipes-sota/custom-sota-client/custom-sota-client_git.bb
- Add offline update support to the public API
- Move the `aklite-offline` to the public API usage
- Extend the custom-sota-client example with sub-commands to perform CLI-based update for both online and offline update.
> Bump aklite version to b2140a5

- meta-lmp-base/recipes-support/lmp-device-auto-register/lmp-device-auto-register/lmp-device-auto-register
This patch allows to auto-register with a subset of apps by setting APPS variable in the service environment.
> meta-lmp-base: allow apps selection for lmp-device-auto-register

- meta-lmp-base/conf/layer.conf
This patch is a follow-up of 24d1016e, the initramfs-ostree-lmp-recovery is used on the machine qemuarm64-secureboot and without this patch the initramfs is rebuilded which consequently triggers a kernel rebuild.
> base: layer.conf: exclude os-release siggen dependencie on the initramfs ostree-lmp-recovery

- meta-lmp-base/recipes-sota/aktualizr/aktualizr_%.bbappend
- meta-lmp-base/recipes-sota/custom-sota-client/custom-sota-client_git.bb
- bd52b57 api, cli, liteclient: Distinguish different checkin errors
- 54a5320 tuf: Move MetadataNotFoundException to tuf.h
> base: rs: aktualizr: Bump version to 95ecfb8

- meta-lmp-base/recipes-containers/docker/files/docker.service
The reboot action was done as a way to validate that docker remains functional after an OTA is performed, but in the end it can trigger a reboot loop in case of normal container/docker/volume errors, which is not ideal.
The proper way to validate that the job is healthy after an update should be done outside the normal unit service operation mode.
> base: docker: drop reboot action in case of failures

- meta-lmp-bsp/recipes-bsp/trusted-firmware-a/tf-a-fio-st.inc
Fix image deploy path which is used STM32_ROT_SIGN_ENABLE is enabled.
> bsp: tf-a-fio-st: fix fip image deploy path

- meta-lmp-base/recipes-kernel/linux/linux-lmp-dev-mfgtool_git.bb
- meta-lmp-bsp/recipes-kernel/linux/linux-lmp-fslc-imx_6.1.bb
Update branch and stable-base version to include the lf-6.1.55-2.2.0 tag.
> bsp: linux-lmp-fslc-imx: update to include the lf-6.1.55-2.2.0 tag

- meta-lmp-base/recipes-core/systemd/systemd_%.bbappend
Replace time4.google.com with pool.ntp.org in order to have at least one entry specific to the most commonly used ntp server.
> base: systemd: add pool.ntp.org to the ntp fallback list

- meta-lmp-base/recipes-kernel/linux/kmeta-linux-lmp-6.1.y.inc
- cd8a7b95 bsp: imx: imx8ulp: fix enabling I2C_IMX_FLEXIO
> base: kmeta-linux-lmp-6.1.y: bump to cd8a7b95

- meta-lmp-bsp/dynamic-layers/meta-ti-bsp/recipes-kernel/linux/linux-lmp-ti-staging_git.bb
Use the same URL that is on meta-ti/meta-ti-bsp/recipes-kernel/linux/linux-ti-staging_6.1.bb
This was causing some troubles on main-next:
```
ERROR: linux-lmp-ti-staging-6.1.69+git-r0 do_unpack: Bitbake Fetcher Error: UnpackError('No up to date source found: clone directory not available or not up to date: /srv/oe/downloads/git2/git.ti.com.ti-linux-kernel.ti-linux-kernel.git; shallow clone not enabled', 'git://git.ti.com/ti-linux-kernel/ti-linux-kernel.git;protocol=https;branch=ti-linux-6.1.y;name=machine;')
```
> bsp: linux-lmp-ti-staging: fix KERNEL_REPO

- meta-lmp-bsp/conf/machine/include/lmp-machine-custom.inc
Install tegra-redundant-boot binaries, needed for handling A/B boot firmware updates.
> bsp: tegra: install tegra-redundant-boot

- meta-lmp-bsp/dynamic-layers/freescale-layer/recipes-graphics/cairo/cairo_1.16.0.bbappend
The commit [1] breaks compatibility with cairo < 1.18. LmP is still based on OE kirkstone, that uses cairo 1.16. Return back compatibility.
[1]
commit 0e478bde ("cairo: Drop the removed packageconfigs")
> bsp: freescale: cairo: fix compatibility with 1.16

- meta-lmp-base/recipes-support/mfgtool-files/mfgtool-files_0.1.bb
=== New feature
* Provide macos arm prebuild version.
* Support i.MX91
* Support yocto bmap file to skip unused block
* Support i.MX95
==== Bug fixes
* Fixed a crash with -d option when change back file.
* Static link tinyxml to avoid difference version ubuntu tinyxml version mismatch problem.
* Fixed usb pipe error when download image with FCB
> mfgtool-files: upgrade to 1.5.179

- meta-lmp-base/classes/lmp-staging.bbclass
- meta-lmp-bsp/conf/machine/include/lmp-machine-custom.inc
We need to support kernel versions with and without vendor subdirs
for arm architecture dts files. Replace a static prefix with a
dynamic one set according to a kernel version.
> linux-lmp: refix setting a subdir for dts files

- meta-lmp-base/recipes-graphics/wayland/weston-init/lmp-wayland/weston.service.patch
It's a patch to configure the behavior, so it's not supposed to be upstreamed.
> base: weston-init: Add Upstream-Status

- meta-lmp-base/recipes-containers/composeapp/composectl_git.bb
- meta-lmp-base/recipes-sota/aktualizr/aktualizr_%.bbappend
- Add callback support to the offline updater.
- Add bundle metadata support to the offline updater. The bundle metadata are signed by TUF targets role key and contains description of the bundle, i.e. tag, bundle targets, whether it is prod or CI bundle, etc. The offline updater checks the bundle metadata signature and use information found in it to determine whether an update should be permitted, possible, and what targets can be installed.
- Move app functionality to check whether app is fetched, installed, and running from aklite to composectl.
> Bump aklite and composectl

- meta-lmp-base/recipes-security/optee/optee-sks_git.bb
- 048c0ca sks: improve attribute size handling
- 22331ae ta: sks: use template class in in create_attributes_from_template
> base: optee-sks: bump to 048c0ca

- meta-lmp-base/recipes-core/systemd/systemd_%.bbappend
There is no reason anymore to keep using cgroupv1 (every component using cgroups is already v2 compatible), so switch to v2 by default, as done on every major linux distribution.
https://github.com/opencontainers/runc/blob/main/docs/cgroup-v2.md
> base: systemd: switch to cgroupv2 by default

- meta-lmp-base/recipes-containers/composeapp/composectl_git.bb
- 17796ca Add ability to define a system-wide base config
> base: rc: composeapp: Bump version to 2488a0e

- meta-lmp-base/recipes-containers/composeapp/composectl_git.bb
- f1e3fce root: Add command to print version
Also, switching to the version branch usage. It simplifies bug fixing and their delivering to customers if LmP version goes further.
> base: rc: composeapp: Bump version 5691069

- meta-lmp-base/recipes-support/fioconfig/fioconfig_git.bb
Brings in a fix for v94 to fix a regression with `fioctl config updates`:
https://github.com/foundriesio/fioconfig/commit/62170c1344a7d3651c85354988677b77053d8ea1
> base: fioconfig: Bump for change handler fix

- meta-lmp-bsp/conf/machine/include/lmp-machine-custom.inc
Set OSTREE_DEPLOY_USR_OSTREE_BOOT for K3 machines only when LUKS is enabled.
> bsp: k3: conditionally copy boot artifacts to boot

- meta-lmp-base/dynamic-layers/tpm-layer/recipes-tpm2/tpm2-tss/tpm2-tss_4.0.1.bb
Upstream removed gcrypt backend as part of the 3.0.0 release (https://github.com/tpm2-software/tpm2-tss/pull/1781), but it was not removed from the recipe during the update.
Also sent to meta-security: https://lists.yoctoproject.org/g/yocto-patches/message/361
> base: tpm2-tss: drop libgcrypt

- meta-lmp-bsp/conf/machine/include/lmp-machine-custom.inc
Using the DEFAULT_PREFERENCE on the meson_0.63.3.imx.bb does not work in this case because
we cannot use the DEFAULT_PREFERENCE to choose versions in lower priority layers,
which are basically almost all of them because we have a very high priority value on the
BBFILE_PRIORITY.
So we need to also set the default PREFERRED_VERSION_meson with the version available
on oe-core because we can't use the DEFAULT_PREFERENCE.
Another issue fixed was the overrides used imx8-nxp-bsp and imx9-nxp-bsp that are not defined
on the IMX bsp layer, we can use the imx-generic-bsp which is common to all IMX.
> bsp: meson: fixup the imx meson backported

- meta-lmp-base/recipes-connectivity/openssh/openssh/CVE-2024-6387.patch
- meta-lmp-base/recipes-connectivity/openssh/openssh_8.9p1.bbappend
sshd(8) in Portable OpenSSH versions 8.5p1 to 9.7p1 (inclusive). Race condition resulting in potential remote code execution. A race condition in sshd(8) could allow remote code execution as root on non-OpenBSD systems. This attack could be prevented by disabling the login grace timeout (LoginGraceTime=0 in sshd_config) though this makes denial-of service against sshd(8) considerably easier. For more information, please refer to the release notes [1] and the report from the Qualys Security Advisory Team [2] who discovered the bug.
[1] https://www.openssh.com/txt/release-9.8
[2] https://www.qualys.com/2024/07/01/cve-2024-6387/regresshion.txt
References:
https://www.openssh.com/security.html
> base: openssh: fix CVE-2024-6387

- meta-lmp-base/recipes-sota/aktualizr/aktualizr_%.bbappend
- 730e3303 appengine: Remove app only from runtime part
- use the release branch v94
> base: rs: Bump aklite to 0271e31b

- meta-lmp-base/recipes-security/optee/optee-fiovb_git.bb
- d659770 Makefile: break build if VENDOR_CREATE is set but no prefix was provided
- ff5c4d1 ta: avoid creating vendor variables with "vendor_" prefix
- e38e905 ta: only create vendor variables if CFG_FIOVB_VENDOR_CREATE is set
> base: optee-fiovb: update to d659770

- meta-lmp-base/recipes-kernel/linux/linux-lmp_6.1.bb
- a2b013d [FIO toup] ARM: dts: stm32mp157c-dk2: add alias for mmc0
> base: linux-lmp: bump revision to a2b013d

- meta-lmp-bsp/conf/machine/include/lmp-machine-custom.inc
Fix the size of u-boot-env partition, which should be 0x4000 as defined in CONFIG_ENV_SIZE, otherwise U-Boot uses the last 0x4000 bytes to place the environment [1].
[1] https://github.com/u-boot/u-boot/blob/v2024.04/env/mmc.c#L124
> bsp: stm32mp15-disco: fix size of u-boot-env partition

- meta-lmp-bsp/dynamic-layers/tegra/recipes-bsp/lmp-boot-firmware/lmp-boot-firmware.bbappend
Add dependency on tegra-uefi-capsules for lmp-boot-firmware on tegra machines.
> bsp: lmp-boot-firmware: tegra: depend on tegra-uefi-capsules

- meta-lmp-base/conf/distro/include/lmp.inc
This reverts commit d4ea7840b0ef58e0cf7ecd518b3be2fd0a166a2a.
Upstream report:
https://github.com/kraj/meta-clang/issues/963
Upstream fix:
https://github.com/kraj/meta-clang/pull/968
> Revert "base: lmp: clang: disable -mbranch-protection=standard"

- meta-lmp-base/conf/distro/include/lmp.inc
Still in main -> kirkstone until we move main further.
> base: lmp: bump version for the 4.0.20 yocto release

- meta-lmp-base/conf/distro/include/lmp.inc
This reverts commit bb1529ab8d239ea176fd20c3a4ce093345f7b1d7.
Fix in meta-clang is not enough for all the clang consumers (e.g. aktualizr).
> Revert "Revert "base: lmp: clang: disable -mbranch-protection=standard""

- meta-lmp-bsp/recipes-kernel/linux/linux-lmp-fslc-imx/0001-FIO-extras-arm64-dts-imx8mm-evk-use-imx8mm-evkb-for-.patch
- meta-lmp-bsp/recipes-kernel/linux/linux-lmp-fslc-imx_6.1.bb
This revision includes the lf-6.1.55-2.2.0 tag.
Refresh patches based on the new kernel rev.
- 1e6abd59ab9ff1 Merge pull request #669 from tq-niebelm/6.1-2.2.x-imx-update-to-lf-6.1.55-2.2.1
- dbc41281fba822 Merge tag 'lf-6.1.55-2.2.1' into 6.1-2.2.x-imx
- de69f223c019fe Merge pull request #659 from tq-niebelm/6.1-2.2.x-imx-ti-sn65dsi83-reverts
- 60fecd90ea6bce Revert "drm/bridge: ti-sn65dsi83: Fix enable/disable flow to meet spec"
- 131f7215711540 Revert "drm/bridge: sn65dsi83: Register and attach our DSI device at probe"
- 8fe2b6682a9340 Revert "drm/bridge: ti-sn65dsi83: Do not cache dsi_lanes and host twice"
- bcb5541dc3a599 Revert "drm/bridge: ti-sn65dsi83: Convert to drm_of_get_data_lanes_count"
- 2bfda7392e6621 Merge pull request #658 from tq-niebelm/6.1-2.2.x-imx
- …
> bsp: linux-lmp-fslc: bump kernel 6.1-2.2.x-imx to 1e6abd59ab9ff1

- meta-lmp-base/recipes-sota/aktualizr/aktualizr_%.bbappend
- meta-lmp-base/recipes-sota/custom-sota-client/custom-sota-client_git.bb
Revert use of `composectl ps` in aklite.
- 3879cfa Revert: "apps: Use `composectl` to check whether app is running"
- f9926c1 Revert: "apps: Use `composectl` to get running apps status"
> base: rs: aktualizr: Bump version to d2cd79e

- meta-lmp-base/recipes-core/initrdscripts/initramfs-framework/cryptfs
Make sure the FS is clean before conversion. Force the fsck
> base: cryptfs: force filesystem check before resize

- meta-lmp-base/recipes-containers/composeapp/composectl_git.bb
- meta-lmp-base/recipes-sota/aktualizr/aktualizr_%.bbappend
- Bump aklite to fix the issue with app installation checking.
- Fix the composectl recipe to enable its version printing.
> Bump aklite v94.1 patch

- meta-lmp-base/recipes-bsp/efitools/efitools/lockdown.conf
- meta-lmp-base/recipes-bsp/efitools/efitools_git.bb
- meta-lmp-bsp/conf/machine/include/lmp-machine-custom.inc
Simplify the Secure Boot key provisioning process by adding a systemd-boot entry wich uses the [efitools](https://github.com/mjg59/efitools.git) EFI program [LockDown.efi](https://github.com/mjg59/efitools/blob/master/LockDown.c).
On selecting that entry, the keys are provisioned after which the system  resets.
Users can then boot into Linux with a secure boot enabled chain.
> base: UEFI Secure Boot Provisioning

- meta-lmp-bsp/recipes-core/base-files/base-files/am62xx-evm/fstab
- meta-lmp-bsp/recipes-core/base-files/base-files/am64xx-evm/fstab
- meta-lmp-bsp/recipes-core/base-files/base-files/beaglebone-yocto/fstab
- meta-lmp-bsp/recipes-core/base-files/base-files/beagleplay/fstab
- meta-lmp-bsp/recipes-core/base-files/base-files/imx6ulevk/fstab
- meta-lmp-bsp/recipes-core/base-files/base-files/imx6ullevk/fstab
- meta-lmp-bsp/recipes-core/base-files/base-files/imx7ulpea-ucom/fstab
- meta-lmp-bsp/recipes-core/base-files/base-files/imx8mm-lpddr4-evk/fstab
- meta-lmp-bsp/recipes-core/base-files/base-files/imx8mn-ddr4-evk/fstab
- meta-lmp-bsp/recipes-core/base-files/base-files/imx8mn-lpddr4-evk/fstab
- meta-lmp-bsp/recipes-core/base-files/base-files/imx8mp-lpddr4-evk/fstab
- meta-lmp-bsp/recipes-core/base-files/base-files/imx8mq-evk/fstab
- meta-lmp-bsp/recipes-core/base-files/base-files/imx8qm-mek/fstab
- meta-lmp-bsp/recipes-core/base-files/base-files/imx8ulp-lpddr4-evk/fstab
- meta-lmp-bsp/recipes-core/base-files/base-files/imx93-11x11-lpddr4x-evk/fstab
- meta-lmp-bsp/recipes-core/base-files/base-files/k26/fstab
- meta-lmp-bsp/recipes-core/base-files/base-files/qemuarm/fstab
- meta-lmp-bsp/recipes-core/base-files/base-files/qemuarm64/fstab
- meta-lmp-bsp/recipes-core/base-files/base-files/qemuriscv64/fstab
- meta-lmp-bsp/recipes-core/base-files/base-files/rpi/fstab
- meta-lmp-bsp/recipes-core/base-files/base-files/sun8i/fstab
- meta-lmp-bsp/recipes-core/base-files/base-files/uz/fstab
Automount[1] the boot partition to minimize vfat partition corruption risks.
This mounts the partition on demand and unmounts after use.
[1] https://www.freedesktop.org/software/systemd/man/latest/systemd.automount.html#
> bsp: core: base-files: automount vfat boot partition

- meta-lmp-base/classes/kernel-lmp-efi.bbclass
Report errors during secure boot sign/verify.
> base: lmp: efi: check for sbsign sbverify errors.

- meta-lmp-base/recipes-support/mfgtool-files/mfgtool-files_0.1.bb
- meta-lmp-bsp/dynamic-layers/meta-ti-bsp/recipes-support/ti-mfgtool-files/ti-mfgtool-files_0.1.bb
- meta-lmp-bsp/dynamic-layers/stm-st-stm32mp/recipes-support/stm32-mfgtool-files/stm32-mfgtool-files_0.1.bb
This will avoid getting the error of using it in unsupported bsp's
> mfgtool-files: make it compatible with specific supported bsp

- meta-lmp-base/recipes-core/initrdscripts/initramfs-framework/cryptfs_tpm2
- meta-lmp-base/recipes-core/initrdscripts/initramfs-framework_%.bbappend
Use efivar to access uefi variables in a standard way.
> base: initramfs-framework: refactor access to UEFI variables

- meta-lmp-base/recipes-core/initrdscripts/initramfs-module-install-efi/init-install-efi.sh
- meta-lmp-base/recipes-core/initrdscripts/initramfs-module-install-efi_%.bbappend
Add support for a CI encrypted rootfs USB installer.
> base: init-install-efi: installer: support encrypted rootfs

- meta-lmp-base/recipes-core/initrdscripts/initramfs-framework/cryptfs_tpm2
- meta-lmp-base/recipes-core/initrdscripts/initramfs-module-install-efi/init-install-efi.sh
Using efivar --print-decimal returns an integer.
> base: initramfs: check for secure boot

- meta-lmp-bsp/conf/machine/include/lmp-machine-custom.inc
Systemd-boot will display its menu by alphabetically iterating the different configuration files.
This commit makes sure that the secure boot menus (provision/revocation) are displayed next to each other for a more structured screen.
Instead of 
we will display
> bsp: intel-corei7-64: provisioning/revocation menu

- meta-lmp-bsp/dynamic-layers/tegra/recipes-bsp/lmp-boot-firmware/lmp-boot-firmware.bbappend
Use L4T_VERSION variable, and convert it to the same format as it's currenlty exposed via ESRT table:
$ cat /sys/firmware/efi/esrt/entries/entry0/fw_version 2295296
> bsp: dynamic-layers: lmp-boot-firmware: use L4T_VERSION

- meta-lmp-base/recipes-bsp/efitools/efitools/lockdown.conf
- meta-lmp-base/recipes-bsp/efitools/efitools/unlock.conf
- meta-lmp-base/recipes-extended/ostree/ostree/0007-sort-key.patch
- meta-lmp-base/recipes-extended/ostree/ostree_%.bbappend
By using the sort-key[1] label in the conf files, this PR positions ostree deployments above UEFI provisioning applications.
[1] https://uapi-group.org/specifications/specs/boot_loader_specification/#sorting
> base: systemd-boot display order

- meta-lmp-bsp/conf/machine/include/lmp-machine-custom.inc
On the first boot, systemd-boot 250.4 defaults to the last element on the display list.
Make the OSTree deployment the last (alphabetically sorted)
> bsp: intel-corei7-64: default entry

- meta-lmp-base/recipes-sota/ostreeuploader/ostreeuploader_git.bb
- 5cd2cf9 check: Reduce a number of goroutine to check file existing
- e318913 fiopush: Treat summary update failure as error
- 5991933 push: Decrease number of push goroutines
> base: rs: Bump ostreeuploader ver 5cd2cf9

- meta-lmp-base/recipes-extended/ostree/ostree/0008-sysroot-deploy-systemd-boot-efi-to-ESP-partition.patch
- meta-lmp-base/recipes-extended/ostree/ostree_%.bbappend
Add support for deploying systemd-boot to ESP partition. Considering that default deployment has always index == 0, the filenames in ESP for efi binaries are generated in this way:
deployment index       path
0:                     /boot/EFI/BOOT/bootx64.efi
1:                     /boot/EFI/BOOT/bootx64-1.efi
2:                     /boot/EFI/BOOT/bootx64-2.efi
> sysroot: deploy systemd-boot efi to ESP partition

- meta-lmp-base/recipes-samples/images/lmp-image-common.inc
- meta-lmp-base/recipes-support/fio-diag/fio-diag_0.1.bb
This adds the first version of fio-diag.sh to an lmp image
> base: lmp: Add diagnostic tool

- meta-lmp-bsp/dynamic-layers/freescale-layer/recipes-bsp/firmware-imx/firmware-nxp-wifi_1.0.bbappend
- meta-lmp-bsp/recipes-kernel/linux-firmware/linux-firmware_%.bbappend
Fix for:
```
* check_data_file_clashes: Package linux-firmware wants to install file /lmp/build-lmp-imx8mm-lpddr4-evk-kirkstone/tmp-lmp/work/imx8mm_lpddr4_evk-lmp-linux/lmp-base-console-image/1.0-r0/rootfs/usr/lib/firmware/nxp/helper_uart_3000000.bin
But that file is already provided by package  * firmware-nxp-wifi-nxp-common
* check_data_file_clashes: Package linux-firmware wants to install file /lmp/build-lmp-imx8mm-lpddr4-evk-kirkstone/tmp-lmp/work/imx8mm_lpddr4_evk-lmp-linux/lmp-base-console-image/1.0-r0/rootfs/usr/lib/firmware/nxp/uartuart8987_bt.bin
But that file is already provided by package  * firmware-nxp-wifi-nxp8987-sdio
```
Steps to replicate is installing the upstream `linux-firmware` using the machine `imx8mm-lpddr4-evk`
> [kirkstone] firmware: fix downstream firmware-nxp-wifi conflicts with the upstream linux-firmware

- meta-lmp-base/recipes-sota/aktualizr/aktualizr_%.bbappend
asn1c tool places the full absolute path for the asn1 files inside comments of the generated source files. Make them relative to ${S} to avoid the warning messages during do_package_qa.
> base: rc: aktualizr: Fix Yocto TMPDIR warning message

- meta-lmp-bsp/conf/machine/include/lmp-machine-custom.inc
- meta-lmp-bsp/scripts/lib/wic/plugins/source/bootimg-sota-efi.py
According to boot entries sorting rules in bootloader spec [1]:
- Entries which are subject to boot counting and are marked as “bad”, should be sorted later than all other entries. Entries which are marked as “indeterminate” or “good” (or were not subject to boot counting at all), are thus sorted earlier.
Mark unlock/lockdown boot entries as bad by adding +0 suffix (0 tries left), as a result the entries will be still shown (so it's possible to select them manually) and always be sorted late.
[1] https://uapi-group.org/specifications/specs/boot_loader_specification/#sorting
> bsp: intel-corei7-64: add 0 tries left suffixes

- meta-lmp-bsp/conf/machine/include/lmp-machine-custom.inc
There is no value in appending the provisioning tools to the WIC unless UEFI signatures have been enabled.
> bsp: conf: x86: append provision tools only with signatures

- meta-lmp-bsp/conf/machine/include/lmp-machine-custom.inc
Add configuration for the serial console in the bootargs. The bootargs
were removed in commit bb3d65787("arm64: dts: ti: k3-am642-sk|evm: Drop
bootargs, add aliases") in the ti-linux-6.6.y branch. This change was
also sent upstream [1].
Providing the proper serial configuration in bootargs fixes the
broken console output in the Linux kernel:
Starting kernel ...
[    0.000000] Booting Linux on physical CPU 0x0000000000 [0x410fd034]
[    0.000000] Linux version 6.6.44-lmp-standard (oe-user@oe-host)
[1] https://lore.kernel.org/all/20230414073328.381336-11-nm@ti.com/
> bsp: k3: add serial console configuration

- meta-lmp-bsp/conf/machine/include/lmp-machine-custom.inc
We found some issues on ti-6_12 who is the one that comes by default in the bsp 11.00.01 so still with ti-6_6 for now with the bsp 11.00.01
> bsp: lmp-machine-custom: keep TI 6.6 in bsp 11.00.01

- meta-lmp-bsp/dynamic-layers/freescale-layer/recipes-bsp/isp-imx/isp-imx_4.2.2.24.0.bbappend
This reverts commit https://github.com/quaresmajose/meta-lmp/commit/4662f1c424ffb87dbeaa801d86d4147c066522c0.
This patch is not need anymore on lmp scarthgap and he is specific
to be used with oe-core/kirkstone.
The patch was needed prior to the scarthgap switch.
when we use the meta-freescale/scarthgap branch with the
oe-core/kirkstone branch, but now everything is on scarthgap.
> Revert "bsp: isp-imx: revert scarthgap specific changes"

- meta-lmp-base/classes/kernel-lmp-fitimage.bbclass
- meta-lmp-bsp/recipes-bsp/u-boot/u-boot-base-scr/imx8qm-mek/boot.cmd
- meta-lmp-bsp/recipes-bsp/u-boot/u-boot-ostree-scr-fit/am62xx-evm/boot.cmd
- meta-lmp-bsp/recipes-bsp/u-boot/u-boot-ostree-scr-fit/am64xx-evm/boot.cmd
- meta-lmp-bsp/recipes-bsp/u-boot/u-boot-ostree-scr-fit/imx6ulevk/boot.cmd
- meta-lmp-bsp/recipes-bsp/u-boot/u-boot-ostree-scr-fit/imx6ullevk/boot.cmd
- meta-lmp-bsp/recipes-bsp/u-boot/u-boot-ostree-scr-fit/imx8mm-lpddr4-evk/boot.cmd
- meta-lmp-bsp/recipes-bsp/u-boot/u-boot-ostree-scr-fit/imx8mn-ddr4-evk/boot.cmd
- meta-lmp-bsp/recipes-bsp/u-boot/u-boot-ostree-scr-fit/imx8mn-lpddr4-evk/boot.cmd
- meta-lmp-bsp/recipes-bsp/u-boot/u-boot-ostree-scr-fit/imx8mp-lpddr4-evk/boot.cmd
- meta-lmp-bsp/recipes-bsp/u-boot/u-boot-ostree-scr-fit/imx8mq-evk/boot.cmd
- meta-lmp-bsp/recipes-bsp/u-boot/u-boot-ostree-scr-fit/imx8qm-mek/boot.cmd
- meta-lmp-bsp/recipes-bsp/u-boot/u-boot-ostree-scr-fit/imx93-11x11-lpddr4x-evk/boot.cmd
Align with the kernel-fitimage changes available in scarthgap.
This will help us upstreaming the changes as we can easily generate a diff based on what is available in scarthgap.
> base: kernel-lmp-fitimage: align changes with scarthgap

- meta-lmp-base/conf/distro/include/lmp.inc
- meta-lmp-base/recipes-support/mfgtool-files/mfgtool-files/full_image.uuu.in
- meta-lmp-base/recipes-support/mfgtool-files/mfgtool-files_0.1.bb
- meta-lmp-bsp/recipes-support/mfgtool-files/mfgtool-files/imx6ulevk/full_image.uuu.in
- meta-lmp-bsp/recipes-support/mfgtool-files/mfgtool-files/imx6ullevk/full_image.uuu.in
- meta-lmp-bsp/recipes-support/mfgtool-files/mfgtool-files/imx8mm-lpddr4-evk-sec/full_image.uuu.in
- meta-lmp-bsp/recipes-support/mfgtool-files/mfgtool-files/imx8mm-lpddr4-evk/full_image.uuu.in
- meta-lmp-bsp/recipes-support/mfgtool-files/mfgtool-files/imx8mn-ddr4-evk-sec/full_image.uuu.in
- meta-lmp-bsp/recipes-support/mfgtool-files/mfgtool-files/imx8mn-ddr4-evk/full_image.uuu.in
- meta-lmp-bsp/recipes-support/mfgtool-files/mfgtool-files/imx8mn-lpddr4-evk-sec/full_image.uuu.in
- meta-lmp-bsp/recipes-support/mfgtool-files/mfgtool-files/imx8mn-lpddr4-evk/full_image.uuu.in
- meta-lmp-bsp/recipes-support/mfgtool-files/mfgtool-files/imx8mp-lpddr4-evk-sec/full_image.uuu.in
- meta-lmp-bsp/recipes-support/mfgtool-files/mfgtool-files/imx8mp-lpddr4-evk/full_image.uuu.in
- meta-lmp-bsp/recipes-support/mfgtool-files/mfgtool-files/imx8mq-evk/full_image.uuu.in
- meta-lmp-bsp/recipes-support/mfgtool-files/mfgtool-files/imx8qm-mek-sec/full_image.uuu.in
- meta-lmp-bsp/recipes-support/mfgtool-files/mfgtool-files/imx8qm-mek/full_image.uuu.in
- meta-lmp-bsp/recipes-support/mfgtool-files/mfgtool-files/imx93-11x11-lpddr4x-evk/full_image.uuu.in
The default value in scarthgap of IMAGE_NAME_SUFFIX is '.rootfs'.
This will have several impacts on our CI so we will revert back for the default value.
> scarthgap: keep the same IMAGE_NAME_SUFFIX as before

- meta-lmp-base/recipes-bsp/efitools/efitools_git.bb
With the use of the UEFI_SIGN_ENABLE this recipe becomes machine specific
> base: efitools: make it machine specific

- meta-lmp-base/recipes-bsp/u-boot/u-boot-fio-mfgtool/lmp-base-common.cfg
- meta-lmp-base/recipes-bsp/u-boot/u-boot-fio-mfgtool/lmp-base.cfg
This is only required to avoid failing in bitbake parsing on the lmp-base distro. The issue can be observed when building the distro lmp-base and using the generic-arm64 machine.
It fixes the bitbake parsing ERROR:
| Unable to get checksum for u-boot-fio-mfgtool SRC_URI entry lmp-base-common.cfg: file could not be found
| Unable to get checksum for u-boot-fio-mfgtool SRC_URI entry lmp-base.cfg: file could not be found
> base: u-boot-fio-mfgtool: add default lmp-base distro cfg

- meta-lmp-bsp/dynamic-layers/tegra/recipes-kernel/linux/linux-tegra-rt_5.10.bb
Align rt version with linux-tegra from meta-tegra.
> bsp: tegra: linux-tegra-rt: bump to r35.5.0

- meta-lmp-bsp/dynamic-layers/tegra/recipes-kernel/linux/linux-tegra-rt_5.10.bb
Align rt version with linux-tegra from meta-tegra.
> bsp: tegra: linux-tegra-rt: bump to r35.6.0

- meta-lmp-base/recipes-containers/composeapp/composectl_git.bb
- meta-lmp-base/recipes-sota/aktualizr/aktualizr_%.bbappend
1. Added support for EFI boot firmware updates, including functionality to get/set bootloader control environment variables using the `fioefi_setenv` and `fioefi_printenv` utilities.
2. Added new CLI client commands: `check`, `pull`, `install`, and `run`. These individual commands allow users to pull, install, and apply updates from different contexts.
3. Introduced the `--src-dir` parameter for the `aktualizr-lite` CLI client, enabling offline updates.
4. Automatic downgrade prevention.
5. Added support for user-initiated rollbacks [experimental]
1. Integrated `composectl` for all operations involving Compose Apps, such as pruning, checking if running, etc.
2. Optimized app management to minimize the number of actions performed on Compose Apps during the update cycle.
3. Made app …
> Aklite and composectl sotactl v95

- meta-lmp-bsp/dynamic-layers/tegra/recipes-core/systemd/systemd-boot/0001-Increase-the-dtb-size.patch
- meta-lmp-bsp/dynamic-layers/tegra/recipes-core/systemd/systemd-boot_%.bbappend
This is probably due to fact systemd-boot does not allocate any extra space for the device tree. Without the modification, because there is not any extra space, the UEFI will fail applying the overlay changes from its .dtbo files
Fixes:
```
EFI stub: ERROR: Invalid header detected on UEFI supplied FDT, ignoring ... 
EFI stub: Generating empty DTB
```
References:
https://github.com/anduril/jetpack-nixos/issues/111
> bsp: tegra: systemd-boot: double dtb buffer size

- meta-lmp-bsp/dynamic-layers/tegra/recipes-bsp/tegra-binaries/tegra-helper-scripts-native_35.6.0.bbappend
- meta-lmp-bsp/dynamic-layers/tegra/recipes-core/initrdscripts/tegra-flash-init_%.bbappend
We have support in https://github.com/foundriesio/meta-lmp/commit/7340131185416ca42f6a7f07d5b6f3f3c1719bf7 for WIC image on the external SSD on the Xavier and for that we added:
- Support for formatting the internal mmc, patching the target recipe `tegra-flash-init`
- Forked the `initrd-flash.sh` part of the recipe `tegra-helper-scripts-native`
We need to rewrite this initrd-flash API using hooks available upstream and we will do that in a followup.
https://github.com/OE4T/meta-tegra/commit/f619e64dddef91ff80b3013ea4e6a51a54083a66
https://github.com/OE4T/meta-tegra/commit/1d1466fa269e6e9e58b7e0509995389b009fdfee
This PR will restrict the downstream fork to Xavier and will follow with the upstream in the Orin SoC.
> Tegra: make our internal downstream fork Xavier specific

- meta-lmp-base/conf/distro/include/lmp.inc
Align meta-lmp with the 4.0.22 yocto release.
Lmp-manifest update will follow.
> base: lmp: bump version for the 4.0.22 yocto release

- meta-lmp-bsp/recipes-kernel/linux/linux-lmp-fslc-imx_6.6.bb
- 5ff4cf4d61e1 Merge pull request #713 from angolini/fix_imx93
- e587f8fe42f1 firmware: se_fw: remove info_list from ro section
- a0609cb5220a Merge pull request #712 from angolini/push_one
- 0f638960dcff media: Kconfig: fix double VIDEO_DEV
- 226bfffe04bc Merge pull request #709 from fs-csenatore/6.6-2.2.x-imx
- 198242c057e0 drivers:clk:imx:clk-imx8mp-audiomix: remove duplicated CLK_GATE_PARENT definition
- 427223e3206d Merge pull request #707 from iceaway/revert_u-serial_patch
- 4f5936d7391f Revert "usb: gadget: u_serial: Disable ep before setting port to null to fix the crash caused by port being null"
- 00aabf3c03c3 Merge pull request #705 from unitexe/6.6-2.2.x-imx
- 997b7e13e413 imx8mp-olimex.dts: Olimex iMX8MP-SOM-EVB-IND
- 2a0fc42db4d4 Merge pull request #704 …
> bsp: linux-lmp-fslc-imx: Bump kernel 6.6-2.2.x-imx to 5ff4cf4d

- meta-lmp-bsp/dynamic-layers/tegra/recipes-containers/libnvidia-container/libnvidia-container/0003-nvcgo-fix-build-with-go-1.24.patch
- meta-lmp-bsp/dynamic-layers/tegra/recipes-containers/libnvidia-container/libnvidia-container_1.10.0.bbappend
Add a patch to libnvidia-container to fix build issues with go 1.24.
> bsp: tegra: libnvidia-container: fix build error

- meta-lmp-bsp/recipes-bsp/lm_sensors/lmsensors-config_1.0.bbappend
This reverts commit 591daf5876895f5ee1cf66629c0fdbb539a68a3c.
Fixup for c3d48d9 bsp: Xilinx: Remove the LmP support
We removed the config file lmsensors-config/kv260/fancontrol but the bbappend stayed there.
> Revert "bsp: lmsensors-config: add fancontrol config for kv260"

- meta-lmp-base/recipes-sota/aktualizr/aktualizr_%.bbappend
The "${RDEPENDS:aktualizr}" syntax is not supported in bitbake.
Also take the opurtunity to apply it just for the class-target
> base: aktualizr: fix RDEPENDS

- meta-lmp-base/classes/image-license-checker.bbclass
There are a fix in the DEPLOY_DIR/licenses/recipe/recipeinfo path generation in Scarthgap. The archtecture was included to avoid overlaping.
This patch uses the same mechanism used in license.bbclass to deploy the license files to search for them in image-license-checker.bbclass.
We can have references such as
https://patchwork.yoctoproject.org/project/oe-core/patch/20230919214621.903967-1-richard.purdie@linuxfoundation.org/ https://github.com/yoctoproject/poky/commit/6cc2a3649a03da8b2ebc4fff4b7bd9ba4eb76497
> base:classes: Fix path for recipeinfo license file

- meta-lmp-base/recipes-support/gmp/gmp_6.3.0.bbappend
Upstream is dual licensed on GPLv2 | LGPLv3, so force GPLv2 in order to allow safe checks via image-license-checker.
There is no conflicting user by default, but users linking to libgmp need to be aware of the license implication.
> base: gmp: prefer GPLv2-or-later as main license

- meta-lmp-bsp/recipes-kernel/linux/linux-lmp-fslc-imx/0001-clk-imx-imx6ul-fix-default-parent-for-enet-_ref_sel.patch
- meta-lmp-bsp/recipes-kernel/linux/linux-lmp-fslc-imx/0001-net-enetc-Use-IRQF_NO_AUTOEN-flag-in-request_irq.patch
- meta-lmp-bsp/recipes-kernel/linux/linux-lmp-fslc-imx_6.6.bb
Backport kernel fixes required to fix the broken ethernet support on imx6ul/imx6ull devices.
> bsp: linux-lmp-fslc-imx: backport fixes for imx6ull ethernet

- meta-lmp-base/recipes-security/optee/optee-os-fio_4.4.0.bb
- 88da15801 [FIO from tree] drivers: caam: check only format
- a8d4fd26f [FIO from tree] drivers: caam: Update comments in RSA
Fixes RSA decrypt regresion detected in CI
https://github.com/OP-TEE/optee_os/issues/7362
> base: optee-os-fio: bump to 88da158

- meta-lmp-base/recipes-core/systemd/systemd_%.bbappend
The are some machines where the MAC is missing and is randomly generated to have a local address.
This will generate interfaces with different names and we don't want that.
> base: systemd: disables the 'mac' policy for pni-names

- meta-lmp-bsp/conf/machine/include/lmp-machine-custom.inc
Required for fitImage support, previously defined via board config but removed from meta-yocto (as they moved to support zImage by default).
Add back in lmp for a functiona fit-based boot.
> bsp: lmp-machine-custom: beagle: define u-boot entrypoint

- meta-lmp-base/recipes-containers/composeapp/composectl_git.bb
- 862e6be ps: Don't print info about ext images if json output
> base: rc: composectl: Bump version 862e6be

- meta-lmp-base/classes/lmp-staging.bbclass
This reverts commit e5490f56ac39823b09b6e59dbd1f3f0363a5cd20.
STM32 was moved to a partner layer, drop leftover LMPSTAGING_KERN_ADD_ST_SUBDIR
> Revert "base: lmp-staging: add vendor subdir for kernel dts if needed"

- meta-lmp-base/recipes-extended/ostree/ostree/0001-deploy-only-set-aboot-abootcfg-when-found.patch
- meta-lmp-base/recipes-extended/ostree/ostree_%.bbappend
Add patch to skip aboot/abootcfg ostree boot entries when aboot is not used by the system.
This fixes unknown line warnings with systemd-boot/bootctl: /boot/loader/entries/ostree-2.conf:8: Unknown line 'abootcfg', ignoring. /boot/loader/entries/ostree-2.conf:9: Unknown line 'aboot', ignoring.
> base: ostree: skip aboot entries when not available

- meta-lmp-base/recipes-extended/rrdtool/rrdtool_%.bbappend
Graph removal is now done via PACKAGECONFIG, update our override to reflect the changes from meta-oe.
> base: rrdtool: remove graph via PACKAGECONFIG

- meta-lmp-base/conf/distro/include/cve-lmp-extra-exclusions.inc
> base: cve-lmp-extra-exclusions: drop CVE-2022-47085

- meta-lmp-base/recipes-bsp/u-boot/u-boot-fio_imx-2022.04.bb
- meta-lmp-base/recipes-bsp/u-boot/u-boot-fio_imx-2024.04.bb
uuu_bootloader_tag bbclass is only available when meta-freescale is also enabled in LmP, causing a parser error when not added by default.
> u-boot-fio_imx: fix uuu_bootloader_tag class inherit

- meta-lmp-bsp/conf/machine/include/lmp-machine-custom.inc
It remove the complete package linux-firware which is installed following the MACHINE_EXTRA_RRECOMMENDS recommendation from meta-intel.
Any sub package from linux-firware can still be installed.
It reduces the final image size by not installing additional extra packages.
-- 
It is tested by checking for `linux-firmware-*` packages from `buildhistory/iamges/intel_corei7-64/glibc/lmp-base-console-image/installed-package-sizes.txt`
> bsp: intel-corei7-64: Remove linux-firmware from RRECOMMENDS

- meta-lmp-base/recipes-bsp/u-boot/u-boot-fio_imx-2022.04.bb
- meta-lmp-base/recipes-bsp/u-boot/u-boot-fio_imx-2024.04.bb
uuu_bootloader_tag bbclass is only available when meta-freescale is also enabled in LmP, causing a parser error when not added by default.
(cherry picked from commit 9c5b2c8561fc79f7ebae718ac28ed4e026ee8c10)
> [scarthgap] u-boot-fio_imx: fix uuu_bootloader_tag class inherit

- meta-lmp-base/recipes-kernel/linux/kmeta-linux-lmp-6.6.y.inc
- a00a749e bsp: raspberrypi3: config updates for 6.6
> base: kmeta-linux-lmp-6.6.y: bump to a00a749e

- meta-lmp-base/recipes-kernel/linux/kmeta-linux-lmp-6.6.y.inc
- 6d8bf98 features/debug/debug-kernel: disable CONFIG_DEBUG_INFO
> base: kmeta-linux-lmp-6.6.y: bump to 6d8bf98

- meta-lmp-bsp/conf/machine/include/lmp-machine-custom.inc
FFTK-4105
Raspberry 3 is no longer relevant to us, so let's remove the code for this.
----
There are several override for "raspberry", the goal here is to remove only those exclusive for raspberrypi3.
Keyword used: rpi, rasp, raspberry, raspberrypi3
> bsp: Remove raspberrypi3 support

- meta-lmp-bsp/recipes-kernel/linux/linux-lmp-fslc-imx.inc
- meta-lmp-bsp/recipes-kernel/linux/linux-lmp-rpi_git.bb
On the lmp base layer the linux-lmp.inc already uses the 'require' so the build fail when the file not found.
The same should also happen in the lmp bsp layer.
> bsp: linux-lmp.inc: makes it mandatory

- meta-lmp-bsp/recipes-kernel/linux/linux-lmp-fslc-imx-rt_6.6.bb
- f03af81d60b7 net: mscc: ocelot: be resilient to loss of PTP packets during transmission
- 72bc664feb34 net: felix: fix gcl configuration lost when clock adjust
> bsp: linux-lmp-fslc-imx-rt: bump to latest commit

- meta-lmp-base/conf/distro/include/lmp.inc
Switch back to the default oe-core toolchain (gcc) as clang still requires a substantial amount of fixes when supporting third party BSP vendors.
> base: lmp: drop custom toolchain options, switch to gcc / default

- meta-lmp-bsp/conf/machine/include/lmp-machine-custom.inc
- meta-lmp-bsp/dynamic-layers/meta-ti-extras/recipes-connectivity/wlconf/wlconf_8.7.3.bbappend
Drop bluetooth and wifi firmware and scripts which are provided by meta-ti, as it is now removed from the standard manifest list.
> bsp: beaglebone-yocto: drop bt / wl firmware and related scripts

- meta-lmp-base/recipes-containers/docker/files/daemon.json.in
- meta-lmp-base/recipes-containers/wayland-cdi/files/wayland-cdi-generate
- meta-lmp-base/recipes-containers/wayland-cdi/files/wayland-cdi.service
- meta-lmp-base/recipes-containers/wayland-cdi/wayland-cdi_0.1.bb
- meta-lmp-base/recipes-samples/images/lmp-feature-docker.inc
We have a hard-to-remember way of running wayland applications inside Docker. By leveraging [CDI](https://github.com/cncf-tags/container-device-interface/) we can make this much easier for users so that you could simply run:
```
docker run --device org.wayland/display=wayland-1 <image>
```
and have all the correct bind-mounts and environment variables set inside the container.
> RFC: Add CDI generator for Wayland displays in (x)wayland images

- meta-lmp-bsp/recipes-bsp/u-boot/u-boot-fio_%.bbappend
- meta-lmp-bsp/recipes-security/optee/optee-os-fio-bsp.inc
Fixup the IMX drop in last commit.
- The u-boot-fio-bsp-common.inc was removed
- Remove extra "
> bsp: fixup imx drop
