recipes-kernel/linux/linux-lmp-dev.bb, recipes-kernel/linux/linux-lmp_git.bb, recipes-sota/lmp-device-register/lmp-device-register_git.bb
The build is failing with: 
ERROR: linux-lmp-4.18.18+gitAUTOINC+b15a38120a_2835754ba8-r0 do_fetch: Fetcher failure for URL: 'git://github.com/foundriesiolinux.git;protocol=https;branch=linux-v4.18.y;name=machine;'. Unable to fetch URL from any source.
because I forgot the trailing /'s
=> fixup! Convert to github source defaults

recipes-devtools/python/python3-docker_3.7.0.bb
=> python3-docker: update to the 3.7.0 release

recipes-kernel/jool/jool_git.bb
=> jool: update to v4.0.0 release

recipes-samples/images/lmp-gateway-image.bb, recipes-security/optee/optee-os_git.bb
* Install and package OP-TEE OS TAs
* Install OS firmware as part of the optee-os package
* Use standard includedir variable
=> Optee-os cleanups

recipes-kernel/linux/linux-lmp_git.bb
=> linux-lmp: update kernel to 5.0.10

conf/distro/include/lmp.inc, recipes-samples/images/lmp-gateway-image.bb, recipes-samples/images/lmp-image-common.inc
These can be overriden in local.conf
=> lmp.inc: set default username/password variables

recipes-samples/images/lmp-image-common.inc, recipes-support/docker-credential-helper-fio/docker-credential-helper-fio_0.1.bb, recipes-support/docker-credential-helper-fio/files/docker-credential-fio-helper
=> Support for docker-credential-helper-fio

recipes-sota/lmp-device-register/lmp-device-register_git.bb
=> lmp-device-register: Pull in fix for docker_apps_root

recipes-sota/config/files/10-lite-public-stream.toml.in
=> aktualizr-lite-public-stream: add docker-app settings

recipes-sota/aktualizr/aktualizr_%.bbappend
Add the ability to report hardware information up to the server.
=> recipes-sota: Bump version of aktualizr

classes/kernel-lmp-fitimage.bbclass
Add support to store and load fpga binaries as part of the kernel
fitimage.
FPGA support depends on FPGA_BINARY and FPGA_LOADADDRESS, which needs to
be defined by the user.
=> kernel-lmp-fitimage: add support for fpga

recipes-security/optee/optee-os/0001-Minimal-HUK-implementation-without-full-CAAM-driver.patch
The current code was failing to retrieve the hardware unique key
=> optee-os: imx: fix mkvb retrieval

recipes-kernel/linux/linux-lmp_git.bb
=> linux-lmp: update to 5.3.9

recipes-security/optee/optee-os/0001-Foundries.IO-Verified-Boot-Trusted-Application.patch, recipes-security/optee/optee-os_git.bb
Clone the AVB trusted application for internal customization
=> FIO trusted application

recipes-security/optee/optee-fiovb_git.bb
=> optee-os: ca: fiovb host: bump version

recipes-security/optee/optee-os/0001-Foundries.IO-Verified-Boot-Trusted-Application.patch
=> fiovb ta: add m4size of the list of persistent variables

meta-lmp-base/recipes-bsp/u-boot/u-boot-fio-common.inc
- 5c4a2d68 [FIO extras] mx7ulp: update wdog disable sequence
- 90957184 [FIO nxp] MLK-22654 mx7ulp: Update wdog disable sequence
- 2bd27028 [FIO internal] arch: arm: imx7ulp: fix rpmsg reservation conflict with OP-TEE
- 0c251800 [fio toup] fpga: imx_m4: correct check for M4 running
- bdd0b148 [FIO toup] fpga: imx_m4: fix infinite loop on corrupted flash data
- ab8a9302 [FIO toup] fpga: imx_m4: fix compilation errors
- 0b3ee9d1 [FIO internal]: fiovb: update persistent variable list
=> meta-lmp-base: u-boot: bump u-boot sha

meta-lmp-base/recipes-containers/docker-app/docker-app/0001-Warn-on-unused-parameters-rather-than-exit.patch, meta-lmp-base/recipes-containers/docker-app/docker-app_git.bb
=> docker-app: Add patch for unused parameters

meta-lmp-base/classes/kernel-lmp-fitimage.bbclass, meta-lmp-base/conf/distro/include/lmp.inc, meta-lmp-base/recipes-kernel/linux/linux-lmp_git.bb, meta-lmp-base/recipes-sota/aktualizr/aktualizr_%.bbappend, meta-lmp-bsp/conf/machine/include/lmp-machine-custom.inc, meta-lmp-bsp/recipes-devtools/qemu/qemu-system-native/0001-target-arm-arm-semi-fix-SYS_OPEN-to-return-nonzero-f.patch, meta-lmp-bsp/recipes-devtools/qemu/qemu-system-native_%.bbappend
General stable updates and making the layer compatible with latest oe-core/master.
=> meta-lmp updates for 64

meta-lmp-base/recipes-security/optee/optee-os_git.bb
Relevant changes
- 568d440e [FIO toup] imx7ulp: add definition for SNVS_BASE
- a667673b [FIO toup] imx7ulp: CFG_IMX_SNVS
=> base: security: op-tee: bump SHA

meta-lmp-base/recipes-support/lmp-auto-hostname/lmp-auto-hostname/lmp-update-hostname.sh
Script was only checking for device-tree when looking for model and
serial, so extend it to also check for sysfs files available on systems
with dmi support.
=> base: lmp-auto-hostname: support model and serial via dmi

meta-lmp-base/recipes-sota/aktualizr/aktualizr_%.bbappend
This pulls in:
https://github.com/foundriesio/aktualizr-lite/commit/35bb1f4e80ea7c635dd27434717d8a6a58f212d8
=> aktualizr: Pull in hot-fix for docker-compose bug

meta-lmp-base/recipes-sota/aktualizr/aktualizr_%.bbappend
This brings in some notable changes:
* callback support
* compose apps package manager
=> recipes-sota: Bump aklite version

meta-lmp-base/recipes-sota/aktualizr/aktualizr_%.bbappend
=> base: aktualizr-lite: bump to 6cdc977

meta-lmp-base/recipes-bsp/u-boot/u-boot-fio-mfgtool.bb, meta-lmp-base/recipes-kernel/linux/linux-lmp-dev-mfgtool.bb, meta-lmp-bsp/recipes-bsp/u-boot/u-boot-fio/imx6ullevk/fw_env.config
- add 2 mfgtool recipe variants to allow easier customization
- include machine specific fw_env.config for imx6ullevk
=> v72 changes

meta-lmp-base/recipes-sota/aktualizr/aktualizr_%.bbappend
- 6dfb002 Check App status and update if not running
- 09aa1c9 Report aktualizr config to server
=> base: aktualizr-lite: bump to 56f8357

meta-lmp-base/recipes-sota/aktualizr/aktualizr_%.bbappend, meta-lmp-base/recipes-sota/config/files/10-lite-public-stream.toml.in, meta-lmp-base/recipes-sota/lmp-device-register/lmp-device-register_git.bb
=> base: lmp-device-register: Remove Docker App

meta-lmp-base/recipes-sota/aktualizr/aktualizr_%.bbappend
- fixup: Remove apps from the list safely
=> base: aktualizr-lite: bump to f6f16a0

meta-lmp-base/recipes-support/fioconfig/fioconfig_git.bb
=> fioconfig: Bump to version with updated help text

meta-lmp-bsp/recipes-bsp/u-boot/u-boot-ostree-scr-fit/imx6ullevk/boot.cmd
=> bsp: u-boot-ostree-scr-fit: imx6ullevk: fix fdtfile typo

meta-lmp-base/recipes-sota/aktualizr/aktualizr_%.bbappend
=> base: aktualizr: fix VERSION generation

meta-lmp-base/recipes-support/fioconfig/fioconfig_git.bb
Include improvement to aktualizr-lite-toml-update callback script
=> fioconfig: Bump version

meta-lmp-base/recipes-support/fioconfig/fioconfig_git.bb
=> fioconfig: Pull in fix for socket leak

meta-lmp-base/recipes-core/initrdscripts/initramfs-module-install-efi/init-install-efi.sh
=> initrdscripts: Preload compose-apps if present

meta-lmp-base/classes/lmp.bbclass
=> base: preload: preload apps along with their images

meta-lmp-base/recipes-kernel/linux/kmeta-linux-lmp-5.10.y.inc, meta-lmp-base/recipes-kernel/linux/linux-lmp_git.bb
=> base: linux-lmp: update to v5.10.1

meta-lmp-base/recipes-support/fioconfig/fioconfig_git.bb
- 67c71aa: Remove files on device when they are removed on server and run the last known onChanged handler
Signed-off-by: Volodymyr Khoroz <volodymyr.khoroz@foundries.io>
=> base: fioconfig: bump rev to 67c71aa

meta-lmp-bsp/conf/machine/uz3eg-iocc.conf, meta-lmp-bsp/dynamic-layers/xilinx-tools/recipes-bsp/bitstream/bitstream-extraction_git.bb, meta-lmp-bsp/dynamic-layers/xilinx-tools/recipes-bsp/fpga-manager-script/files/0001-Correct-used-paths.patch, meta-lmp-bsp/dynamic-layers/xilinx-tools/recipes-bsp/fpga-manager-script/fpga-manager-script_%.bbappend
=> meta-lmp: xilinx-tools: bitstream-extraction: Add bitstream support

meta-lmp-base/recipes-containers/docker/docker-moby.bb, meta-lmp-base/recipes-containers/docker/docker-moby/dockerd-daemon-reload-image-store-on-a-hup-signal.patch, meta-lmp-base/recipes-sota/aktualizr/aktualizr_%.bbappend
patch dockerd to reload images on a HUP signal
=> dockerd's Image Store hot reload

meta-lmp-base/recipes-security/optee/optee-fiovb_git.bb
dee20a2 fiovb: change normal output to standard out
=> base: optee-fiovb: bump to 2fb0daf

meta-lmp-base/conf/distro/lmp-xwayland.conf, meta-lmp-base/recipes-samples/images/lmp-feature-wayland.inc
- add DISTRO config for lmp-xwayland
- adjust lmp-feature-wayland to include weston-xwayland package when x11 is selected
=> support xwayland distro

meta-lmp-bsp/recipes-support/mfgtool-files/mfgtool-files/apalis-imx6/bootloader.uuu.in, meta-lmp-bsp/recipes-support/mfgtool-files/mfgtool-files/apalis-imx6/full_image.uuu.in, meta-lmp-bsp/recipes-support/mfgtool-files/mfgtool-files/apalis-imx8/bootloader.uuu.in, meta-lmp-bsp/recipes-support/mfgtool-files/mfgtool-files/apalis-imx8/full_image.uuu.in, meta-lmp-bsp/recipes-support/mfgtool-files/mfgtool-files/imx8mmevk/full_image.uuu.in, meta-lmp-bsp/recipes-support/mfgtool-files/mfgtool-files/imx8mqevk/full_image.uuu.in
Choose eMMC hw partition only once.
=> bsp: mfgtool-files: common: choose hw partition only once

meta-lmp-base/classes/uboot-fitimage.bbclass
I found that some platforms support 64-bit addressing with 4GB
or more of memory. This will check if the address is greater
than a 32-bit address and reformat the address so the dtc will
process it correctly.
=> base: classes: allow 64-bit addresses in fit image

meta-lmp-bsp/conf/machine/imx6ullevk-sec.conf, meta-lmp-bsp/recipes-support/mfgtool-files/mfgtool-files/imx6ullevk-sec/close.uuu, meta-lmp-bsp/recipes-support/mfgtool-files/mfgtool-files/imx6ullevk-sec/fuse.uuu, meta-lmp-bsp/recipes-support/mfgtool-files/mfgtool-files/imx6ullevk-sec/readme.md, meta-lmp-bsp/recipes-support/mfgtool-files/mfgtool-files_%.bbappend
PR to add a new machine focusing on secure boot for imx6ullevk.
Some files are also installed to the mfgtools-files package:
- fuse.uuu and close.uuu from lmp-tools scripts
- provision.uuu as a copy from full_image.uuu (but using signed SPL instead)
- readme file with some instructions on how to use the uuu scripts
=> Imx6ullevk secureboot

meta-lmp-bsp/conf/machine/include/lmp-machine-custom.inc, meta-lmp-bsp/recipes-bsp/u-boot/u-boot-fio/apalis-imx6/lmp.cfg
=> bsp: apalis-imx6: pre-load boot script from u-boot FIT

meta-lmp-bsp/dynamic-layers/freescale-layer/recipes-bsp/imx-atf/imx-atf/0003-feat-plat-imx8m-add-system_reset2-implementation.patch
=> bsp: imx-atf: add system_reset2 for imx8mq

meta-lmp-bsp/conf/machine/include/lmp-machine-custom.inc
=> bsp: add missing config for imx7ulp for boot firmware update

meta-lmp-base/classes/uboot-fitimage.bbclass
Allow optee to be optional based on what is set via MACHINE_FEATURES.
Final fit configuration now supports with/without ATF and/or OP-TEE.
=> base: uboot-fitimage: allow optee to be optional

meta-lmp-bsp/dynamic-layers/xilinx/recipes-bsp/bootgen/bootgen/0001-zynqmp-bootloader-support-binary-format.patch, meta-lmp-bsp/dynamic-layers/xilinx/recipes-bsp/bootgen/bootgen_1.0.bbappend
https://github.com/Xilinx/bootgen/pull/10
=> bsp: xlnx: bootgen: support u-boot-spl.bin 

meta-lmp-base/recipes-samples/images/lmp-base-console-image.bb, meta-lmp-base/recipes-samples/images/lmp-gateway-image.bb, meta-lmp-base/recipes-samples/images/lmp-mini-image.bb, meta-lmp-base/recipes-sota/lmp-device-register/lmp-device-register_git.bb
These are the minimal changes seeking to reach a successful build on dunfell.
=> Dunfell update

meta-lmp-base/recipes-sota/lmp-device-register/lmp-device-register_git.bb
Pull in changes to make it work with SOTA_CLIENT
=> recipes-sota: Bump lmp-device-register

meta-lmp-base/classes/lmp.bbclass, meta-lmp-base/conf/distro/lmp-mfgtool.conf
- allow partners to customize lmp settings with conf/machine/include/lmp-partner-custom.inc
- allow partners to customize mfgtool settings with conf/machine/include/lmp-mfgtool-partner-custom.inc
=> meta-lmp partner include support

meta-lmp-base/recipes-bsp/u-boot/u-boot-ostree-scr-fit/boot-common-alternative.cmd.in, meta-lmp-base/recipes-bsp/u-boot/u-boot-ostree-scr-fit/boot-common.cmd.in
Move initialization of fiovb vars obtained from RPMB.
=> bsp: u-boot-ostree-scr-fit: common: move fiovb var init

meta-lmp-base/recipes-sota/aktualizr/aktualizr/aktualizr-lite.service.in, meta-lmp-base/recipes-sota/aktualizr/aktualizr_%.bbappend, meta-lmp-base/recipes-sota/lmp-device-register/lmp-device-register_git.bb
Changes required for the "restorable" apps https://github.com/foundriesio/aktualizr-lite/pull/120.
- Add skopeo as dependency for aklite;
- Add the auth config env variable to the aklite systemd service, skopeo uses it to get auth for Registry.
=> Restorable apps

meta-lmp-base/recipes-samples/images/lmp-feature-wifi.inc, meta-lmp-base/recipes-support/mxm-mwifiex-setup/mxm-mwifiex-setup/modprobe-moal.conf, meta-lmp-base/recipes-support/mxm-mwifiex-setup/mxm-mwifiex-setup/modules-load-moal.conf, meta-lmp-base/recipes-support/mxm-mwifiex-setup/mxm-mwifiex-setup_0.1.bb, meta-lmp-bsp/conf/machine/include/lmp-machine-custom.inc, meta-lmp-bsp/recipes-kernel/linux-firmware/linux-firmware_%.bbappend
Can be merged separately. Wi-Fi starts working after merging https://github.com/foundriesio/lmp-kernel-cache/pull/25
=> master: add wi-fi firmware for imx8mm evkb

meta-lmp-base/recipes-graphics/wayland/weston-init.bbappend, meta-lmp-base/recipes-graphics/wayland/weston-init/lmp-wayland/tmpfiles.conf
=> base: add creation of weston home directory

meta-lmp-bsp/recipes-bsp/u-boot/u-boot-ostree-scr-fit/apalis-imx8/boot.cmd, meta-lmp-bsp/recipes-bsp/u-boot/u-boot-ostree-scr-fit/imx8qm-mek/boot.cmd
Drop set_blkcnt invocation, as it's not used backup_boot0/restore_boot0
cmds.
=> set_blkcnt drop

meta-lmp-base/recipes-samples/images/lmp-feature-wifi.inc, meta-lmp-base/recipes-support/mxm-mwifiex-setup/mxm-mwifiex-setup_0.1.bb, meta-lmp-bsp/conf/machine/include/lmp-machine-custom.inc, meta-lmp-bsp/recipes-kernel/linux-firmware/linux-firmware_%.bbappend
Addressed comments in https://github.com/foundriesio/meta-lmp/pull/483
=> master: small fixes for imx-firmware solution

meta-lmp-base/recipes-kernel/linux/kmeta-linux-lmp-5.10.y.inc, meta-lmp-base/recipes-kernel/linux/kmeta-linux-lmp-5.14.y.inc, meta-lmp-base/recipes-kernel/linux/kmeta-linux-lmp-5.15.y.inc, meta-lmp-base/recipes-kernel/linux/kmeta-linux-lmp-5.4.y.inc
- 0efe41d6 base: kmeta-linux-lmp-5.15.y: bump to 4e7a17e
- 0977216c base: kmeta-linux-lmp-5.14.y: bump to 6175c93
- ba023743 base: kmeta-linux-lmp-5.10.y: bump to 15c0657
- c96bdd7a base: kmeta-linux-lmp-5.4.y: bump to ac641ed
=> main: bump kernel configs

meta-lmp-base/recipes-containers/containerd/containerd-opencontainers_git.bb, meta-lmp-base/recipes-containers/docker/docker-ce_git.bb
Minor update to fix CVE-2022-24769.
=> Update docker-ce to 20.10.14

meta-lmp-base/recipes-bsp/grub/grub-efi_%.bbappend
=> bsp: grub-efi: Fix override sintax in a function

meta-lmp-base/recipes-containers/docker/python3-docker-vxcan/docker-vxcan.service, meta-lmp-base/recipes-containers/docker/python3-docker-vxcan_1.0.2.bb, meta-lmp-base/recipes-devtools/python/python3-pyroute2/0001-fix-vxcan-peer.patch, meta-lmp-base/recipes-devtools/python/python3-pyroute2_%.bbappend
Docker NetworkDriver plugin providing CAN connectivity.
=> Add support for docker-vxcan

meta-lmp-bsp/dynamic-layers/freescale-layer/recipes-bsp/imx-atf/imx-atf/0001-plat-imx8mp-implement-system_reset2.patch, meta-lmp-bsp/dynamic-layers/freescale-layer/recipes-bsp/imx-atf/imx-atf_%.bbappend
=> bsp: imx-atf: imx8mp: implement system_reset2

meta-lmp-base/recipes-security/optee/optee-test_3.15.0.bb, meta-lmp-base/recipes-sota/lmp-device-register/lmp-device-register_git.bb
=> Prepare packages to avoid some build errors

meta-lmp-base/recipes-connectivity/networkmanager/networkmanager_1.36.%.bbappend, meta-lmp-base/recipes-connectivity/nfs-utils/nfs-utils_%.bbappend, meta-lmp-base/recipes-containers/skopeo/skopeo_git.bbappend, meta-lmp-base/recipes-core/base-passwd/base-passwd_%.bbappend, meta-lmp-base/recipes-core/initrdscripts/initramfs-framework_%.bbappend, meta-lmp-base/recipes-core/readline/readline_%.bbappend, meta-lmp-base/recipes-devtools/python/python3-docker_%.bbappend, meta-lmp-base/recipes-devtools/python/python3-pyroute2_%.bbappend, meta-lmp-base/recipes-extended/collectd/collectd_%.bbappend, meta-lmp-base/recipes-extended/ostree/ostree_%.bbappend, meta-lmp-base/recipes-extended/zram/zram_%.bbappend, meta-lmp-base/recipes-security/softhsm/softhsm_2.%.bbappend, meta-lmp-bsp/dynamic-layers/tegra/recipes-bsp/cboot/cboot-t19x_%.bbappend, meta-lmp-bsp/dynamic-layers/xilinx-tools/recipes-utils/fru-print/fru-print.bb, meta-lmp-bsp/recipes-kernel/linux/linux-lmp-dev-mfgtool.bbappend
Fix the warning:
WARNING: SRC_URI:append += is not a recommended operator combination, please replace it.
The complete explanation is found in the yocto documentation:
https://docs.yoctoproject.org/singleindex.html#append-prepend-in-combination-with-other-operators
=> Use append instead of += in some recipes

meta-lmp-bsp/conf/machine/apalis-imx6-sec.conf, meta-lmp-bsp/conf/machine/imx6ullevk-sec.conf, meta-lmp-bsp/conf/machine/imx8mm-lpddr4-evk-ebbr.conf, meta-lmp-bsp/conf/machine/imx8mm-lpddr4-evk-sec.conf, meta-lmp-bsp/conf/machine/imx8mp-lpddr4-evk-ebbr.conf, meta-lmp-bsp/conf/machine/imx8mq-evk-ebbr.conf, meta-lmp-bsp/conf/machine/qemuarm64-secureboot-ebbr.conf
Fix duplicated entries in machine overrides to avoid issues during the bitbake override logic.
=> Fix duplication in machine overrides

meta-lmp-base/classes/image-license-checker.bbclass
Following the upstream for kirkstone, the classe image-license-checker got a sensitive
review.
=> base:image-license-checker: Sensitive review

meta-lmp-base/conf/distro/include/lmp.inc
=> base: lmp: bump version for the 4.0.1 yocto release

meta-lmp-base/classes/lmp.bbclass
If the OE builtin preload is turned ON, then invoke the preload script which is supposed to copy Apps and their images into the rootfs that is being bitbaked by the current OE build.
=> base: lmp: Preload Apps if enabled

meta-lmp-base/dynamic-layers/parsec-layer/recipes-parsec/parsec-service/parsec-service/parsec-tmpfiles.conf, meta-lmp-base/dynamic-layers/parsec-layer/recipes-parsec/parsec-service/parsec-service_%.bbappend, meta-lmp-base/recipes-connectivity/nfs-utils/nfs-utils/tmpfiles.conf, meta-lmp-base/recipes-connectivity/nfs-utils/nfs-utils_%.bbappend
* Parsec (now via meta-security)
* nfs-utils (now via meta-updater)
=> Minor cleanups (changes now available via other layers)

meta-lmp-base/conf/distro/include/lmp.inc, meta-lmp-base/conf/distro/include/non-clangable.inc, meta-lmp-base/recipes-devtools/clang/clang-cross-canadian_git.bbappend, meta-lmp-base/recipes-devtools/clang/clang-cross_git.bbappend, meta-lmp-base/recipes-devtools/clang/clang-crosssdk_git.bbappend, meta-lmp-base/recipes-devtools/clang/clang/0036-builtins-Build-float128-soft-float-builtins-for-x86_.patch, meta-lmp-base/recipes-devtools/clang/clang_git.bbappend, meta-lmp-base/recipes-devtools/clang/compiler-rt-sanitizers_git.bbappend, meta-lmp-base/recipes-devtools/clang/compiler-rt_git.bbappend, meta-lmp-base/recipes-devtools/clang/libclc_git.bbappend, meta-lmp-base/recipes-devtools/clang/libcxx_git.bbappend, meta-lmp-base/recipes-devtools/clang/llvm-project-source.bbappend, meta-lmp-base/recipes-devtools/clang/lmp-clang.inc, meta-lmp-base/recipes-devtools/clang/openmp_git.bbappend
- Add LMP non clangable exceptions
- Backport clang submited patch
=> prepare lmp to use clang as default toolchain

meta-lmp-bsp/recipes-kernel/linux/linux-lmp-ea-imx_git.bb
Based on the latest BSP from EA.
=> bsp: linux-lmp-ea-imx: update to linux-ea-v5.10.72

meta-lmp-base/recipes-samples/images/lmp-feature-debug.inc
This is an alternative to https://github.com/foundriesio/meta-lmp/pull/752
This tool is useful for troubleshooting.
=> Alter: base: lmp-feture-debug: add curl tool

meta-lmp-base/recipes-support/fioconfig/fioconfig_git.bb
Brings in new subdir support:
https://github.com/foundriesio/fioconfig/commit/d428548b5fea8b0cd4c874b0d5e20d2ba6b7a2ac
=> base: Bump version of fioconfig

meta-lmp-base/recipes-containers/nerdctl/nerdctl_git.bbappend
=> base: rc: nerdctl: Add redps on the CNI plugins

meta-lmp-base/recipes-bsp/u-boot/u-boot-fio_2022.04.bb, meta-lmp-bsp/dynamic-layers/xilinx/recipes-bsp/u-boot/u-boot-xlnx_2022.01.bb
Includes latest stable and CVE fixes.
=> U-boot-fio and u-boot-xlnx stable bumps

meta-lmp-base/recipes-core/images/initramfs-ostree-lmp-recovery.bb
* drop more fstypes image formats
* depend on u-boot-default-env instead
=> Minor fixes for recovery

meta-lmp-base/conf/distro/include/lmp.inc
=> base: lmp: bump version for the 4.0.4 yocto release

meta-lmp-base/recipes-security/optee/fio-se05x-cli_git.bb
=> lmp-base: fio-se05x-cli: support multiple tokens

meta-lmp-base/recipes-bsp/u-boot/u-boot-ostree-scr-fit/boot-common.cmd.in
Refactor boot image path detection in boot-common include file to decrease code duplication.
=> base: u-boot-ostree-scr-fit: refactor boot-common include

meta-lmp-base/recipes-kernel/linux/kmeta-linux-lmp-5.15.y.inc, meta-lmp-bsp/recipes-kernel/linux/linux-lmp-fslc-imx-rt_git.bb
=> Add support for linux-lmp-fslc-imx-rt (5.15 based)

meta-lmp-base/recipes-support/bluetooth-attach/bluetooth-attach_0.1.bb
=> base: bluetooth-attach: fix syntax

meta-lmp-base/conf/distro/include/lmp.inc
=> base: lmp: bump version for the 4.0.6 yocto release

meta-lmp-base/recipes-kernel/linux/linux-lmp-dev-mfgtool_git.bb, meta-lmp-bsp/recipes-kernel/linux/linux-lmp-fslc-imx_git.bb
=> linux-lmp-fslc-imx: bump to 34103ef81ca9

meta-lmp-base/recipes-containers/docker/docker-ce_git.bb, meta-lmp-base/recipes-containers/docker/files/0001-Fsync-layer-once-extracted-to-file-system.patch
=> base: rc: docker: Patch docker to fsync layer

meta-lmp-base/recipes-samples/images/lmp-feature-wifi.inc, meta-lmp-bsp/conf/machine/include/lmp-machine-custom.inc, meta-lmp-bsp/recipes-kernel/linux-firmware/linux-firmware_%.bbappend
All of this is now been available upstream
https://github.com/Freescale/meta-freescale/pull/1346
=> Drop nxp89xx

meta-lmp-base/conf/distro/include/non-clangable.inc
It supersedes PR  https://github.com/foundriesio/meta-lmp/pull/1003
- Add strip in clang excludes for Linux kernels
- Add a description and references to meta-clang
- Sort a list
=> Fix known clang issues in LmP

meta-lmp-bsp/recipes-kernel/jailhouse/jailhouse/0001-configs-arm64-k3-am625-sk-Add-crypto-memory-region.patch, meta-lmp-bsp/recipes-kernel/jailhouse/jailhouse/0002-configs-arm64-k3-am625-sk-Switch-inmate-boot-console.patch, meta-lmp-bsp/recipes-kernel/jailhouse/jailhouse/0003-configs-arm64-k3-am625-sk-add-vtm-memory-node.patch, meta-lmp-bsp/recipes-kernel/jailhouse/jailhouse/0004-configs-arm64-k3-am625-sk-Add-GPMC-memory-region.patch, meta-lmp-bsp/recipes-kernel/jailhouse/jailhouse_git.bbappend
Patch series available at
https://groups.google.com/g/jailhouse-dev/c/3BrwWSbrq90
=> bsp: jailhouse: k3: update patch-set based on what was submitted

meta-lmp-base/recipes-kernel/linux/kmeta-linux-lmp-5.10.y.inc, meta-lmp-bsp/conf/machine/include/lmp-machine-custom.inc, meta-lmp-bsp/dynamic-layers/meta-ti-bsp/recipes-bsp/u-boot/u-boot-ti-staging_%.bbappend, meta-lmp-bsp/recipes-kernel/linux/linux-lmp-ti-staging_git.bb
=> Ti BSP update to 08.06.00.007

meta-lmp-base/recipes-security/optee/optee-fiovb_git.bb
- 8e898d1 ta: decrease verbosity of read_value()
=> base: optee-fiovb: bump revision to 8e898d1

meta-lmp-base/recipes-support/lmp-el2go-auto-register/lmp-el2go-auto-register.bb, meta-lmp-base/recipes-support/lmp-el2go-auto-register/lmp-el2go-auto-register/lmp-el2go-auto-register
Replace ssscli with fio-se05x-cli.
We should notice a performance improvement
=> base: lmp-el2go-auto-register: replace ssscli

meta-lmp-bsp/dynamic-layers/meta-ti-bsp/recipes-bsp/u-boot/u-boot-ti-staging/lib-zlib-Fix-a-bug-when-getting-a-gzip-header-extra-field.patch, meta-lmp-bsp/dynamic-layers/meta-ti-bsp/recipes-bsp/u-boot/u-boot-ti-staging_%.bbappend
Add the patch to fix CVE-2022-37434 bug in zlib.
This solves https://foundriesio.atlassian.net/browse/FFTK-2495 for AMxxx
=> bsp: u-boot-ti-staging: fix CVE-2022-37434

meta-lmp-base/recipes-kernel/xenomai4/xenomai4_git.bb
pick rwlock: fix trylock() error check
=> base: xenomai4: bump version

meta-lmp-bsp/recipes-kernel/linux/linux-lmp-ti-staging_git.bb
Changes required in order to be aligned with https://github.com/foundriesio/lmp-manifest/pull/354
=> TI BSP update to 202306291638

meta-lmp-base/recipes-sota/aktualizr/aktualizr_%.bbappend
Split the aktualizr-lite-apps and aktualizr-lite-offline from main aktualizr package.
Aktualizr has been split into two new packages to better track dependencies.
Now the aklite-offline and aklite-apps can  be provided to custom sota client  without needing to include the aktualizr package.
New Packages:
- aktualizr-lite-offline:  /usr/bin/aklite-offline
- aktualizr-lite-apps:    /usr/bin/aklite-apps
=> base: aktualizr: Split aktualizr-lite apps packages

meta-lmp-bsp/conf/layer.conf, meta-lmp-bsp/conf/machine/include/lmp-machine-custom.inc, meta-lmp-bsp/dynamic-layers/meta-ti-extras/recipes-connectivity/wlconf/wlconf_8.7.3.bbappend, meta-lmp-bsp/recipes-kernel/linux-firmware/linux-firmware_%.bbappend
Prefer using the wilink firmware files and recipes from meta-ti-extras, now that it is available in lmp.
=> TI wilink clean up

meta-lmp-base/recipes-kernel/linux/linux-lmp-dev-mfgtool_git.bb, meta-lmp-base/recipes-kernel/linux/linux-lmp-dev.bb, meta-lmp-bsp/recipes-kernel/linux/linux-lmp-fslc-imx_6.1.bb
Tested building and booting with:
- imx8mm-lpddr4-evk
- imx6ullevk
=> Upgrade linux kernel to 6.1.38 aligned with NXP BSP LF6.1.22_2.0.0

meta-lmp-bsp/dynamic-layers/freescale-layer/recipes-bsp/imx-mkimage/imx-boot/0001-iMX9-add-SPL-only-build.patch
Refresh 0001-iMX9-add-SPL-only-build.patch on top of lf-6.1.22_2.0.0.
=> bsp: imx-boot: refresh imx9 patch

meta-lmp-base/recipes-containers/docker-compose/docker-compose_2.20.2.bb, meta-lmp-base/recipes-containers/docker/docker-ce_git.bb
Versions aligned with the upstream docker v24.0.5 packaging.
=> Update docker to v24.0.5 and compose to v2.20.2 

meta-lmp-bsp/dynamic-layers/tegra/recipes-bsp/tegra-binaries/tegra-helper-scripts/initrd-flash.sh
Update forked script based on the changes done for R35.4.1.
Main change is that --user_key was now removed.
=> bsp: tegra-helper-scripts: update initrd-flash.sh based on R35.4.1

meta-lmp-base/recipes-sota/aktualizr/aktualizr_%.bbappend
- a8d0bfe: Load images to docker store efficiently
=> base: rs: aktualizr: Bump aklite ver to a8d0bfe

meta-lmp-base/conf/distro/include/lmp.inc, meta-lmp-base/recipes-core/base-files/base-files-issue.bb, meta-lmp-base/recipes-core/base-files/base-files_%.bbappend
- Fix sstate-cache invalidation of the kernel initrd images
=> Fix kernel initrd images rebuild on CI

meta-lmp-base/recipes-security/optee/optee-fiovb_git.bb
Relevant Changes:
- 2c20a4a ta: partially revert 4a353de
=> base: Bump optee-fiovb to 2c20a4a

meta-lmp-base/recipes-sota/aktualizr/aktualizr_%.bbappend
- 21f25da cli: Add param to delay App installation
- 7d5d6be api: Add delayed App installation mode
=> base: rs: aktualizr: bump version to e5106f2

meta-lmp-base/recipes-sota/aktualizr/aktualizr_%.bbappend
- a11bf7d cmake: Add BUILD_P11 option to aklite
- 0bcf0f1 offline: Require all enabled apps for offline update
=> base: rs: aktualizr: bump version to 1345b23

meta-lmp-base/classes/lmp-staging.bbclass
Follow meta-ti 9b4f5af61 and switch mcdepends from do_image_complete to do_image.
=> base: lmp-staging: k3: switch mcdepends from do_image_complete

meta-lmp-bsp/dynamic-layers/freescale-layer/recipes-bsp/imx-mkimage/imx-boot/0001-iMX9-add-SPL-only-build.patch
Refresh patches against the lf-6.1.36-2.1.0 release.
=> bsp: imx-boot: refresh patches

meta-lmp-bsp/dynamic-layers/meta-ti-bsp/recipes-support/ti-mfgtool-files/ti-mfgtool-files/flash.sh.in
meta-ti-bsp: add fixes and improvements to flash.sh
=> TI flash fixes

meta-lmp-base/conf/distro/include/cve-lmp-extra-exclusions.inc, meta-lmp-base/conf/distro/include/lmp.inc
Add basic cve-check configs and extra exclusions for lmp.
=> base: add basic configs for cve-check

meta-lmp-base/classes/lmp-staging.bbclass, meta-lmp-bsp/conf/machine/include/lmp-machine-custom.inc, meta-lmp-bsp/conf/multiconfig/lmp-k3r5.conf, meta-lmp-bsp/dynamic-layers/meta-ti-bsp/recipes-bsp/lmp-boot-firmware/lmp-boot-firmware.bbappend, meta-lmp-bsp/dynamic-layers/meta-ti-bsp/recipes-kernel/linux/linux-lmp-ti-staging_git.bb
Wainting the last piece to be merged https://lists.yoctoproject.org/g/meta-ti/topic/102547765
=> TI stable kirkstone bump

meta-lmp-base/recipes-kernel/linux/kmeta-linux-lmp-6.1.y.inc, meta-lmp-bsp/conf/machine/include/lmp-machine-custom.inc, meta-lmp-bsp/dynamic-layers/meta-ti-bsp/recipes-bsp/u-boot/u-boot-bb.org_%.bbappend, meta-lmp-bsp/dynamic-layers/meta-ti-bsp/recipes-kernel/linux/linux-lmp-ti-staging_git.bb
Align with changes from meta-ti cicd.kirkstone.202401090400.
=> Ti: update BSP to cicd.kirkstone.202401090400

recipes-sota/aktualizr/aktualizr-callback_1.0.bb
=> base: correct aktualizr-callback RDEPENDS

meta-lmp-bsp/dynamic-layers/meta-ti-bsp/recipes-bsp/u-boot/u-boot-ti-staging/am62xx-evm/lmp.cfg
Load boot.itb file from eMMC on AM62xx.
=> bsp: u-boot-ti-staging: am62xx-evm: load boot.itb from eMMC

meta-lmp-base/recipes-support/fioconfig/fioconfig_git.bb
This brings in a newer fioconfig that has improvements for parsing the sota toml files.
=> base: fioconfig: Bump version

meta-lmp-bsp/dynamic-layers/xilinx-tools/recipes-utils/fru-print/fru-print.bb
Branch was renamed upstream from master to main.
=> bsp: fru-print: move upstream branch to main

meta-lmp-bsp/dynamic-layers/tegra/recipes-bsp/tegra-binaries/tegra-helper-scripts/initrd-flash.sh
Bring missing changes during the BSP update to 35.5.0:
- https://github.com/OE4T/meta-tegra/commit/c106a81d515ba9d1aff2f9b9fb28e972e93fa97e
- https://github.com/OE4T/meta-tegra/commit/c69a7d47a6e7cb220881b564ce94fd3689eba78d
- https://github.com/OE4T/meta-tegra/commit/f619e64dddef91ff80b3013ea4e6a51a54083a66
=> bsp: tegra: initrd-flash.sh: update based on latest meta-tegra changes

meta-lmp-base/recipes-security/optee/optee-os-fio-se05x.inc, meta-lmp-base/recipes-security/optee/optee-os-fio.inc
Define SRCREV_FORMAT for the Plug-and-Trust expansion.
=> scarthgap: se05x: fix expansion of multiple URI

meta-lmp-base/recipes-containers/composeapp/composectl_git.bb
- 052ae81 test: Remove bash usage in shell script
=> base: rc: composectl: Bump ver 052ae81

meta-lmp-base/conf/distro/include/lmp.inc, meta-lmp-base/recipes-core/systemd/systemd_%.bbappend
- add pstore
- add conditional for pni-names
- enable pni-names by default
=> systemd updates for scarthgap

meta-lmp-base/recipes-sota/aktualizr/aktualizr_%.bbappend
- a2b704d api: Fix apps-only rollback when using delay-app-install
- e852901 aktualizr: Add ostree manager fixes for partial commits
=> base: rs: aklite: Bump to 9034bdf

meta-lmp-base/recipes-sota/aktualizr/aktualizr_%.bbappend
- f8a987c2 composeappmanager: Force app installation if enabled
- 3fb10b94 e2e-tests: Fix format of yaml files generated by entrypoint.sh
=> base: rs: aklite: Bump to 6cda15b7

.github/workflows/backport.yaml
Based on the same workflow as used by meta-freescale.
=> ci: add backport github workflow

.github/workflows/backport.yaml
Update backport workflow to use the korthout/backport-action@v3 instead, which has better support for rebase & merge prs.
=> ci: backport: update to korthout/backport-action@v3

meta-lmp-base/recipes-containers/docker/files/daemon.json.in, meta-lmp-base/recipes-containers/wayland-cdi/files/wayland-cdi-generate, meta-lmp-base/recipes-containers/wayland-cdi/files/wayland-cdi.service, meta-lmp-base/recipes-containers/wayland-cdi/wayland-cdi_0.1.bb, meta-lmp-base/recipes-samples/images/lmp-feature-docker.inc
=> scarthgap: backport #1518
